"""News event pools for the CA / EV scenario.

  COMPETITOR_NEWS_POOL: (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
  DEPT_NEWS_POOL:       (headline, detail, dept_name, k_mult, smax_mult, sentiment)
  GENERAL_NEWS_POOL:    (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
"""

COMPETITOR_NEWS_POOL = [
    # 40 POSITIVE
    ('Federal Government Expands iZEV Rebate to $10,000: {{company}} Models Qualify', 'Expanded Incentives for Zero-Emission Vehicles programme widens the addressable buyer pool across Canada.', (1.10, 1.20), (2_700_000, 7_200_000), 'positive'),
    ('{{company}} Battery Breakthrough Improves Cold-Weather Range by 22%', 'New thermal management system addresses Canada\'s top EV concern: winter range loss.', (1.08, 1.18), (1_800_000, 5_400_000), 'positive'),
    ('Canada Infrastructure Bank Funds Nationwide Charging Network', '10,000 new fast-chargers planned along Trans-Canada Highway and northern corridors.', (1.06, 1.14), (1_400_000, 4_500_000), 'positive'),
    ('{{company}} Wins Major Fleet Contract with Canada Post', '8,000-unit purchase order for last-mile delivery vehicles locks in three years of fleet revenue.', (1.12, 1.22), (3_600_000, 8_100_000), 'positive'),
    ('CAA Names {{company}} Top EV Pick for Canadian Drivers', 'Reliability and winter performance scores drive record inbound leads from all-season segment.', (1.06, 1.12), (1_400_000, 3_600_000), 'positive'),
    ('Lithium Prices Fall as Quebec Mining Output Surges', 'Domestic lithium supply from Abitibi region stabilises battery costs across Canadian EV manufacturers.', (1.04, 1.10), (1_800_000, 5_400_000), 'positive'),
    ('{{company}} Partners with Hydro-Québec on Integrated Home Charging', 'Bundled charging solution with provincially subsidised installation accelerates adoption in Quebec.', (1.07, 1.15), (1_400_000, 4_000_000), 'positive'),
    ('{{company}} Awarded Five-Star IIHS Top Safety Pick+', 'Top safety designation generates extensive coverage in Canadian automotive press.', (1.06, 1.13), (1_600_000, 4_300_000), 'positive'),
    ('Record EV Sales Quarter in Canada: Market Exceeds Forecasts', 'Pent-up demand and falling battery costs drive industry-wide volume surge across all provinces.', (1.08, 1.16), (2_200_000, 5_800_000), 'positive'),
    ('{{company}} Launches Industry-Leading 10-Year Cold-Climate Battery Warranty', 'Bold warranty addresses resale anxiety in harsh Canadian winters and drives enquiry surge.', (1.07, 1.14), (1_800_000, 4_700_000), 'positive'),
    ('Solid-State Battery Partnership Announced: {{company}} Secures Early Access', 'Joint development with University of Waterloo grants exclusive early-production allocation.', (1.09, 1.18), (2_300_000, 6_300_000), 'positive'),
    ('{{company}} Named EV Manufacturer of the Year at Canadian Auto Show', 'Prestigious award reinforces brand credibility across English and French Canadian markets.', (1.05, 1.12), (1_300_000, 3_400_000), 'positive'),
    ('Federal Fleet Electrification Mandate: {{company}} On Approved Vendor List', 'Ottawa mandates 100% ZEV federal fleet by 2027; approved vendors gain first-mover advantage.', (1.10, 1.19), (2_700_000, 6_800_000), 'positive'),
    ('EV Insurance Costs Fall 18% as Canadian Actuarial Data Matures', 'Lower premiums reduce total cost of ownership, removing barrier for prairie province buyers.', (1.04, 1.09), (1_100_000, 3_100_000), 'positive'),
    ('{{company}} Over-the-Air Update Delivers 15% Winter Range Improvement', 'Software update addressing cold-weather efficiency delights Canadian owners and generates viral coverage.', (1.06, 1.12), (1_400_000, 3_800_000), 'positive'),
    ('Major Canadian Ride-Share Platform Selects {{company}} as Preferred Supplier', 'Preferred supplier status delivers guaranteed volume across Toronto, Vancouver, and Montreal.', (1.09, 1.17), (2_500_000, 5_900_000), 'positive'),
    ('{{company}} Ontario Plant Expansion Approved: Capacity Doubles by Year 3', 'Ontario government fast-tracks permits for Markham facility expansion.', (1.08, 1.15), (2_000_000, 5_000_000), 'positive'),
    ('Competitor Recall Diverts 60,000 Canadian Buyers: {{company}} Captures Demand', 'High-profile rival recall creates conversion opportunity in GTA and Metro Vancouver markets.', (1.11, 1.20), (2_900_000, 7_200_000), 'positive'),
    ('{{company}} Tops J.D. Power Canada EV Ownership Satisfaction Study', 'Highest satisfaction score for a Canadian EV brand; NPS lifts materially.', (1.06, 1.12), (1_400_000, 3_600_000), 'positive'),
    ('Carbon Credit Revenue Exceeds Forecast: {{company}} Books C$36M Windfall', 'Strong credit demand from legacy OEMs in Canada generates unexpected non-operating income.', (1.04, 1.09), (1_800_000, 5_000_000), 'positive'),
    ('{{company}} Signs Long-Term Lithium Offtake with Patriot Battery Metals', 'Multi-year supply contract with Quebec-based miner hedges against commodity volatility.', (1.06, 1.13), (1_600_000, 4_300_000), 'positive'),
    ('BC Hydro Grid Upgrade Unlocks Interior BC and Northern EV Adoption', 'Infrastructure investment expands addressable market into previously underserved Canadian regions.', (1.05, 1.11), (1_300_000, 3_400_000), 'positive'),
    ('{{company}} Autonomous Feature Achieves Transport Canada Level 3 Approval', 'First mass-market EV with approved Level 3 autonomy on Canadian highways.', (1.09, 1.18), (2_300_000, 6_100_000), 'positive'),
    ('Employer EV Salary-Sacrifice Schemes Expand Across Ontario and BC', 'Tax-efficient benefit programme drives strong commercial pipeline growth in key provinces.', (1.06, 1.13), (1_600_000, 4_100_000), 'positive'),
    ('{{company}} Wins Sustainability Award from Canadian Standards Association', 'CSA recognition amplifies ESG credentials and attracts Bay Street institutional interest.', (1.05, 1.11), (1_100_000, 2_900_000), 'positive'),
    ('Alberta Announces Surprise EV Incentive Programme: New Market Opens', 'Previously holdout province launches C$5,000 rebate, creating fresh demand in Western Canada.', (1.08, 1.16), (2_200_000, 5_800_000), 'positive'),
    ('Quebec Mandates 100% ZEV Sales by 2035: Demand Certainty Locked In', 'Provincial legislation provides long-term demand visibility for EV manufacturers in Canada\'s second-largest market.', (1.07, 1.14), (1_800_000, 4_700_000), 'positive'),
    ('Trans-Canada Highway Fast-Charging Corridor Project Completes Phase 1', 'Coast-to-coast charging removes range anxiety for long-distance Canadian road trips.', (1.05, 1.12), (1_400_000, 4_000_000), 'positive'),
    ('{{company}} Selected for RCMP Fleet Pilot Programme', 'Federal law enforcement pilot creates high-visibility validation and opens institutional channel.', (1.07, 1.15), (1_800_000, 4_700_000), 'positive'),
    ('Canadian Dollar Strengthens: Import Costs for Components Fall', 'Favourable FX movement reduces bill-of-materials cost for imported battery modules.', (1.04, 1.09), (1_300_000, 3_400_000), 'positive'),
    ('{{company}} Partners with Loblaws for Destination Charging at 500 Stores', 'Charging network at Canada\'s largest retailer creates brand touchpoints during grocery runs.', (1.05, 1.12), (1_300_000, 3_800_000), 'positive'),
    ('NRCan Awards {{company}} C$25M Clean Technology Grant', 'Natural Resources Canada grant funds next-generation cold-weather battery development programme.', (1.06, 1.13), (1_600_000, 4_300_000), 'positive'),
    ('{{company}} Achieves Record 4.9 Star Rating on Google Reviews Canada', 'Organic customer advocacy drives unprecedented inbound lead volume across digital channels.', (1.05, 1.11), (1_200_000, 3_200_000), 'positive'),
    ('Oil Sands Workers Pivot to EV Manufacturing: Alberta Labour Pool Deepens', 'Skilled tradespeople transitioning from oil sector provide experienced manufacturing workforce.', (1.04, 1.09), (1_100_000, 2_900_000), 'positive'),
    ('{{company}} Named Best Canadian EV by Globe and Mail Drive Section', 'Major national newspaper endorsement drives consideration across English Canada.', (1.05, 1.11), (1_300_000, 3_400_000), 'positive'),
    ('Provincial Rebate Stacking Allows C$15,000 Combined Incentive in Quebec', 'Federal iZEV plus provincial rebate creates strongest purchase incentive in North America.', (1.08, 1.16), (2_200_000, 5_800_000), 'positive'),
    ('{{company}} Winter Testing Programme in Yellowknife Validates -40°C Performance', 'Extreme cold validation generates compelling marketing content and builds buyer confidence.', (1.06, 1.13), (1_400_000, 3_800_000), 'positive'),
    ('Canadian Pension Funds Increase EV Sector Allocation: {{company}} Included', 'CPP and CDPQ institutional investment signals long-term confidence in Canadian EV sector.', (1.05, 1.11), (1_200_000, 3_200_000), 'positive'),
    ('{{company}} Launches French-Language Digital Experience for Quebec Market', 'Fully localised Québécois digital platform drives 30% increase in provincial leads.', (1.05, 1.12), (1_300_000, 3_600_000), 'positive'),
    ('Federal Budget Allocates C$3B to Domestic EV Manufacturing Support', 'Landmark investment programme anchors EV supply chain in Canada for the next decade.', (1.07, 1.15), (1_800_000, 4_700_000), 'positive'),

    # 40 NEGATIVE
    ('Federal iZEV Rebate Programme Suspended Pending Budget Review', 'Incentive freeze creates wait-and-see behaviour among Canadian buyers. Orders pause nationwide.', (0.84, 0.92), (-8_100_000, -3_600_000), 'negative'),
    ('{{company}} Faces Class-Action Lawsuit Over Winter Range Claims', 'Plaintiffs allege advertised range overstates real-world cold-weather performance by 35%.', (0.83, 0.91), (-9_000_000, -4_100_000), 'negative'),
    ('Polar Vortex Strands EV Drivers Across Prairies: Media Frenzy', 'Extreme cold event generates wall-to-wall negative coverage of EV winter reliability.', (0.82, 0.90), (-9_500_000, -4_500_000), 'negative'),
    ('Trans-Canada Shipping Disruption: Rail Strike Blocks Component Delivery', 'CN Rail work stoppage halts parts shipments from Vancouver port to Ontario assembly plants.', (0.84, 0.92), (-8_500_000, -3_800_000), 'negative'),
    ('Ontario Hydro Rate Hike Erodes EV Running Cost Advantage', 'Time-of-use electricity price increases narrow the gap between EV and ICE operating costs.', (0.86, 0.93), (-5_800_000, -2_200_000), 'negative'),
    ('{{company}} Recalls 22,000 Units Over Heating System Software Defect', 'Cabin heater malfunction in sub-zero conditions triggers Transport Canada mandatory recall.', (0.82, 0.91), (-8_300_000, -3_400_000), 'negative'),
    ('US-Canada Trade Tensions Raise {{company}} Component Import Costs 12%', 'New tariff round covers electronic modules sourced from US suppliers.', (0.85, 0.93), (-6_700_000, -2_900_000), 'negative'),
    ('{{company}} Loses Key Battery Engineer to US Rival', 'Departure of principal thermal management architect signals talent drain to higher-paying US market.', (0.87, 0.94), (-5_400_000, -2_000_000), 'negative'),
    ('Viral Campaign Targets {{company}} on Cobalt Mining Ethics', 'Activist group challenges supply chain practices; brand trust drops among eco-conscious segment.', (0.85, 0.93), (-6_100_000, -2_500_000), 'negative'),
    ('Semiconductor Shortage Returns: {{company}} Cuts Canadian Production by 20%', 'Global chip constraints force output reduction at Ontario and Quebec facilities.', (0.83, 0.92), (-7_600_000, -3_200_000), 'negative'),
    ('{{company}} Credit Rating Downgraded by DBRS Morningstar', 'Rating agency cites cash burn and intense competition; debt refinancing costs rise.', (0.87, 0.94), (-5_600_000, -2_200_000), 'negative'),
    ('New Carbon Tax Increase Raises Manufacturing Costs Across Canada', 'Federal carbon price escalation adds $400 per vehicle to production costs.', (0.86, 0.93), (-6_300_000, -2_700_000), 'negative'),
    ('{{company}} Denied Expansion Permit by Municipality Near Toronto', 'Local opposition blocks planned Brampton gigafactory; capacity expansion delayed indefinitely.', (0.86, 0.93), (-5_900_000, -2_300_000), 'negative'),
    ('EV Market Softness: Canadian Consumer Purchase Intent Falls 16%', 'High interest rates and housing affordability crisis dampen discretionary vehicle purchases.', (0.85, 0.93), (-6_500_000, -2_700_000), 'negative'),
    ('{{company}} CFO Resignation Triggers Bay Street Short Seller Attack', 'Opportunistic short report published day of departure; TSX share price falls sharply.', (0.86, 0.93), (-5_900_000, -2_300_000), 'negative'),
    ('Ice Storm Knocks Out Charging Infrastructure Across Southern Ontario', 'Multi-day power outage leaves thousands of EV owners stranded; negative media cycle erupts.', (0.84, 0.92), (-7_200_000, -3_000_000), 'negative'),
    ('Port of Vancouver Strike Delays {{company}} Component Shipments by 6 Weeks', 'ILWU work action at Canada\'s busiest port backs up Pacific supply chain.', (0.85, 0.93), (-6_300_000, -2_500_000), 'negative'),
    ('{{company}} Loses Exclusive Petro-Canada Charging Partnership to Rival', 'Competitor secures exclusivity at 2,000 Petro-Canada charging locations.', (0.87, 0.94), (-5_200_000, -2_000_000), 'negative'),
    ('Flooding at Quebec Battery Supplier Disrupts Production', 'Spring flood season damages primary cell supplier facility; force majeure declared.', (0.83, 0.92), (-7_800_000, -3_400_000), 'negative'),
    ('{{company}} Product Liability Case Settled for C$72M', 'Settlement of personal injury claim on icy highway sets precedent for future litigation.', (0.86, 0.93), (-6_100_000, -2_500_000), 'negative'),
    ('Viral Video of {{company}} Battery Fire in Toronto Parking Garage Gets 40M Views', 'Isolated thermal event generates disproportionate national media coverage.', (0.81, 0.91), (-8_500_000, -3_800_000), 'negative'),
    ('Retaliatory Canadian Tariff on Chinese EV Components Raises Costs', 'Trade policy response increases bill-of-materials cost for Canadian manufacturers.', (0.84, 0.92), (-7_200_000, -3_100_000), 'negative'),
    ('{{company}} ADAS Feature Fails Transport Canada Safety Audit', 'Audit failure in winter driving conditions requires feature suspension via OTA update.', (0.85, 0.93), (-6_300_000, -2_500_000), 'negative'),
    ('Supply Chain Audit Finds Labour Violations at {{company}} Overseas Supplier', 'Ethical sourcing concerns force rapid supplier transition; cost and timeline impact significant.', (0.86, 0.93), (-5_800_000, -2_300_000), 'negative'),
    ('Bank of Canada Rate Hike Makes Auto Financing 18% More Expensive', 'Tightening monetary policy pushes monthly payments beyond threshold for middle-income families.', (0.84, 0.92), (-7_200_000, -3_100_000), 'negative'),
    ('Canadian Automotive Workers Union Demands 15% Wage Increase', 'Unifor hardline bargaining position threatens production continuity at Ontario assembly plant.', (0.85, 0.93), (-6_500_000, -2_700_000), 'negative'),
    ('{{company}} Faces Patent Infringement Ruling from Federal Court', 'Court requires retroactive royalty payments and ongoing per-unit licensing fees.', (0.86, 0.93), (-6_800_000, -2_900_000), 'negative'),
    ('Consumer Watchdog Report Cites {{company}} for Poor Winter Service', 'Low service satisfaction scores in cold-weather provinces go viral on social media.', (0.85, 0.93), (-5_900_000, -2_300_000), 'negative'),
    ('Alberta Premiers Threaten Anti-EV Legislation Over Oil Sector Concerns', 'Political opposition to EVs in Western Canada creates regulatory uncertainty.', (0.86, 0.94), (-5_400_000, -2_000_000), 'negative'),
    ('{{company}} Loses Major Municipal Fleet Contract to Chinese Competitor', 'City of Toronto selects lower-cost Chinese EV for 3,000-vehicle fleet order.', (0.85, 0.93), (-6_500_000, -2_700_000), 'negative'),
    ('Benchmark Canadian EV Test Ranks {{company}} Last on DC Charging Speed', 'Poor real-world fast-charging performance widely reported in Canadian media.', (0.86, 0.94), (-5_200_000, -2_000_000), 'negative'),
    ('Border Crossing Delays Add 3 Days to US-Sourced Parts Lead Time', 'Enhanced customs inspections at Windsor-Detroit crossing disrupt just-in-time supply chain.', (0.86, 0.93), (-5_800_000, -2_300_000), 'negative'),
    ('{{company}} Investigated by Competition Bureau for Dealer Contract Terms', 'Competition authority probe forces contract renegotiation and generates negative press.', (0.87, 0.94), (-5_000_000, -1_800_000), 'negative'),
    ('Wildfire Smoke Disrupts BC Operations and Logistics for 3 Weeks', 'Air quality emergency forces partial plant shutdown and delivery delays in Western Canada.', (0.85, 0.93), (-6_500_000, -2_700_000), 'negative'),
    ('{{company}} French-Language Marketing Misstep Causes Quebec Backlash', 'Culturally insensitive advertising campaign damages brand in critical Quebec market.', (0.86, 0.93), (-5_600_000, -2_200_000), 'negative'),
    ('Housing Affordability Crisis Diverts Consumer Spending Away from EVs', 'Mortgage stress test and rising rents reduce discretionary spending on new vehicles.', (0.85, 0.93), (-6_300_000, -2_500_000), 'negative'),
    ('{{company}} Battery Degradation Data Leaks: Canadian Owners Concerned', 'Internal telemetry data showing above-expected degradation in cold climates sparks media coverage.', (0.84, 0.92), (-7_000_000, -2_900_000), 'negative'),
    ('Competitor Launches Aggressive Price War in Canadian Market', 'Two rivals cut MSRP by C$5,000 simultaneously, compressing margins across the sector.', (0.84, 0.92), (-7_200_000, -3_100_000), 'negative'),
    ('{{company}} Loses Key Sponsorship of Hockey Night in Canada', 'Failure to renew iconic sports sponsorship reduces brand visibility in prime advertising slot.', (0.87, 0.94), (-5_200_000, -2_000_000), 'negative'),
    ('Federal Carbon Price Ruled Unconstitutional by Alberta Court', 'Legal challenge creates policy uncertainty affecting EV incentive framework nationwide.', (0.86, 0.93), (-5_600_000, -2_200_000), 'negative'),

    # 20 NEUTRAL
    ('Canadian EV Market Grows 42% YoY, but Competition Intensifies', 'Total EV sales surge, but new entrants from Asia and legacy OEMs compress margins.', (0.96, 1.06), (-1_800_000, 2_700_000), 'neutral'),
    ('{{company}} Restructures Dealer Network Ahead of Direct-Sales Push', 'Transition creates friction with dealer partners but should improve margins long-term.', (0.93, 1.03), (-2_700_000, 1_800_000), 'neutral'),
    ('Transport Canada Proposes New Crash Safety Standards for EVs', 'Compliance costs increase but {{company}} existing safety scores provide a head start.', (0.95, 1.02), (-3_600_000, 1_400_000), 'neutral'),
    ('Industry Body Proposes Canadian EV Charging Protocol Standard', 'Proposed standard requires minor hardware updates; timelines uncertain.', (0.96, 1.04), (-2_200_000, 1_600_000), 'neutral'),
    ('{{company}} Undertakes Leadership Team Restructure', 'C-suite reshuffle brings operational talent but introduces short-term execution risk.', (0.94, 1.03), (-2_500_000, 1_800_000), 'neutral'),
    ('Canadian Battery Recycling Regulations Tighten', 'New end-of-life obligations require investment; financial magnitude being quantified.', (0.95, 1.02), (-3_200_000, 1_300_000), 'neutral'),
    ('Survey Shows Rising Canadian EV Awareness But Unchanged Purchase Timelines', 'Brand awareness improves but conversion constrained by affordability and winter concerns.', (0.96, 1.04), (-1_400_000, 2_000_000), 'neutral'),
    ('{{company}} Pilot Programme for Autonomous Feature Launches in Toronto', 'Limited trial generates positive press but financial contribution immaterial near-term.', (0.97, 1.04), (-1_600_000, 2_000_000), 'neutral'),
    ('Electricity Grid Study Highlights Charging Load Challenges in Northern Ontario', 'Study identifies bottlenecks but confirms scale of suppressed demand in underserved regions.', (0.96, 1.03), (-1_800_000, 1_400_000), 'neutral'),
    ('{{company}} Completes Mid-Cycle Refresh: Reception Mixed', 'Updated exterior well received; cold-weather range improvement smaller than hoped.', (0.95, 1.04), (-2_200_000, 2_300_000), 'neutral'),
    ('New PIPEDA Updates Affect {{company}} Connected Car Data Collection', 'Privacy law changes require consent adjustments; some connected features modestly reduced.', (0.95, 1.02), (-2_700_000, 1_100_000), 'neutral'),
    ('Canadian EV TCO Comparison Published: {{company}} Mid-Table', 'Total cost of ownership competitive but not leading versus best-in-class alternatives.', (0.96, 1.03), (-1_400_000, 1_400_000), 'neutral'),
    ('{{company}} Annual Investor Day Held: Targets Reaffirmed', 'Management confirms five-year roadmap; no material changes to guidance.', (0.97, 1.03), (-1_100_000, 1_600_000), 'neutral'),
    ('Canadian Auto Sector Talent War Intensifies: Engineering Salaries Rise', 'Retention investment necessary; partially offset by reduced recruitment cost.', (0.96, 1.02), (-2_300_000, 1_100_000), 'neutral'),
    ('{{company}} Engages Third-Party ESG Audit', 'Proactive audit likely to confirm compliance; outcome uncertain.', (0.96, 1.03), (-1_600_000, 1_400_000), 'neutral'),
    ('{{company}} Announces Leadership Restructuring: Strategy Unchanged', 'Board-level changes prompt media speculation but operational guidance reaffirmed.', (0.97, 1.03), (-900_000, 1_400_000), 'neutral'),
    ('Supply Chain Audit Reveals Mixed Results for {{company}}', 'Some component lines improved, others flagged for diversification.', (0.96, 1.04), (-1_400_000, 1_400_000), 'neutral'),
    ('{{company}} Files Patent Portfolio Expansion in Canada', 'New IP filings signal future direction. Analyst opinions split on near-term impact.', (0.97, 1.03), (-900_000, 1_800_000), 'neutral'),
    ('Canadian Auto Industry Conference Highlights Shifting Preferences', 'Market research suggests gradual demand evolution. No immediate disruption expected.', (0.96, 1.04), (-1_400_000, 1_400_000), 'neutral'),
    ('{{company}} Quarterly Earnings Meet Bay Street Expectations', 'Inline results neither excite nor concern investors. TSX listing trades flat.', (0.97, 1.03), (-900_000, 900_000), 'neutral'),
]


DEPT_NEWS_POOL = [
    # Operations negative
    ("Global Lithium Shortage Impacts Canadian Battery Supply Chain",
     "Lithium prices spike 40%. Manufacturers without locked-in Canadian mining contracts face delays.",
     "Operations", 1.40, 0.80, "negative"),
    ("CN Rail Strike Blocks Component Shipments Across Canada",
     "National rail work stoppage halts parts delivery from Vancouver to Ontario assembly plants.",
     "Operations", 1.30, 0.85, "negative"),
    ("Unifor Calls Strike at Ontario Assembly Plant",
     "Labour dispute at key facility threatens Q3 production targets. Output could drop 25%.",
     "Operations", 1.35, 0.75, "negative"),
    ("Critical Assembly Robot Failure Halts Line for 2 Weeks",
     "Proprietary welding robot fails. Replacement parts on 14-day lead time from Germany.",
     "Operations", 1.35, 0.80, "negative"),
    ("Quebec Battery Cell Supplier Declares Force Majeure After Fire",
     "Key Tier-1 supplier cites fire damage. Alternative sourcing at 30% cost premium.",
     "Operations", 1.40, 0.75, "negative"),
    ("Environment Canada Tightens Factory Emissions Standards",
     "New regulations require C$14M scrubber installation. Production paused during fit-out.",
     "Operations", 1.25, 0.85, "negative"),
    ("Spring Flooding Destroys C$9M in Finished Inventory in Ontario",
     "Extreme weather damages 350 completed vehicles at Markham distribution centre.",
     "Operations", 1.20, 0.80, "negative"),
    ("Nickel Price Spike Raises Battery Pack Costs by 24%",
     "Sudbury mine disruption and global demand surge increase key input costs materially.",
     "Operations", 1.30, 0.85, "negative"),
    ("Quality Audit Reveals Defective Wiring Harness in 4,500 Units",
     "Internal QA flags issue before delivery. Rework required on all affected Canadian-built vehicles.",
     "Operations", 1.25, 0.80, "negative"),
    ("US Border Semiconductor Controls Cut Canadian Chip Allocation by 30%",
     "New US export rules reduce chip availability for Canadian manufacturers.",
     "Operations", 1.35, 0.80, "negative"),
    # Operations positive
    ("Ontario Government Awards C$60M Advanced Manufacturing Grant",
     "Provincial grant for domestic EV production accelerates factory upgrades.",
     "Operations", 0.80, 1.20, "positive"),
    ("New Gigapress Installation Cuts Body Assembly Time by 40%",
     "Single-piece casting technology at Toronto plant eliminates 70 weld points.",
     "Operations", 0.75, 1.25, "positive"),
    ("Long-Term Nickel Contract Locks In Below-Market Pricing from Sudbury",
     "Five-year offtake with Vale Canada secures key input at 18% below spot.",
     "Operations", 0.80, 1.15, "positive"),
    ("Factory Achieves ISO 14001 Environmental Certification",
     "Certification unlocks green bond financing and reduces facility insurance premiums.",
     "Operations", 0.85, 1.15, "positive"),
    ("Second Shift Ramp-Up at Ontario Plant Completes Ahead of Schedule",
     "Night shift fully staffed and trained two months early. Effective capacity doubles.",
     "Operations", 0.75, 1.25, "positive"),
    ("New Battery Recycling Line Opens at Quebec Facility",
     "In-house recycling recovers 92% of cathode materials. Raw material costs drop.",
     "Operations", 0.80, 1.20, "positive"),
    ("Dedicated EV Distribution Hub Opens Near Montreal",
     "Purpose-built facility cuts average delivery time across Eastern Canada by 3 days.",
     "Operations", 0.85, 1.15, "positive"),
    ("AI Quality Vision System Cuts Defect Rate by 60%",
     "AI-powered inspection catches micro-defects invisible to human inspectors.",
     "Operations", 0.80, 1.20, "positive"),
    ("Hydro-Québec PPA Signed: Factory Runs on 100% Clean Hydro Power",
     "Power purchase agreement locks in lowest electricity rates in North America.",
     "Operations", 0.85, 1.15, "positive"),
    ("Strategic Parts Warehouse Opens in Winnipeg for Central Canada",
     "Regional hub cuts service turnaround from 5 days to next-day for prairie provinces.",
     "Operations", 0.85, 1.15, "positive"),
    # Operations neutral
    ("Industry-Wide Shift to LFP Chemistry: Canadian Plants Retooling",
     "Lower cost but different process. Retooling investment needed; long-term benefit unclear.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Unifor Contract Renewal Negotiations Begin for Ontario Plant",
     "Current agreement expires in 90 days. Talks expected to be constructive.",
     "Operations", 1.05, 0.98, "neutral"),
    ("New Provincial Workplace Safety Protocols Require Additional Training",
     "Compliance straightforward but reduces productive hours by 3% during transition.",
     "Operations", 1.08, 0.97, "neutral"),
    ("Tier-2 Supplier Acquired by Competitor: Supply Terms Under Review",
     "No immediate disruption but exclusivity risk. Alternative qualification underway.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Factory Smart Grid Upgrade: Short-Term Disruption Expected",
     "Electrical infrastructure modernisation requires weekend shutdowns for 6 weeks.",
     "Operations", 1.05, 0.98, "neutral"),

    # R&D negative
    ("Rival Files Patent Blocking Key Cold-Weather Battery Technology",
     "Competitor secures broad patent on thermal management system. R&D must pivot or license.",
     "R&D", 1.45, 0.80, "negative"),
    ("Transport Canada Mandates New Winter Safety Standards for EVs",
     "Regulators require additional cold-weather testing. R&D must redesign heating systems.",
     "R&D", 1.35, 0.85, "negative"),
    ("Software Vulnerability Discovered in ADAS Module",
     "Critical security flaw requires emergency R&D response. Resources diverted from roadmap.",
     "R&D", 1.30, 0.90, "negative"),
    ("Key Chief Engineer Departs for US Tech Giant",
     "Lead powertrain architect lured to Silicon Valley. Brain drain to US a persistent risk.",
     "R&D", 1.35, 0.85, "negative"),
    ("Battery Thermal Runaway Incident During -30°C Testing in Yellowknife",
     "Prototype pack fails extreme cold abuse test. Full investigation required.",
     "R&D", 1.40, 0.80, "negative"),
    ("Transport Canada Type Approval Delayed Over Documentation Gaps",
     "Regulatory reviewer requests additional evidence. Launch timeline at risk.",
     "R&D", 1.25, 0.85, "negative"),
    ("Open-Source Licence Violation Found in Infotainment Stack",
     "Legal review requires code audit and partial rewrite of connected services platform.",
     "R&D", 1.20, 0.90, "negative"),
    ("Range Testing Discrepancy: NRCan Ratings Overstated",
     "Internal audit reveals optimistic cold-weather assumptions. Re-certification needed.",
     "R&D", 1.30, 0.85, "negative"),
    ("Supplier Discontinues Key Sensor Component",
     "Lidar module end-of-life forces redesign. 4-month re-qualification cycle begins.",
     "R&D", 1.35, 0.80, "negative"),
    ("University of Waterloo Research Partner Loses Federal Funding",
     "Joint battery chemistry programme suspended. R&D must absorb costs internally.",
     "R&D", 1.25, 0.85, "negative"),
    # R&D positive
    ("Breakthrough in Solid-State Battery Technology at Quebec Lab",
     "Internal team achieves energy density milestone. Patent filing underway.",
     "R&D", 0.85, 1.25, "positive"),
    ("New Motor Design Achieves 97% Efficiency: Cold-Climate Optimised",
     "Proprietary reluctance motor delivers class-leading efficiency even at -25°C.",
     "R&D", 0.80, 1.20, "positive"),
    ("ADAS System Passes Transport Canada Level 3 Validation First Attempt",
     "Autonomous driving stack clears Canadian regulatory hurdle ahead of schedule.",
     "R&D", 0.75, 1.25, "positive"),
    ("R&D Team Wins NRCan Innovation Award: C$18M Grant Attached",
     "Natural Resources Canada recognises cold-weather battery innovation.",
     "R&D", 0.80, 1.20, "positive"),
    ("New AI Simulation Platform Cuts Vehicle Testing Time by 50%",
     "Digital twin technology allows thousands of virtual winter and durability tests.",
     "R&D", 0.85, 1.15, "positive"),
    ("Patent Portfolio Reaches 400 Canadian Filings: Strongest in Segment",
     "IP moat discourages fast-follower competitors and enables licensing revenue.",
     "R&D", 0.85, 1.20, "positive"),
    ("Strategic Hire: Former Bombardier Engineer Joins as VP Engineering",
     "High-profile appointment brings deep aerospace thermal management expertise.",
     "R&D", 0.80, 1.20, "positive"),
    ("Next-Gen Platform Passes All Safety Milestones 3 Months Early",
     "Accelerated timeline frees engineering resources for cold-climate derivatives.",
     "R&D", 0.80, 1.25, "positive"),
    ("Collaborative R&D Agreement with McGill University Signed",
     "Three-year partnership grants access to materials science research and talent.",
     "R&D", 0.85, 1.15, "positive"),
    ("Over-the-Air Update Architecture Praised by Canadian Cybersecurity Centre",
     "Federal security body rates OTA system as best-in-class. Faster feature releases unlocked.",
     "R&D", 0.85, 1.15, "positive"),
    # R&D neutral
    ("New CSA Functional Safety Standard Published for Canadian EVs",
     "Updated standard requires additional documentation but aligns with existing processes.",
     "R&D", 1.08, 0.97, "neutral"),
    ("Industry Consortium Proposes Shared Canadian EV Platform Standard",
     "Could reduce R&D costs but limit differentiation. Internal debate on participation.",
     "R&D", 1.05, 0.98, "neutral"),
    ("Chief Technology Officer Announces Planned Retirement",
     "Orderly succession underway. New CTO brings fresh perspective but some continuity risk.",
     "R&D", 1.08, 0.96, "neutral"),
    ("Academic Paper Questions LFP Chemistry Viability in Canadian Winters",
     "Peer-reviewed study creates media attention. Internal assessment shows limited relevance.",
     "R&D", 1.05, 0.98, "neutral"),
    ("R&D Budget Audit Recommends Reallocation Between Programmes",
     "Internal review suggests shifting resources from mature to emerging technology streams.",
     "R&D", 1.05, 0.98, "neutral"),

    # Sales negative
    ("Competitor Launches Aggressive 0% Financing Across Canada",
     "Major rival undercuts market with zero-interest financing. Price objections surge.",
     "Sales", 1.40, 0.80, "negative"),
    ("Canadian Consumer Confidence Drops to 18-Month Low",
     "Economic uncertainty and housing crisis cause buyers to delay vehicle purchases.",
     "Sales", 1.30, 0.85, "negative"),
    ("Key Ontario Dealership Partner Files for Bankruptcy",
     "Regional dealer network collapse creates sales gaps in GTA and Hamilton.",
     "Sales", 1.25, 0.80, "negative"),
    ("Bank of Canada Rate Hike Makes Auto Loans 15% More Expensive",
     "Tightening pushes monthly payments beyond threshold for Canadian middle-income families.",
     "Sales", 1.35, 0.85, "negative"),
    ("Major Fleet Customer Cancels 1,800-Unit Provincial Government Order",
     "Budget cuts at key provincial account lead to fleet purchase freeze.",
     "Sales", 1.30, 0.80, "negative"),
    ("Negative Viral Review by Influential Canadian Auto YouTuber",
     "Video highlighting winter performance concerns gets 4M views. Leads drop 22%.",
     "Sales", 1.25, 0.85, "negative"),
    ("Competitor Launches Direct Price Match Guarantee Across Canada",
     "Rival promises to beat any competitor quote by C$750. Pricing leverage lost.",
     "Sales", 1.30, 0.85, "negative"),
    ("Regional Sales Manager Exodus: 5 of 10 Provinces Uncovered",
     "Compensation dispute triggers departures. Coverage gaps across Western and Atlantic Canada.",
     "Sales", 1.35, 0.80, "negative"),
    ("Provincial EV Rebate Suspended in BC Pending Budget Review",
     "Key provincial incentive freeze creates buyer hesitation in major market.",
     "Sales", 1.30, 0.85, "negative"),
    ("Competitor Slashes EV Prices by C$8,000 Across Canadian Lineup",
     "Aggressive repricing forces defensive response or margin erosion.",
     "Sales", 1.35, 0.80, "negative"),
    # Sales positive
    ("Federal Government Triples iZEV Budget: Rebates Guaranteed Through 2028",
     "Multi-year incentive certainty removes buyer hesitation. Order pipeline surges.",
     "Sales", 0.80, 1.25, "positive"),
    ("{{company}} Showroom Opens on Yonge Street: Flagship Toronto Location",
     "Premium downtown presence drives walk-in traffic and brand awareness in Canada's largest city.",
     "Sales", 0.85, 1.20, "positive"),
    ("New Online Configurator Increases Average Order Value by 14%",
     "Redesigned bilingual digital experience drives higher trim and option attach rates.",
     "Sales", 0.85, 1.15, "positive"),
    ("Employer EV Benefit Programme Launches: 80 Canadian Companies Enrolled",
     "Pre-tax employee benefit creates captive buyer channel with minimal acquisition cost.",
     "Sales", 0.80, 1.20, "positive"),
    ("Referral Programme Generates 35% of Q2 Canadian Orders",
     "Owner advocacy reaches critical mass across GTA and Metro Vancouver.",
     "Sales", 0.85, 1.20, "positive"),
    ("Provincial Scrappage Scheme: C$6,000 ICE Trade-In Bonus in Ontario",
     "Trade-in programme targets budget segment. Showroom traffic spikes.",
     "Sales", 0.80, 1.20, "positive"),
    ("Fleet Partnership with Enterprise and Discount Car Rental Canada",
     "Preferred vehicle status on major leasing platforms drives fleet volume.",
     "Sales", 0.80, 1.25, "positive"),
    ("Record Monthly Order Intake: Canadian Waitlist Extends to 5 Months",
     "Demand exceeds supply. Pricing power improves and discounting drops to zero.",
     "Sales", 0.85, 1.20, "positive"),
    ("{{company}} Named Best Value EV by Le Guide de l'Auto",
     "Quebec's most influential automotive publication endorsement drives French Canadian sales.",
     "Sales", 0.85, 1.15, "positive"),
    ("Municipal Fleet Electrification Wave: 15 Canadian Cities Place Orders",
     "Coast-to-coast municipal procurement drives volume without direct sales cost.",
     "Sales", 0.80, 1.25, "positive"),
    # Sales neutral
    ("New Vehicle Registration Tax Structure Takes Effect in Ontario",
     "EV advantage preserved but calculation changes. Buyer behaviour impact unclear.",
     "Sales", 1.05, 0.98, "neutral"),
    ("Industry Report Shows Flat EV Consideration Scores in Canada",
     "Market awareness high but conversion not accelerating. Status quo persists.",
     "Sales", 1.05, 0.97, "neutral"),
    ("Western Canada Dealer Contract Terms Up for Renegotiation",
     "Opportunity to improve margins but risk of coverage disruption.",
     "Sales", 1.08, 0.96, "neutral"),
    ("Competitor Pivots to Subscription Model in Toronto Pilot",
     "Novel ownership model creates uncertainty. Buyers may delay decisions.",
     "Sales", 1.05, 0.98, "neutral"),
    ("Online Sales Channel Audit Reveals UX Friction in French Version",
     "Drop-off analysis identifies improvement areas. Fix in progress.",
     "Sales", 1.05, 0.97, "neutral"),

    # Marketing negative
    ("Viral Social Media Backlash Over Winter Quality Complaint",
     "Customer's viral video of a frozen door handle gets millions of views. Sentiment drops.",
     "Marketing", 1.45, 0.75, "negative"),
    ("Competitor's Hockey Night in Canada Ad Dominates Mindshare",
     "Rival's high-budget HNIC campaign captures Canadian attention. Awareness gap widens.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Influencer Partnership Scandal Damages Brand Trust",
     "Key Canadian brand ambassador involved in controversy. Messaging pivot required.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Greenwashing Accusation by Canadian Environmental Group Goes Viral",
     "David Suzuki Foundation challenges supply chain claims. Brand trust drops.",
     "Marketing", 1.40, 0.80, "negative"),
    ("Meta Algorithm Change Doubles Canadian Cost Per Lead",
     "Platform overhauls targeting. Customer acquisition cost spikes 90% overnight.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Brand Safety Incident: Ad Appears Next to Controversial Canadian Content",
     "Programmatic placement puts brand in damaging context. Emergency media pull required.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Léger Marketing Downgrades {{company}} Brand Health Score",
     "Annual brand tracker shows declining unaided recall across English and French Canada.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Sponsorship Deal with Canadian Film Festival Collapses",
     "High-profile partnership cancelled. Paid media must replace earned exposure at 5x cost.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Competitor Launches Aggressive Comparison Campaign in Canada",
     "Head-to-head advertising directly targets {{company}}. Defensive response required.",
     "Marketing", 1.35, 0.80, "negative"),
    ("Data Breach at Marketing Agency Exposes Canadian Customer Records",
     "Breach triggers PIPEDA notification requirements and accelerated privacy investment.",
     "Marketing", 1.30, 0.80, "negative"),
    # Marketing positive
    ("Brand Wins 'Most Trusted Canadian EV' Consumer Award",
     "Industry award boosts credibility. Marketing campaigns gain natural amplification.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Viral Delivery Video at Niagara Falls Generates 18M Organic Views",
     "Customer delivery experience video breaks platform records. Zero-cost brand surge.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Hockey Night in Canada Sponsorship Secured at Below-Market Rate",
     "Late cancellation creates rare opportunity. Projected reach across all Canadian markets.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Brand Ambassador Signs 3-Year Deal with Canadian Olympic Athlete",
     "Partnership creates instant credibility with active lifestyle and family demographics.",
     "Marketing", 0.80, 1.20, "positive"),
    ("CBC Documentary on Company Sustainability Mission Airs Nationally",
     "Organic editorial coverage in premium format. Brand search volume triples.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Social Media Campaign Wins Marketing Awards Canada Gold",
     "Creative excellence recognition generates industry press coverage.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Owner Community Passes 60,000 Canadian Members",
     "Self-sustaining bilingual fan community creates authentic content at scale.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Brand Partnerships with MEC, Roots, and Canada Goose Announced",
     "Co-branding with iconic Canadian lifestyle brands elevates positioning.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Customer NPS Reaches 76: Highest in Canadian EV Segment",
     "Net promoter score drives word-of-mouth growth 3x above industry average.",
     "Marketing", 0.80, 1.20, "positive"),
    ("First-Party Data Platform Launch Cuts Canadian Targeting Cost by 38%",
     "In-house data infrastructure reduces reliance on third-party cookies.",
     "Marketing", 0.85, 1.15, "positive"),
    # Marketing neutral
    ("New Canadian Digital Privacy Regulation Restricts Ad Targeting",
     "Privacy law changes limit behavioural targeting. First-party data partially compensates.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Annual Brand Tracker Shows Flat Awareness Across Canada",
     "Awareness stable but not growing. Current mix sustaining but not expanding reach.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Marketing Agency Contract Up for Competitive Review",
     "Mandatory rebid creates transition risk but opportunity to improve creative.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("TikTok Canada Algorithm Overhaul Changes Content Distribution",
     "Organic reach formula changes. Content strategy needs adjustment.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Competitor Exits Key Canadian Sponsorship: Opportunity Emerges",
     "Premium NHL sponsorship available at short notice. High cost but significant visibility.",
     "Marketing", 1.05, 0.97, "neutral"),
]


GENERAL_NEWS_POOL = [
    # 40 POSITIVE
    ("Federal Government Expands iZEV Rebate: Pinnacle EV Models Qualify",
     "Enhanced Incentives for Zero-Emission Vehicles programme widens the buyer pool across Canada.",
     (1.06, 1.14), (1_800_000, 5_400_000), "positive"),
    ("Canada Infrastructure Bank Funds Trans-Canada Charging Corridor",
     "8,000 new fast-chargers planned along major Canadian highways and northern routes.",
     (1.04, 1.10), (1_400_000, 3_600_000), "positive"),
    ("Lithium Prices Fall as Canadian Mining Output Stabilises",
     "Domestic lithium from Quebec and Ontario stabilises battery costs for Canadian manufacturers.",
     (1.03, 1.08), (1_800_000, 4_500_000), "positive"),
    ("Record EV Sales Quarter in Canada: Market Exceeds All Forecasts",
     "Pent-up demand and falling battery costs drive industry-wide volume surge.",
     (1.05, 1.12), (1_800_000, 5_000_000), "positive"),
    ("EV Insurance Costs Fall 15% as Canadian Actuarial Data Matures",
     "Lower premiums reduce total cost of ownership for Canadian EV buyers.",
     (1.03, 1.08), (900_000, 2_700_000), "positive"),
    ("BC and Ontario Grid Upgrades Unlock Suburban and Rural EV Adoption",
     "Provincial infrastructure investment expands the addressable Canadian market.",
     (1.04, 1.09), (1_100_000, 3_200_000), "positive"),
    ("Quebec Mandates 100% ZEV Sales by 2035: Demand Certainty",
     "Provincial legislation provides long-term demand visibility in Canada's second-largest market.",
     (1.05, 1.12), (1_800_000, 4_500_000), "positive"),
    ("Employer EV Benefit Schemes Expand Across Canada",
     "Tax-efficient programmes drive commercial pipeline growth in Ontario and BC.",
     (1.04, 1.10), (1_400_000, 3_600_000), "positive"),
    ("Federal Fleet Mandate: Pinnacle EV On Approved Vendor List",
     "Ottawa requires 100% ZEV federal fleet by 2027; approved vendors gain first-mover volume.",
     (1.06, 1.14), (2_300_000, 5_400_000), "positive"),
    ("Carbon Credit Revenue Exceeds Forecast: Windfall for Canadian EVs",
     "Strong credit demand from legacy OEMs generates unexpected non-operating income.",
     (1.02, 1.06), (2_700_000, 6_300_000), "positive"),
    ("Major Canadian Ride-Share Platform Selects Pinnacle EV as Preferred Supplier",
     "Preferred status delivers volume across Toronto, Vancouver, and Montreal markets.",
     (1.05, 1.12), (2_300_000, 5_400_000), "positive"),
    ("Canada-South Korea Trade Deal Exempts EV Battery Components from Tariffs",
     "Exemption reduces bill-of-materials cost for Canadian assemblers by an estimated 7%.",
     (1.03, 1.08), (1_400_000, 3_600_000), "positive"),
    ("Major Legacy Automaker Exits Canadian EV Segment: Share Available",
     "Competitor strategic retreat creates white-space opportunity.",
     (1.05, 1.12), (1_800_000, 5_000_000), "positive"),
    ("CAA Names Pinnacle EV Top Pick for Canadian Drivers",
     "Reliability and winter performance scores drive record inbound leads.",
     (1.04, 1.09), (1_400_000, 3_600_000), "positive"),
    ("Bay Street Analyst Upgrades Pinnacle EV to Buy: Target Raised 30%",
     "Institutional upgrade triggers media coverage and accelerates fleet procurement.",
     (1.04, 1.10), (1_400_000, 4_100_000), "positive"),
    ("Pinnacle EV Named Canadian Manufacturer of the Year",
     "Award reinforces brand credibility across English and French Canadian markets.",
     (1.03, 1.08), (1_100_000, 3_200_000), "positive"),
    ("Pinnacle EV Wins Clean50 Sustainability Leadership Award",
     "Recognition amplifies ESG credentials and attracts Canadian institutional investors.",
     (1.03, 1.08), (900_000, 2_700_000), "positive"),
    ("Oil Prices Surge Past $130: Canadian EV Value Proposition Strengthens",
     "High fuel costs accelerate consumer switching even in oil-producing provinces.",
     (1.06, 1.14), (2_300_000, 5_400_000), "positive"),
    ("University of British Columbia Study Confirms EVs Best for Canadian Climate",
     "Peer-reviewed research neutralises anti-EV arguments specific to cold climates.",
     (1.03, 1.08), (900_000, 2_700_000), "positive"),
    ("Canadian EV Market Crosses 15% Penetration: Tipping Point Reached",
     "Adoption enters mainstream phase. Late-adopter segments begin considering EVs.",
     (1.05, 1.12), (1_800_000, 4_500_000), "positive"),
    ("Federal Tax Incentive for Home Charger Installation Extended 3 Years",
     "Removal of charging barrier accelerates suburban and rural Canadian adoption.",
     (1.03, 1.08), (1_100_000, 3_200_000), "positive"),
    ("Pinnacle EV J.D. Power Canada Satisfaction Score Hits All-Time High",
     "Highest ownership satisfaction drives repeat purchase and referral rates up.",
     (1.04, 1.09), (1_400_000, 3_600_000), "positive"),
    ("Hydro Rates Fall 6% in Ontario and Quebec: EV Running Costs Drop",
     "Lower electricity prices make EV ownership savings even more compelling.",
     (1.03, 1.07), (900_000, 2_700_000), "positive"),
    ("Pinnacle EV Production Record: 20,000 Units in Single Quarter",
     "Record delivery quarter demonstrates manufacturing maturity.",
     (1.04, 1.10), (1_400_000, 4_100_000), "positive"),
    ("Autonomous Vehicle Legislation Passes in Ontario: ADAS Approved",
     "Provincial framework for Level 3 autonomy established. Pinnacle EV qualifies.",
     (1.05, 1.12), (1_800_000, 4_500_000), "positive"),
    ("Major Canadian Insurer Offers EV-Specific Low-Rate Policy",
     "New product from Intact Financial reduces TCO and removes purchase barrier.",
     (1.03, 1.07), (900_000, 2_700_000), "positive"),
    ("Federal Government Announces C$2.5B Trans-Canada Charging Project",
     "Coast-to-coast fast charging eliminates range anxiety for cross-country trips.",
     (1.04, 1.10), (1_400_000, 3_600_000), "positive"),
    ("Competitor Recall Diverts 50,000 Canadian Buyers: Switching Opportunity",
     "High-profile rival recall creates conversion window. Conquest marketing activated.",
     (1.06, 1.14), (2_300_000, 5_900_000), "positive"),
    ("G7 Climate Summit in Canada Strengthens EV Commitments",
     "International policy alignment provides long-term demand certainty.",
     (1.04, 1.09), (1_400_000, 3_600_000), "positive"),
    ("Pinnacle EV App Store Launch Unlocks Ecosystem Revenue",
     "In-vehicle app marketplace opens recurring software income stream.",
     (1.03, 1.08), (1_400_000, 3_600_000), "positive"),
    ("Vehicle-to-Grid Revenue Model Approved by Ontario Energy Board",
     "V2G capability makes Pinnacle EV vehicles a home energy asset.",
     (1.04, 1.09), (1_400_000, 3_600_000), "positive"),
    ("New Battery Warranty Standard: Pinnacle EV Already Compliant",
     "Proposed 10-year Canadian standard positions Pinnacle EV as safe choice.",
     (1.03, 1.07), (900_000, 2_700_000), "positive"),
    ("Canadian Tech Giants Invest in EV Infrastructure: Ecosystem Grows",
     "Shopify, BlackBerry QNX, and others invest in connected EV ecosystem.",
     (1.04, 1.10), (1_400_000, 4_100_000), "positive"),
    ("Used EV Resale Values Surge 28% in Canada: Purchase Confidence Rises",
     "Strong residual values reduce effective cost and improve financing terms.",
     (1.04, 1.10), (1_400_000, 3_600_000), "positive"),
    ("Pinnacle EV OTA Update Delivers 15% Winter Range Improvement",
     "Software update addressing cold-weather efficiency generates viral coverage.",
     (1.04, 1.09), (1_100_000, 3_400_000), "positive"),
    ("National EV Awareness Week Drives Record Dealership Traffic",
     "NRCan-sponsored campaign generates industry-wide foot traffic boost across Canada.",
     (1.03, 1.07), (900_000, 2_700_000), "positive"),
    ("Alberta Surprises with C$5,000 Provincial EV Rebate Launch",
     "Previously holdout province opens significant new market in Western Canada.",
     (1.05, 1.12), (1_800_000, 4_500_000), "positive"),
    ("Pinnacle EV Named Best Canadian EV by Globe and Mail Drive",
     "Major newspaper endorsement drives consideration across English Canada.",
     (1.04, 1.09), (1_300_000, 3_400_000), "positive"),
    ("Canadian Pension Funds Increase EV Allocation: Pinnacle EV Included",
     "CPP and CDPQ investment signals institutional confidence in the sector.",
     (1.03, 1.08), (1_100_000, 3_200_000), "positive"),
    ("Federal Budget Allocates C$3B to Domestic EV Manufacturing",
     "Landmark programme anchors EV supply chain in Canada for the next decade.",
     (1.05, 1.12), (1_800_000, 4_500_000), "positive"),

    # 40 NEGATIVE
    ("Federal iZEV Rebate Suspended Pending Budget Review",
     "Incentive freeze creates buyer hesitation nationwide. Orders pause.",
     (0.86, 0.93), (-5_900_000, -2_500_000), "negative"),
    ("Polar Vortex Strands EV Drivers: National Media Coverage",
     "Extreme cold event generates wall-to-wall negative coverage of EV reliability.",
     (0.84, 0.92), (-6_800_000, -2_900_000), "negative"),
    ("CN Rail Strike Disrupts Automotive Supply Chain Across Canada",
     "National rail stoppage halts parts delivery and vehicle distribution for weeks.",
     (0.85, 0.93), (-6_300_000, -2_700_000), "negative"),
    ("Bank of Canada Unexpected Rate Hike: Auto Financing Costs Surge",
     "Tightening cycle pushes monthly payments beyond threshold for middle-income buyers.",
     (0.85, 0.93), (-6_300_000, -2_700_000), "negative"),
    ("Ontario Hydro Rate Surge Erodes EV Running Cost Advantage",
     "Electricity price spike narrows gap between EV and ICE operating costs.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("US-Canada Trade Tensions Raise EV Component Costs 12%",
     "New tariffs on cross-border automotive parts increase manufacturing costs.",
     (0.86, 0.93), (-5_900_000, -2_500_000), "negative"),
    ("Pinnacle EV Recalls 18,000 Units Over Heating System Defect",
     "Cabin heater malfunction in sub-zero conditions triggers Transport Canada recall.",
     (0.84, 0.92), (-6_800_000, -2_900_000), "negative"),
    ("Semiconductor Shortage Returns: Canadian Production Cut 18%",
     "Global chip constraints force output reduction at Ontario facility.",
     (0.85, 0.93), (-6_300_000, -2_700_000), "negative"),
    ("Competitor Patent Victory Restricts Key Feature in Canada",
     "Court ruling blocks popular ADAS feature. Workaround in development.",
     (0.88, 0.95), (-3_600_000, -1_400_000), "negative"),
    ("Housing Affordability Crisis Diverts Consumer Spending from EVs",
     "Mortgage stress and rising rents reduce discretionary vehicle spending.",
     (0.85, 0.93), (-6_300_000, -2_500_000), "negative"),
    ("Wildfire Season Disrupts BC Manufacturing and Logistics",
     "Air quality emergencies force plant slowdowns and delivery delays.",
     (0.86, 0.93), (-5_900_000, -2_500_000), "negative"),
    ("Negative CBC Marketplace Investigation on EV Winter Range Claims",
     "National consumer affairs programme challenges advertised range figures.",
     (0.86, 0.93), (-5_400_000, -2_200_000), "negative"),
    ("Port of Vancouver Labour Dispute Blocks Component Imports",
     "ILWU work action at Canada's busiest port disrupts Pacific supply chain.",
     (0.85, 0.93), (-5_900_000, -2_500_000), "negative"),
    ("Carbon Tax Legal Challenge Creates Policy Uncertainty",
     "Provincial court ruling questions federal carbon pricing framework.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Viral Video of EV Battery Fire in Toronto Gets 35M Views",
     "Isolated thermal event generates disproportionate national media coverage.",
     (0.84, 0.92), (-6_800_000, -2_900_000), "negative"),
    ("Canadian Dollar Weakness Raises Import Costs for Key Components",
     "Unfavourable FX movement increases bill-of-materials for imported modules.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Pinnacle EV Faces Class-Action Over Cold-Weather Range Claims",
     "Canadian plaintiffs allege advertised range materially overstates winter performance.",
     (0.85, 0.93), (-6_300_000, -2_700_000), "negative"),
    ("EV Market Price War Erupts in Canada: Margins Compressed",
     "Multiple competitors cut prices simultaneously. Race to the bottom.",
     (0.85, 0.93), (-5_900_000, -2_500_000), "negative"),
    ("Ice Storm Knocks Out Charging Infrastructure Across Southern Ontario",
     "Multi-day outage leaves EV owners stranded. Negative media cycle erupts.",
     (0.85, 0.93), (-6_300_000, -2_700_000), "negative"),
    ("Alberta Premier Threatens Anti-EV Legislation",
     "Political opposition in oil-producing province creates regulatory uncertainty.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Pinnacle EV Battery Degradation Data Leaks: Owners Concerned",
     "Internal telemetry showing above-expected cold-climate degradation sparks coverage.",
     (0.85, 0.93), (-5_900_000, -2_500_000), "negative"),
    ("Automotive Labour Shortage Drives Canadian Wage Inflation 14%",
     "Compensation increases compress operating margins for all manufacturers.",
     (0.88, 0.95), (-4_100_000, -1_600_000), "negative"),
    ("Negative Documentary on EV Mining Practices Airs on CBC",
     "Exposé on mining conditions creates consumer guilt and purchase hesitation.",
     (0.87, 0.94), (-4_100_000, -1_600_000), "negative"),
    ("Key Battery Patent Invalidated by Canadian Federal Court",
     "Court defeat removes competitive moat and increases commoditisation risk.",
     (0.88, 0.94), (-4_100_000, -1_600_000), "negative"),
    ("Competition Bureau Investigation into EV Pricing Practices",
     "Regulatory scrutiny creates uncertainty. No wrongdoing alleged but coverage damaging.",
     (0.88, 0.95), (-3_600_000, -1_400_000), "negative"),
    ("Unifor Dispute Over Shift Patterns: Ontario Production Slowdown",
     "Industrial relations breakdown causes 30% output reduction for six weeks.",
     (0.86, 0.93), (-5_000_000, -2_000_000), "negative"),
    ("Benchmark Canadian EV Test Ranks Pinnacle EV Last on Charging Speed",
     "Poor DC charging performance widely reported in Canadian automotive media.",
     (0.87, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Customer Financing Default Rates Rise Across Canada",
     "Macro pressure on household budgets pushes vehicle loan defaults above assumptions.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Spring Flooding Damages Pinnacle EV Distribution Centre",
     "Seasonal flooding destroys inventory at Eastern Canada distribution hub.",
     (0.86, 0.93), (-5_400_000, -2_200_000), "negative"),
    ("Retaliatory Tariffs on Chinese EV Components Raise Canadian Costs",
     "Trade policy response increases bill-of-materials for all domestic assemblers.",
     (0.86, 0.93), (-5_400_000, -2_200_000), "negative"),
    ("Pinnacle EV French Marketing Misstep Causes Quebec Backlash",
     "Culturally insensitive ad campaign damages brand in critical market.",
     (0.87, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Central Bank Warns of Asset Bubble in Canadian EV Sector",
     "BoC stability report highlights overvaluation risk. Investor sentiment retreats.",
     (0.88, 0.95), (-3_600_000, -1_400_000), "negative"),
    ("Counterfeit Charger Causes Garage Fire in Mississauga",
     "Third-party accessory incident creates brand halo risk despite no direct fault.",
     (0.88, 0.95), (-4_100_000, -1_600_000), "negative"),
    ("Rising Steel Costs Add C$1,000 Per Vehicle to BOM",
     "Commodity inflation flow-through forces pricing review or margin acceptance.",
     (0.88, 0.95), (-4_100_000, -1_600_000), "negative"),
    ("Pinnacle EV Forced Recall Over Charging Port Seal Defect",
     "Safety issue requires recall of 22,000 vehicles across Canada.",
     (0.86, 0.93), (-5_400_000, -2_300_000), "negative"),
    ("Global Shipping Crisis Disrupts Canadian Vehicle Export Logistics",
     "Container shortage delays international deliveries by 8+ weeks.",
     (0.87, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Pinnacle EV Loses Key Canadian Battery Patent Challenge",
     "IP defeat removes competitive moat. Technology commoditisation risk rises.",
     (0.87, 0.94), (-4_100_000, -1_600_000), "negative"),
    ("Federal Investigation into EV Safety Data Reporting Practices",
     "Transport Canada scrutiny creates uncertainty. Media coverage damaging.",
     (0.88, 0.95), (-3_600_000, -1_400_000), "negative"),
    ("Autonomous Vehicle Crash Investigation in Ontario",
     "Incident involving ADAS feature creates media firestorm and potential restrictions.",
     (0.87, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Competitor Launches Aggressive Canadian Market Entry with C$30K EV",
     "New entrant undercuts entire market. Margins compressed across the sector.",
     (0.85, 0.93), (-5_900_000, -2_500_000), "negative"),

    # 20 NEUTRAL
    ("Canadian EV Market Grows 42% YoY, but Competition Intensifies",
     "Total EV sales surge, but new Asian and legacy entrants compress margins.",
     (0.96, 1.06), (-1_800_000, 2_700_000), "neutral"),
    ("Transport Canada Proposes New Safety Testing Standards for EVs",
     "Compliance costs increase but Pinnacle EV existing scores provide a head start.",
     (0.96, 1.03), (-2_700_000, 1_400_000), "neutral"),
    ("Industry Body Proposes Canadian Charging Protocol Standard",
     "Proposed standard requires minor hardware updates. Timelines uncertain.",
     (0.96, 1.04), (-1_800_000, 1_400_000), "neutral"),
    ("Canadian Battery Recycling Regulations Tighten",
     "New end-of-life obligations require process investment. Magnitude being quantified.",
     (0.96, 1.03), (-2_300_000, 1_100_000), "neutral"),
    ("Survey Shows Rising Canadian EV Awareness But Flat Purchase Intent",
     "Brand salience improves but conversion constrained by affordability.",
     (0.97, 1.04), (-1_400_000, 1_800_000), "neutral"),
    ("Grid Study Highlights Northern Ontario EV Charging Challenges",
     "Bottlenecks identified but report confirms scale of suppressed demand.",
     (0.96, 1.03), (-1_400_000, 1_400_000), "neutral"),
    ("Canadian EV TCO Comparison Published: Pinnacle EV Mid-Table",
     "TCO competitive but not leading versus best-in-class alternatives.",
     (0.97, 1.03), (-1_400_000, 1_400_000), "neutral"),
    ("Canadian Auto Talent War Intensifies: Salaries Rise 9%",
     "Retention investment necessary. Partially offset by reduced recruitment cost.",
     (0.96, 1.03), (-1_800_000, 1_100_000), "neutral"),
    ("PIPEDA Updates Affect Connected Car Data Collection",
     "Privacy law changes require consent adjustments. Some features modestly reduced.",
     (0.96, 1.03), (-1_800_000, 900_000), "neutral"),
    ("Pinnacle EV Completes Mid-Cycle Refresh: Reception Mixed",
     "Updated exterior well received; winter range improvement smaller than expected.",
     (0.96, 1.04), (-1_800_000, 1_800_000), "neutral"),
    ("Annual Investor Day: Long-Term Canadian Targets Reaffirmed",
     "Management confirms five-year roadmap. No material changes to guidance.",
     (0.97, 1.03), (-900_000, 1_400_000), "neutral"),
    ("Canadian EV Ownership Demographics Shift: Older Buyers Entering",
     "Late-adopter demographics begin purchasing. Different marketing approach may be needed.",
     (0.97, 1.04), (-900_000, 1_800_000), "neutral"),
    ("Hydrogen Fuel Cell Vehicle Launches in Canada: Limited Impact",
     "Alternative powertrain creates debate but volumes negligible versus battery EVs.",
     (0.96, 1.03), (-1_400_000, 1_400_000), "neutral"),
    ("Canadian EV Subscription Model Gains Traction",
     "New ownership pattern creates uncertainty but opens fresh channels.",
     (0.96, 1.04), (-1_400_000, 1_800_000), "neutral"),
    ("National Infrastructure Report Highlights Canadian Charging Gaps",
     "Federal acknowledgement of shortfall. Funding expected but timeline unclear.",
     (0.96, 1.03), (-1_400_000, 1_400_000), "neutral"),
    ("Ontario Autonomous Vehicle Insurance Framework Proposed",
     "New liability structure could accelerate ADAS adoption but adds compliance complexity.",
     (0.97, 1.03), (-900_000, 1_400_000), "neutral"),
    ("Used Canadian EV Market Grows 55%: Opportunity and Cannibalisation",
     "Strong used market validates ownership but may divert some new-car demand.",
     (0.96, 1.04), (-1_400_000, 1_800_000), "neutral"),
    ("Major Tech Company Enters Canadian EV Market",
     "New entrant brings deep pockets and software expertise. Impact unclear near-term.",
     (0.95, 1.04), (-1_800_000, 1_800_000), "neutral"),
    ("Pinnacle EV Annual Sustainability Report Published",
     "Third-party audit confirms ESG progress. No material surprises.",
     (0.97, 1.03), (-900_000, 1_400_000), "neutral"),
    ("Federal Budget Review of EV Incentive Programmes Begins",
     "Routine review creates short-term uncertainty. Outcome expected positive.",
     (0.96, 1.04), (-1_400_000, 1_400_000), "neutral"),
]
