"""News event pools for the CA / PHARMA scenario.

  COMPETITOR_NEWS_POOL: (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
  DEPT_NEWS_POOL:       (headline, detail, dept_name, k_mult, smax_mult, sentiment)
  GENERAL_NEWS_POOL:    (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
"""

COMPETITOR_NEWS_POOL = [
    # 40 POSITIVE
    ('Health Canada Grants {{company}} Expanded Pediatric Indication', 'New age-group approval widens addressable patient population across Canadian provinces.', (1.10, 1.20), (1_400_000, 3_800_000), 'positive'),
    ('{{company}} Smart Pen Wins Canadian Health Innovation Award', 'Recognition from the Canadian Medical Association drives physician interest.', (1.06, 1.14), (700_000, 2_100_000), 'positive'),
    ('Pan-Canadian Pharmaceutical Alliance Adds {{company}} to National Formulary', 'pCPA listing unlocks reimbursement across all provinces simultaneously.', (1.12, 1.22), (1_900_000, 4_800_000), 'positive'),
    ('{{company}} Real-World Study at University of Toronto Shows Superior Outcomes', 'Published HbA1c improvement data from Canadian patient population strengthens positioning.', (1.08, 1.18), (1_000_000, 2_900_000), 'positive'),
    ('Ontario Drug Benefit Program Lists {{company}} as Preferred', 'Canada\'s largest provincial formulary grants preferred status — 14M residents covered.', (1.10, 1.20), (1_600_000, 4_200_000), 'positive'),
    ('{{company}} Partners with LifeLabs for Integrated Glucose Monitoring', 'CGM data integration with Canada\'s largest lab network creates closed-loop ecosystem.', (1.08, 1.16), (1_100_000, 3_000_000), 'positive'),
    ('Federal Budget Expands Pharmacare Coverage for Diabetes Devices', 'National pharmacare framework includes connected insulin delivery reimbursement.', (1.08, 1.16), (1_400_000, 3_600_000), 'positive'),
    ('{{company}} Secures Exclusive Partnership with Shoppers Drug Mart', 'Preferred pharmacy status at 1,400+ Shoppers locations drives patient access.', (1.09, 1.17), (1_300_000, 3_400_000), 'positive'),
    ('Canadian Diabetes Association Annual Conference Features {{company}} Data', 'CDA presentation generates physician buzz across Canadian endocrinology community.', (1.06, 1.13), (700_000, 2_100_000), 'positive'),
    ('{{company}} App Reaches 50K Canadian Downloads — Engagement Strong', 'Connected pen ecosystem shows patient stickiness in Canadian healthcare context.', (1.07, 1.15), (1_000_000, 2_700_000), 'positive'),
    ('Canadian Hospital Group Purchasing Org Awards {{company}} Preferred Status', 'HealthPRO contract covers 600+ hospitals and long-term care facilities.', (1.10, 1.19), (1_600_000, 4_200_000), 'positive'),
    ('{{company}} Canadian Patent Portfolio Strengthened — 12 New Filings', 'IP protection discourages generic smart pen competitors in Canadian market.', (1.06, 1.12), (600_000, 1_900_000), 'positive'),
    ('Competitor Recalls Insulin Pen in Canada — Patients Switch to {{company}}', 'Health Canada mandatory recall creates 60-day switching window.', (1.11, 1.20), (1_800_000, 4_600_000), 'positive'),
    ('{{company}} Listed on NIHB Formulary for Indigenous Communities', 'Non-Insured Health Benefits listing provides access to 900K Indigenous patients.', (1.07, 1.15), (1_000_000, 2_700_000), 'positive'),
    ('Health Canada Priority Review Granted for Next-Gen NovaPen', 'Accelerated regulatory review cuts timeline by 6 months.', (1.08, 1.16), (1_100_000, 3_000_000), 'positive'),
    ('{{company}} Named Top Canadian Health Startup by BetaKit', 'Media recognition drives investor confidence and talent pipeline.', (1.05, 1.12), (500_000, 1_800_000), 'positive'),
    ('Major Employer Group Benefits Plan Selects {{company}} for 80K Employees', 'Sun Life group plan adoption creates high-volume private insurance channel.', (1.09, 1.17), (1_400_000, 3_600_000), 'positive'),
    ('{{company}} Head-to-Head Trial at McGill Beats Market Leader on HbA1c', 'Canadian clinical superiority data transforms physician perception.', (1.10, 1.19), (1_600_000, 4_200_000), 'positive'),
    ('Diabetes Canada Endorses Connected Insulin Delivery in Guidelines', 'Professional society recommendation creates tailwind for smart pen category.', (1.06, 1.14), (800_000, 2_400_000), 'positive'),
    ('{{company}} Montreal Facility Achieves Health Canada GMP Excellence Rating', 'Flawless production record builds payer and physician confidence.', (1.05, 1.12), (500_000, 1_800_000), 'positive'),
    ('Rexall Pharmacy Expands {{company}} Placement Nationwide', 'Increased pharmacy visibility across Rexall\'s 400+ Canadian locations.', (1.07, 1.14), (900_000, 2_500_000), 'positive'),
    ('{{company}} Data Cited in Updated Canadian Diabetes Treatment Algorithm', 'Incorporation into Canadian guidelines drives protocol-based prescribing.', (1.08, 1.16), (1_100_000, 3_000_000), 'positive'),
    ('Canadian Armed Forces Health Services Adopts {{company}}', 'Military health contract provides steady volume and high visibility.', (1.09, 1.17), (1_300_000, 3_400_000), 'positive'),
    ('{{company}} Raises C$50M Series C — Bay Street Analysts Upgrade', 'Capital raise signals confidence. Two Canadian analysts upgrade to Buy.', (1.06, 1.13), (800_000, 2_400_000), 'positive'),
    ('JDRF Canada Endorses {{company}} Smart Pen Platform', 'Type 1 diabetes advocacy group partnership drives community awareness.', (1.05, 1.12), (500_000, 1_800_000), 'positive'),
    ('{{company}} OTA Update Adds French Language Interface', 'Bilingual app support drives adoption in Quebec — Canada\'s second-largest market.', (1.06, 1.13), (700_000, 2_100_000), 'positive'),
    ('Competitor Supply Shortage Creates 90-Day Gap in Canadian Market', 'Manufacturing disruption at rival forces pharmacy chains to seek alternatives.', (1.10, 1.19), (1_600_000, 4_200_000), 'positive'),
    ('{{company}} Wins J.D. Power Canada Patient Satisfaction Award', 'Highest-rated insulin delivery device in Canadian patient survey.', (1.05, 1.12), (500_000, 1_800_000), 'positive'),
    ('Alberta Blue Cross Adds {{company}} to Preferred Drug List', 'Provincial private insurer listing opens Alberta market access.', (1.08, 1.16), (1_100_000, 3_000_000), 'positive'),
    ('{{company}} Cold Chain Innovation Tested Successfully in Northern Canada', 'Arctic temperature stability enables distribution to remote northern communities.', (1.07, 1.15), (1_000_000, 2_700_000), 'positive'),
    ('Digital Health Billing Code Approved by Canadian Medical Association', 'Physicians can now bill provincial plans for reviewing connected pen data.', (1.08, 1.16), (1_100_000, 3_000_000), 'positive'),
    ('{{company}} Selected for Diabetes Canada Research Partnership', 'National research collaboration drives clinical credibility.', (1.06, 1.13), (700_000, 2_100_000), 'positive'),
    ('Record Quarter — {{company}} Enrolls 2,500 New Canadian Patients in Q3', 'Accelerating patient acquisition across all provinces.', (1.08, 1.16), (1_100_000, 3_000_000), 'positive'),
    ('{{company}} Smart Pen Reduces ER Visits by 30% in Ontario Health Study', 'Real-world cost savings data strengthens the economic case for provincial payers.', (1.09, 1.17), (1_300_000, 3_600_000), 'positive'),
    ('BC PharmaCare Removes Prior Authorization for {{company}}', 'Streamlined access in British Columbia accelerates patient starts.', (1.07, 1.14), (900_000, 2_500_000), 'positive'),
    ('{{company}} Pen Awarded Canadian IP Protection in Federal Court', 'Patent ruling prevents copycat devices in Canadian market.', (1.05, 1.11), (500_000, 1_600_000), 'positive'),
    ('Telehealth Ontario Integration Enables Remote {{company}} Prescribing', 'Virtual care compatibility expands prescriber reach across province.', (1.06, 1.13), (700_000, 2_100_000), 'positive'),
    ('{{company}} Named to Globe and Mail\'s Top Growing Companies', 'National newspaper recognition drives brand awareness.', (1.04, 1.10), (400_000, 1_400_000), 'positive'),
    ('Manulife Offers Premium Discount for {{company}} Smart Pen Users', 'Outcome-based insurance incentive drives patient enrollment.', (1.08, 1.16), (1_100_000, 3_000_000), 'positive'),
    ('{{company}} Launches Zero-Cost Patient Program for Uninsured Canadians', 'Patient assistance removes financial barrier for Canada\'s uninsured diabetics.', (1.07, 1.14), (900_000, 2_500_000), 'positive'),

    # 40 NEGATIVE
    ('Health Canada Issues Notice of Non-Compliance for Label Expansion', 'Regulatory setback requires additional Canadian-specific clinical data.', (0.84, 0.92), (-4_200_000, -1_900_000), 'negative'),
    ('pCPA Rejects {{company}} Pricing Proposal — Renegotiation Required', 'Pan-Canadian alliance demands 30% price reduction for formulary listing.', (0.82, 0.91), (-4_800_000, -2_200_000), 'negative'),
    ('{{company}} Faces Patent Challenge from Generic Manufacturer in Federal Court', 'Patheon-linked challenge could invalidate key smart pen patents in Canada.', (0.85, 0.93), (-3_600_000, -1_400_000), 'negative'),
    ('Health Canada GMP Warning at Montreal Production Facility', 'Manufacturing deficiency requires remediation. Production reduced during fix.', (0.83, 0.92), (-4_100_000, -1_800_000), 'negative'),
    ('Parliamentary Committee Targets Insulin Pricing — {{company}} Under Scrutiny', 'House of Commons hearings create negative media coverage.', (0.86, 0.93), (-3_000_000, -1_200_000), 'negative'),
    ('Competitor Launches Biosimilar Smart Pen at 35% Lower Price in Canada', 'New entrant undercuts with aggressive pricing. Market share at risk.', (0.83, 0.91), (-4_400_000, -1_900_000), 'negative'),
    ('{{company}} App Data Breach Exposes 15K Canadian Patient Records', 'PIPEDA violation triggers Privacy Commissioner investigation.', (0.84, 0.92), (-4_000_000, -1_600_000), 'negative'),
    ('Cold Chain Failure During Cross-Country Shipment — C$3M Inventory Lost', 'Temperature excursion during Trans-Canada transport renders batch unusable.', (0.85, 0.93), (-3_400_000, -1_300_000), 'negative'),
    ('Key Canadian Endocrinologist Publicly Questions {{company}} Data', 'University of Toronto physician challenges methodology on social media.', (0.86, 0.94), (-2_800_000, -1_100_000), 'negative'),
    ('PMPRB Rules {{company}} Price Excessive — Mandatory Reduction Ordered', 'Patented Medicine Prices Review Board forces price cut.', (0.84, 0.92), (-4_000_000, -1_800_000), 'negative'),
    ('{{company}} VP of Commercial Departs for US Competitor', 'Senior sales leader takes knowledge and key account relationships to American rival.', (0.87, 0.94), (-2_500_000, -1_000_000), 'negative'),
    ('Shoppers Drug Mart Threatens Delisting Over Supply Issues', 'Pharmacy chain warns of removal from preferred list.', (0.85, 0.93), (-3_400_000, -1_300_000), 'negative'),
    ('Health Canada Adverse Event Report Triggers Investigation', 'Safety signal requires voluntary investigation and media management.', (0.83, 0.92), (-4_100_000, -1_800_000), 'negative'),
    ('Ontario Hospital Network Switches to Competitor After Contract Dispute', 'Major health system defects over pricing dispute.', (0.84, 0.92), (-4_000_000, -1_600_000), 'negative'),
    ('API Supplier Raises Prices 25% — Production Costs Spike', 'Active ingredient cost increase squeezes gross margins.', (0.86, 0.93), (-3_000_000, -1_200_000), 'negative'),
    ('{{company}} Canadian Clinical Trial Fails Primary Endpoint', 'Real-world study at Canadian sites shows no significant advantage.', (0.83, 0.91), (-4_400_000, -1_900_000), 'negative'),
    ('Provincial Drug Plan Tightens Prior Authorization for Smart Pens', 'Quebec RAMQ adds step therapy requirements.', (0.85, 0.93), (-3_600_000, -1_400_000), 'negative'),
    ('Competition Bureau Investigates {{company}} Rebate Practices', 'Federal competition authority scrutiny creates uncertainty.', (0.86, 0.94), (-2_800_000, -1_100_000), 'negative'),
    ('Counterfeit {{company}} Cartridges Found in Canadian Distribution', 'Fake insulin cartridges endanger patients and damage trust.', (0.83, 0.91), (-4_400_000, -1_900_000), 'negative'),
    ('{{company}} Forced to Recall 40K Pen Devices Across Canada', 'Mechanical defect requires device replacement nationally.', (0.82, 0.91), (-4_800_000, -2_200_000), 'negative'),
    ('Provincial Drug Budget Cuts Reduce Insulin Reimbursement Rates', 'Ontario and BC budget constraints compress payer margins.', (0.85, 0.93), (-3_400_000, -1_300_000), 'negative'),
    ('Competitor Publishes Superior Head-to-Head Results in CMAJ', 'Canadian Medical Association Journal study shifts physician preference.', (0.84, 0.92), (-4_000_000, -1_600_000), 'negative'),
    ('{{company}} Loses Key Canadian Patent in Federal Court', 'Patent invalidation opens market to generic competitors.', (0.84, 0.92), (-4_000_000, -1_800_000), 'negative'),
    ('Cybersecurity Flaw Found in Smart Pen Bluetooth Protocol', 'Security vulnerability requires emergency firmware update.', (0.86, 0.93), (-3_000_000, -1_200_000), 'negative'),
    ('Competitor Launches DTC Campaign in Canadian Market', 'While prescription DTC is banned, competitor finds creative channels.', (0.85, 0.93), (-3_400_000, -1_300_000), 'negative'),
    ('{{company}} Montreal Warehouse Fire Destroys Safety Stock', 'Distribution center incident creates Eastern Canada supply gap.', (0.83, 0.91), (-4_400_000, -1_900_000), 'negative'),
    ('CBC Marketplace Investigation Questions Smart Pen Value', 'National consumer affairs programme challenges connected pen pricing.', (0.85, 0.93), (-3_400_000, -1_400_000), 'negative'),
    ('Quebec Attorney General Probes {{company}} Pricing Practices', 'Provincial legal action creates precedent risk.', (0.86, 0.93), (-3_000_000, -1_200_000), 'negative'),
    ('Key Clinical Advisory Board Member Resigns Over Conflict', 'Public departure damages scientific credibility in Canadian market.', (0.87, 0.94), (-2_400_000, -1_000_000), 'negative'),
    ('{{company}} Faces Class-Action in Ontario Over Pen Malfunction', 'Lawsuit alleges dosing errors caused adverse events.', (0.84, 0.92), (-4_000_000, -1_800_000), 'negative'),
    ('Manitoba and Saskatchewan Drop {{company}} from Provincial Formulary', 'Prairie province formulary decisions cut access.', (0.85, 0.93), (-3_600_000, -1_400_000), 'negative'),
    ('Ice Storm Disrupts {{company}} Distribution Across Eastern Canada', 'Power outage damages cold-chain integrity.', (0.85, 0.93), (-3_400_000, -1_300_000), 'negative'),
    ('Competitor Offers Free Pen Upgrade to {{company}} Canadian Patients', 'Aggressive switching campaign targets existing patient base.', (0.84, 0.92), (-4_000_000, -1_600_000), 'negative'),
    ('{{company}} CFO Resignation Triggers TSX Downgrade', 'Executive departure signals internal issues.', (0.86, 0.94), (-2_800_000, -1_100_000), 'negative'),
    ('Insulin Pen Needle Shortage Affects Canadian Market', 'Global needle supply constraint limits patient starts.', (0.86, 0.93), (-3_000_000, -1_200_000), 'negative'),
    ('{{company}} Loses McKesson Canada Distribution Exclusivity', 'Wholesaler ends exclusivity. Competitors gain equal access.', (0.85, 0.93), (-3_400_000, -1_300_000), 'negative'),
    ('Negative CMAJ Editorial Questions Smart Pen Cost-Effectiveness', 'Medical journal piece dampens physician enthusiasm.', (0.86, 0.94), (-2_800_000, -1_100_000), 'negative'),
    ('Generic Insulin Cartridge Approved by Health Canada', 'Interchangeable biosimilar cartridge erodes pricing power.', (0.83, 0.91), (-4_400_000, -1_900_000), 'negative'),
    ('{{company}} Cloud Platform Outage Affects Canadian Users for 36 Hours', 'Service disruption prevents patients from syncing data.', (0.86, 0.93), (-3_000_000, -1_200_000), 'negative'),
    ('Unexpected Injection Site Reactions Reported in Canadian Patients', 'Post-market adverse events reported at higher rate than trials.', (0.85, 0.93), (-3_600_000, -1_400_000), 'negative'),

    # 20 NEUTRAL
    ('Canadian Insulin Market Grows 10% — Competition Intensifies', 'Market expansion offset by biosimilar proliferation.', (0.96, 1.06), (-1_000_000, 1_400_000), 'neutral'),
    ('{{company}} Undertakes Canadian Operations Restructuring', 'Leadership changes bring focus but introduce transition risk.', (0.94, 1.03), (-1_400_000, 1_000_000), 'neutral'),
    ('Health Canada Proposes Updated Connected Device Guidance', 'New framework may benefit or constrain smart pen features.', (0.96, 1.04), (-1_200_000, 1_000_000), 'neutral'),
    ('Canadian Digital Health Standards Body Debates Interoperability', 'Standardization could reduce costs but limit differentiation.', (0.96, 1.03), (-1_000_000, 800_000), 'neutral'),
    ('{{company}} Annual Investor Day — Canadian Guidance Maintained', 'No material changes. TSX analyst consensus unchanged.', (0.97, 1.03), (-500_000, 700_000), 'neutral'),
    ('Provincial Drug Plan Annual Reviews Begin Across Canada', 'Routine review creates both opportunity and attrition risk.', (0.96, 1.04), (-1_000_000, 1_000_000), 'neutral'),
    ('Canadian Pharmacy Consolidation Continues', 'McKesson-Shoppers dynamics shift. Impact uncertain.', (0.96, 1.03), (-800_000, 600_000), 'neutral'),
    ('{{company}} Engages Health Canada in Pre-Submission Meeting', 'Regulatory engagement signals progress. Outcome uncertain.', (0.97, 1.04), (-600_000, 1_000_000), 'neutral'),
    ('Canadian Diabetes Prevalence Growing at 4% Annually', 'Steady market growth. No acceleration or deceleration.', (0.97, 1.04), (-500_000, 1_000_000), 'neutral'),
    ('{{company}} Files 6 New Canadian Patents', 'IP expansion signals direction. Commercial impact unclear.', (0.97, 1.03), (-400_000, 800_000), 'neutral'),
    ('Competitor Announces Canadian Partnership — Market Watches', 'Strategic alliance could reshape competitive dynamics.', (0.95, 1.04), (-1_200_000, 1_000_000), 'neutral'),
    ('Diabetes Canada Updates Treatment Guidelines', 'Revised recommendations neither favor nor disadvantage smart pens.', (0.96, 1.04), (-800_000, 1_000_000), 'neutral'),
    ('{{company}} Mid-Year Review Shows Mixed Provincial Performance', 'Strong Ontario uptake offset by slower Western Canada adoption.', (0.96, 1.03), (-1_000_000, 800_000), 'neutral'),
    ('Canada Health Infoway Digital Health Pilot — Results Pending', 'Smart pen data integration pilot could drive or complicate adoption.', (0.97, 1.04), (-600_000, 1_000_000), 'neutral'),
    ('Canadian Insulin Market Report — {{company}} Rated Promising', 'Analyst report positions {{company}} as growing but unproven at scale.', (0.96, 1.03), (-800_000, 600_000), 'neutral'),
    ('Federal Budget Includes Diabetes Affordability Provisions', 'Bipartisan support but implementation details unclear.', (0.96, 1.04), (-800_000, 1_000_000), 'neutral'),
    ('{{company}} Canadian Supply Chain Audit — Mixed Results', 'Some suppliers upgraded, others flagged for redundancy.', (0.96, 1.03), (-1_000_000, 600_000), 'neutral'),
    ('Smart Pen Awareness Growing in Canada — Adoption Gradual', 'Physicians aware but switching behavior is slow.', (0.97, 1.03), (-500_000, 800_000), 'neutral'),
    ('{{company}} Quarterly Results Meet Bay Street Expectations', 'Inline results. No surprises.', (0.97, 1.03), (-400_000, 500_000), 'neutral'),
    ('CDA Publishes Smart Pen Best Practices for Canadian Context', 'Guidelines document neutral toward {{company}} specifically.', (0.97, 1.03), (-500_000, 600_000), 'neutral'),
]


DEPT_NEWS_POOL = [
    ("Global Insulin API Shortage Hits Canadian Manufacturers",
     "Active ingredient supply constrained. Manufacturers without contracts face delays.",
     "Operations", 1.40, 0.80, "negative"),
    ("Health Canada Inspection Finds GMP Deficiencies at Montreal Facility",
     "Warning requires remediation within 90 days. Line partially shut down.",
     "Operations", 1.35, 0.75, "negative"),
    ("Cold Chain Failure During Winter Shipment to Northern Ontario",
     "Paradoxically, extreme cold damages insulin in transit. C$2M inventory lost.",
     "Operations", 1.30, 0.85, "negative"),
    ("Key Pen Component Supplier Declares Bankruptcy",
     "Canadian injection mechanism supplier fails. Alternative sourcing at premium.",
     "Operations", 1.35, 0.80, "negative"),
    ("Cleanroom Contamination Event Halts Montreal Production",
     "Particulate contamination detected. Full decontamination required.",
     "Operations", 1.40, 0.75, "negative"),
    ("Glass Cartridge Supplier Quality Issue — Batch Rejected",
     "Incoming QC detects defects. Entire shipment scrapped.",
     "Operations", 1.25, 0.85, "negative"),
    ("CN Rail Strike Blocks Pharmaceutical Shipments Across Canada",
     "National rail stoppage halts distribution from Montreal to Western provinces.",
     "Operations", 1.20, 0.80, "negative"),
    ("Pen Needle Supplier Price Increase of 30%",
     "Single-source dependency exploited. Margins compressed.",
     "Operations", 1.30, 0.85, "negative"),
    ("Quality Audit Reveals Calibration Drift in 8K Devices",
     "Internal QA catches issue. Rework and recalibration required.",
     "Operations", 1.25, 0.80, "negative"),
    ("Semiconductor Shortage Affects Smart Pen Electronics Supply",
     "Bluetooth chip allocation cut. Device production constrained.",
     "Operations", 1.35, 0.80, "negative"),
    # Operations positive
    ("New Automated Fill-Finish Line Doubles Cartridge Capacity",
     "State-of-the-art aseptic technology at Montreal facility operational.",
     "Operations", 0.80, 1.20, "positive"),
    ("Long-Term API Supply Contract with Canadian Source Signed",
     "Five-year domestic agreement hedges against import volatility.",
     "Operations", 0.80, 1.15, "positive"),
    ("Health Canada Grants Facility Exemplary Compliance Status",
     "Perfect inspection record unlocks expedited batch release.",
     "Operations", 0.85, 1.15, "positive"),
    ("Smart Pen Assembly Achieves Six Sigma Quality at Montreal Plant",
     "Defect rate drops dramatically. Warranty claims fall.",
     "Operations", 0.75, 1.25, "positive"),
    ("Cold Chain Innovation Enables Northern Canada Distribution",
     "Arctic-rated packaging enables year-round delivery to remote communities.",
     "Operations", 0.80, 1.20, "positive"),
    ("Second Manufacturing Site Opens in Ontario — Redundancy Achieved",
     "Markham facility eliminates single-site risk.",
     "Operations", 0.75, 1.25, "positive"),
    ("In-House Pen Needle Manufacturing Launches at Quebec Facility",
     "Vertical integration reduces cost and eliminates supplier dependency.",
     "Operations", 0.80, 1.20, "positive"),
    ("AI Predictive Maintenance Cuts Equipment Downtime by 50%",
     "Machine learning anticipates failures before they occur.",
     "Operations", 0.85, 1.15, "positive"),
    ("Strategic Safety Stock Program Fully Funded",
     "6-month buffer protects against supply chain disruptions.",
     "Operations", 0.85, 1.15, "positive"),
    ("Sustainable Packaging Redesign Reduces Cost and Improves Recyclability",
     "Environmental initiative delivers cost savings and ESG benefits.",
     "Operations", 0.85, 1.15, "positive"),
    # Operations neutral
    ("Industry Shift to Pre-Filled Cartridges — Retooling Needed",
     "Market trend requires line modification investment.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Annual Health Canada GMP Inspection Scheduled",
     "Routine inspection. No concerns but resources diverted to prep.",
     "Operations", 1.05, 0.98, "neutral"),
    ("Pen Component Supplier Acquired by Competitor",
     "No immediate disruption but supply terms under review.",
     "Operations", 1.10, 0.95, "neutral"),
    ("New Environment Canada Regulations on Pharmaceutical Waste",
     "Compliance straightforward but adds annual operating costs.",
     "Operations", 1.08, 0.97, "neutral"),
    ("Facility Smart Grid Upgrade Requires Weekend Shutdowns",
     "Electrical modernization. Minimal production impact.",
     "Operations", 1.05, 0.98, "neutral"),

    ("Rival Files Patent Blocking Key Smart Pen Feature in Canada",
     "Competitor secures Canadian patent on dose-tracking algorithm.",
     "R&D", 1.45, 0.80, "negative"),
    ("Canadian Real-World Study Fails to Show Superiority",
     "Multi-centre trial shows no significant improvement over standard pens.",
     "R&D", 1.35, 0.85, "negative"),
    ("Software Vulnerability in Firmware Requires Emergency Patch",
     "Security flaw diverts engineering from feature roadmap.",
     "R&D", 1.30, 0.90, "negative"),
    ("Chief Scientific Officer Departs for US Competitor",
     "Brain drain to higher-paying US market takes key researcher.",
     "R&D", 1.35, 0.85, "negative"),
    ("CGM Integration Partner Pulls Out of Canadian Development",
     "Glucose monitor company pivots. Smart pen ecosystem plan disrupted.",
     "R&D", 1.40, 0.80, "negative"),
    ("Health Canada Requests Additional Data for Label Expansion",
     "Regulatory feedback extends trial by 12 months.",
     "R&D", 1.25, 0.85, "negative"),
    ("Insulin Stability Issue in New Cartridge Formulation",
     "Degradation found in aging study. Reformulation required.",
     "R&D", 1.30, 0.85, "negative"),
    ("UBC Research Collaborator Retracts Published Study",
     "Data integrity questions force retraction of supportive evidence.",
     "R&D", 1.35, 0.80, "negative"),
    ("Smart Pen Bluetooth Incompatible with New iPhone OS in Canada",
     "iOS update breaks connectivity for majority of Canadian users.",
     "R&D", 1.25, 0.85, "negative"),
    ("Key R&D Engineer Recruited by Google Health Canada",
     "Top firmware engineer lured away. Knowledge gap.",
     "R&D", 1.30, 0.85, "negative"),
    # R&D positive
    ("Next-Gen Smart Pen Achieves 99.8% Dose Accuracy",
     "Class-leading precision. Health Canada filing accelerated.",
     "R&D", 0.85, 1.25, "positive"),
    ("CGM Integration Prototype Passes Canadian Validation",
     "Glucose data drives automated dose suggestions. Endocrinologists impressed.",
     "R&D", 0.80, 1.20, "positive"),
    ("Published Trial Shows 28% Reduction in Hypoglycemic Events",
     "Canadian patient safety data transforms prescribing confidence.",
     "R&D", 0.75, 1.25, "positive"),
    ("NRC Awards C$6M Research Grant for Connected Delivery",
     "National Research Council funding accelerates next-gen development.",
     "R&D", 0.80, 1.20, "positive"),
    ("AI Dose Optimization Passes Health Canada Software Validation",
     "Machine learning feature cleared for Canadian clinical use. Industry first.",
     "R&D", 0.80, 1.25, "positive"),
    ("Canadian Patent Portfolio Reaches 60 Granted Claims",
     "IP moat prevents imitation of key smart pen features.",
     "R&D", 0.85, 1.20, "positive"),
    ("Former Bombardier VP Joins as Head of Device Engineering",
     "Aerospace precision manufacturing expertise applied to medical devices.",
     "R&D", 0.80, 1.20, "positive"),
    ("Room-Temperature Insulin Achieves 30-Day Stability",
     "Eliminates cold chain for patients. Transformative for Northern Canada.",
     "R&D", 0.80, 1.25, "positive"),
    ("Partnership with University of Waterloo for Microneedle Research",
     "Academic collaboration targets painless injection technology.",
     "R&D", 0.85, 1.15, "positive"),
    ("OTA Update Adds Full French Language Support",
     "Bilingual interface expands Quebec adoption.",
     "R&D", 0.85, 1.15, "positive"),
    # R&D neutral
    ("Health Canada Issues Updated Guidance for AI Medical Devices",
     "New framework clarifies pathway but adds documentation burden.",
     "R&D", 1.08, 0.97, "neutral"),
    ("Canadian Industry Consortium Proposes Smart Pen Standards",
     "Standardization could reduce costs but limit features.",
     "R&D", 1.05, 0.98, "neutral"),
    ("CTO Announces Planned Retirement",
     "Orderly succession. Fresh perspective with transition risk.",
     "R&D", 1.08, 0.96, "neutral"),
    ("Academic Paper Questions Long-Term Pen Sensor Accuracy",
     "Study creates discussion but limited commercial impact.",
     "R&D", 1.05, 0.98, "neutral"),
    ("R&D Budget Reallocation Between Device and Software Programs",
     "Internal review shifts resources to digital health features.",
     "R&D", 1.05, 0.98, "neutral"),

    ("Competitor Launches Aggressive Rebate Campaign to Provincial Plans",
     "Major rival offers deep discounts to provincial drug plans.",
     "Sales", 1.40, 0.80, "negative"),
    ("Key Ontario Hospital Network Switches to Competitor",
     "Annual formulary review selects lower-cost alternative.",
     "Sales", 1.30, 0.85, "negative"),
    ("Regional Sales Manager Exodus — 4 Provinces Uncovered",
     "Compensation dispute triggers departures across Western Canada.",
     "Sales", 1.35, 0.80, "negative"),
    ("Provincial Prior Authorization Burden Increases for Smart Pens",
     "New step therapy rules add 3-week delay to patient access.",
     "Sales", 1.30, 0.85, "negative"),
    ("Major Employer Benefits Plan Drops {{company}} Coverage",
     "Sun Life group plan switches to competitor.",
     "Sales", 1.25, 0.80, "negative"),
    ("Canadian Endocrinologist Survey Shows Declining Smart Pen Interest",
     "Physician fatigue with digital health dampens prescribing enthusiasm.",
     "Sales", 1.25, 0.85, "negative"),
    ("Competitor Offers Free 90-Day Trial to {{company}} Patients",
     "Aggressive switching campaign in Canadian market.",
     "Sales", 1.30, 0.85, "negative"),
    ("Shoppers Drug Mart Reduces {{company}} Shelf Placement",
     "Pharmacy chain demotes to secondary position.",
     "Sales", 1.25, 0.80, "negative"),
    ("Quebec RAMQ Removes {{company}} from Preferred List",
     "Provincial formulary decision cuts access in Quebec.",
     "Sales", 1.30, 0.85, "negative"),
    ("Competitor Cost-Effectiveness Study Published in CMAJ",
     "Health economics data shifts provincial payer preference.",
     "Sales", 1.35, 0.80, "negative"),
    # Sales positive
    ("Five Provincial Drug Plans Add {{company}} Simultaneously",
     "Coordinated formulary wins across BC, Alberta, Ontario, Quebec, Nova Scotia.",
     "Sales", 0.80, 1.25, "positive"),
    ("{{company}} Canadian Sales Team Wins Industry Excellence Award",
     "Top-performing pharmaceutical sales organization recognized.",
     "Sales", 0.85, 1.15, "positive"),
    ("Major Hospital Network Contract — 50K Patient Lives",
     "Multi-year volume commitment from largest Canadian health network.",
     "Sales", 0.80, 1.25, "positive"),
    ("Patient Hub Program Drives 88% Refill Rate — Canadian Best",
     "Patient support services create exceptional retention.",
     "Sales", 0.85, 1.20, "positive"),
    ("National Pharmacy Chain Partnership Expands Coast-to-Coast",
     "Distribution through Shoppers and Rexall ensures access everywhere.",
     "Sales", 0.80, 1.20, "positive"),
    ("Canadian Forces Health Services Expands {{company}} Program",
     "Military health contract extended to all bases and deployed personnel.",
     "Sales", 0.80, 1.25, "positive"),
    ("Field Medical Team Rated Most Responsive by Canadian Physicians",
     "Physician satisfaction at all-time high.",
     "Sales", 0.85, 1.15, "positive"),
    ("Record Quarter: 3,000 New Canadian Patients Enrolled",
     "Commercial momentum accelerates beyond forecasts.",
     "Sales", 0.85, 1.20, "positive"),
    ("Ontario Drug Benefit Moves {{company}} to Preferred Tier",
     "Lowest patient copay tier drives preference.",
     "Sales", 0.80, 1.20, "positive"),
    ("Regional Health Authority Mandates {{company}} as Default Pen",
     "Vancouver Coastal Health standardizes on {{company}}.",
     "Sales", 0.80, 1.25, "positive"),
    # Sales neutral
    ("Annual Provincial Formulary Reviews Begin Across Canada",
     "Routine cycle creates opportunity and risk.",
     "Sales", 1.05, 0.98, "neutral"),
    ("PMPRB Proposes Insulin Pricing Framework Changes",
     "Impact on smart pen economics unclear.",
     "Sales", 1.05, 0.97, "neutral"),
    ("Hospital Group Contract Coming Up for Competitive Rebid",
     "Retention likely but not guaranteed.",
     "Sales", 1.08, 0.96, "neutral"),
    ("Competitor Launches Canadian Patient Loyalty Program",
     "New retention tactic creates switching uncertainty.",
     "Sales", 1.05, 0.98, "neutral"),
    ("McKesson Canada Distribution Terms Under Renegotiation",
     "Channel consolidation offers efficiency and risk.",
     "Sales", 1.05, 0.97, "neutral"),

    # Note: DTC prescription advertising is BANNED in Canada
    ("Social Media Backlash Over Insulin Pricing in Canada",
     "Patient advocacy group targets {{company}} despite fair Canadian pricing.",
     "Marketing", 1.45, 0.75, "negative"),
    ("Competitor's Medical Conference Campaign Dominates Mindshare",
     "Rival's aggressive CDA conference presence captures physician attention.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Key Opinion Leader Switches Endorsement to Competitor",
     "Prominent Canadian endocrinologist becomes advocate for rival.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Patient Community Backlash Over Connected Pen Data Collection",
     "Privacy concerns about health data collection in Canadian context.",
     "Marketing", 1.40, 0.80, "negative"),
    ("Digital Ad Restrictions Tighten for Health Products in Canada",
     "Health Canada guidance limits digital marketing tactics.",
     "Marketing", 1.35, 0.85, "negative"),
    ("CDA Conference Exhibit Receives Poor Physician Traffic",
     "Booth placement issue. Lead generation disappoints.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Brand Study Shows Declining Trust Among Canadian Physicians",
     "Annual tracker reveals erosion in physician confidence.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Patient Education Campaign Perceived as Advertising — Regulatory Inquiry",
     "Health Canada questions whether patient program crosses into promotion.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Competitor Launches Comparison Campaign Through Medical Channels",
     "Head-to-head physician education directly targets {{company}}.",
     "Marketing", 1.35, 0.80, "negative"),
    ("PIPEDA Violation in Marketing Materials Triggers Investigation",
     "Patient data inadvertently used in case study.",
     "Marketing", 1.30, 0.80, "negative"),
    # Marketing positive
    ("{{company}} Wins Best Patient Education Program — Canadian Health Awards",
     "Excellence recognition generates press and physician awareness.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Patient Ambassador Network Reaches 3,000 Active Canadian Advocates",
     "Peer-to-peer community creates authentic awareness.",
     "Marketing", 0.80, 1.25, "positive"),
    ("National Diabetes Awareness Month Campaign Drives Record Engagement",
     "Cross-platform campaign generates significant patient inquiries.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Canadian Olympic Athlete Diabetes Diagnosis Creates Awareness",
     "High-profile diagnosis creates national conversation about diabetes management.",
     "Marketing", 0.80, 1.20, "positive"),
    ("CDA Conference Booth Wins Best Exhibit — 2,000 Physician Visits",
     "Interactive demonstration creates buzz among Canadian endocrinologists.",
     "Marketing", 0.85, 1.20, "positive"),
    ("{{company}} App Wins Canadian Digital Health Innovation Award",
     "Tech recognition drives awareness beyond traditional pharma channels.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Patient NPS Reaches 74 — Highest in Canadian Insulin Category",
     "Net promoter score drives referrals and word-of-mouth.",
     "Marketing", 0.80, 1.20, "positive"),
    ("Partnership with Diabetes Canada for National Awareness Campaign",
     "Co-branded initiative reaches millions of Canadians.",
     "Marketing", 0.85, 1.15, "positive"),
    ("{{company}} Named Most Trusted Diabetes Brand by Canadian Patients",
     "Trust award generates media coverage and physician confidence.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Bilingual Marketing Platform Reduces Patient Acquisition Cost by 30%",
     "English-French optimization improves targeting across Canada.",
     "Marketing", 0.85, 1.15, "positive"),
    # Marketing neutral
    ("Health Canada Updates Guidance for Health Product Communications",
     "New rules clarify boundaries of permitted education vs promotion.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Annual Brand Tracker Shows Stable Awareness Across Canada",
     "Awareness holding but not growing. Current approach sustaining.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Medical Conference Calendar Shift Affects Event Planning",
     "CDA conference rescheduled. Marketing program timing adjusted.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Social Media Algorithm Changes Affect Health Content Reach",
     "Organic reach reduced. Strategy adjustment needed.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Competitor Exits Key Medical Education Sponsorship",
     "Conference sponsorship available. High cost, high visibility.",
     "Marketing", 1.05, 0.97, "neutral"),
]


GENERAL_NEWS_POOL = [
    # 40 POSITIVE
    ("Federal Pharmacare Framework Expands Diabetes Coverage",
     "National pharmacare includes connected insulin delivery reimbursement.",
     (1.06, 1.14), (1_000_000, 2_900_000), "positive"),
    ("Diabetes Canada Reports Prevalence Rising — Insulin Demand Grows",
     "3.8M Canadians with diabetes. New diagnoses accelerating demand.",
     (1.04, 1.10), (600_000, 1_900_000), "positive"),
    ("Provincial Drug Plans Expand Coverage for Connected Health Devices",
     "Reimbursement pathway widens across multiple provinces.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("Major Canadian Health System Mandates Connected Insulin as Standard",
     "University Health Network protocol change creates precedent.",
     (1.06, 1.14), (1_000_000, 2_900_000), "positive"),
    ("Insulin API Costs Fall as Global Production Expands",
     "New manufacturing capacity reduces input costs for all producers.",
     (1.03, 1.08), (600_000, 1_900_000), "positive"),
    ("Diabetes Canada Updates Guidelines to Recommend Connected Delivery",
     "Professional endorsement creates tailwind for smart pen category.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("Record Year for Biosimilar Adoption in Canada",
     "Biosimilar stigma fading. Market share crosses 25%.",
     (1.04, 1.10), (600_000, 1_900_000), "positive"),
    ("Federal Funding for Diabetes Technology Innovation",
     "CIHR budget increase includes diabetes management research.",
     (1.04, 1.10), (500_000, 1_600_000), "positive"),
    ("NovaBio Health Named Top Canadian Health Startup",
     "BetaKit recognition drives investor confidence.",
     (1.03, 1.08), (400_000, 1_400_000), "positive"),
    ("Employer Plans Increasingly Cover Smart Pens Without Barriers",
     "Trend toward frictionless access accelerates adoption.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("NovaBio Health J.D. Power Canada Score Reaches Category High",
     "Patient satisfaction drives referral rates.",
     (1.04, 1.09), (600_000, 1_900_000), "positive"),
    ("Telehealth Integration Expands Smart Pen Prescribing Reach",
     "Virtual care enables remote prescribing across provinces.",
     (1.04, 1.10), (600_000, 1_900_000), "positive"),
    ("NovaBio Health Production Record — 3,500 Patient Kits in Quarter",
     "Record output demonstrates supply chain maturity.",
     (1.04, 1.10), (600_000, 1_900_000), "positive"),
    ("Canadian Health Economics Study Shows Smart Pens Reduce Total Costs",
     "Data shows 20% reduction in diabetes-related ER visits.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("Provincial Insulin Affordability Programs Expand",
     "Legislative momentum improves patient access.",
     (1.04, 1.10), (600_000, 1_900_000), "positive"),
    ("Competitor Exits Canadian Insulin Market — Share Available",
     "Strategic retreat creates opportunity.",
     (1.06, 1.14), (1_000_000, 2_900_000), "positive"),
    ("Digital Health Billing Codes Approved Across Provinces",
     "Physician billing for pen data review now reimbursable.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("NovaBio Health Investor Day — Analysts Upgrade",
     "Strong pipeline drives analyst upgrades.",
     (1.04, 1.09), (500_000, 1_600_000), "positive"),
    ("Pharmacy Chains Expand Smart Pen Displays Across Canada",
     "Retail visibility improves nationwide.",
     (1.03, 1.08), (400_000, 1_400_000), "positive"),
    ("NovaBio Health OTA Update Adds Bilingual Meal Logging",
     "Feature enhancement increases daily engagement.",
     (1.04, 1.09), (500_000, 1_700_000), "positive"),
    ("Canadian Armed Forces Expands Smart Pen Program",
     "Military rollout creates steady volume.",
     (1.06, 1.14), (1_000_000, 2_900_000), "positive"),
    ("University of Toronto Publishes Favorable Real-World Evidence",
     "Major academic study validates smart pen outcomes.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("Pen Needle Innovation Reduces Injection Pain",
     "New needle technology improves patient experience.",
     (1.03, 1.08), (400_000, 1_400_000), "positive"),
    ("Patient Advocacy Groups Launch National Smart Pen Campaign",
     "Grassroots awareness drives patient demand.",
     (1.04, 1.10), (600_000, 1_900_000), "positive"),
    ("Insurance Premium Discounts for Smart Pen Users in Canada",
     "Outcome-based incentives drive enrollment.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("NovaBio Health Selected for Canadian Quality Improvement Pilot",
     "Quality initiative validates smart pen as care improvement tool.",
     (1.04, 1.09), (500_000, 1_600_000), "positive"),
    ("Canadian Medical Schools Add Smart Pen Training to Curriculum",
     "Next-generation physicians trained on connected delivery.",
     (1.03, 1.08), (300_000, 1_200_000), "positive"),
    ("NovaBio Health Patient Assistance Enrolls 10K Canadians",
     "Access program drives adoption among cost-sensitive patients.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("Smart Pen Refurbishment Program Creates Sustainability Story",
     "Device recycling generates positive media coverage.",
     (1.03, 1.07), (200_000, 1_000_000), "positive"),
    ("Canadian Diabetes Technology Conference Highlights Innovation",
     "Presentations generate buzz among Canadian diabetes community.",
     (1.04, 1.09), (500_000, 1_600_000), "positive"),
    ("NovaBio Health App Store Rating Reaches 4.7 Stars in Canada",
     "Patient app satisfaction drives organic referrals.",
     (1.03, 1.08), (300_000, 1_200_000), "positive"),
    ("Federal Budget Includes C$200M for Diabetes Programs",
     "Government spending creates downstream demand.",
     (1.04, 1.10), (600_000, 1_900_000), "positive"),
    ("New Study Shows Connected Pens Improve Medication Adherence",
     "Adherence data strengthens value proposition for payers.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("NovaBio Health Selected as Innovation Partner by Major Health Network",
     "Strategic partnership drives protocol-based adoption.",
     (1.06, 1.13), (800_000, 2_400_000), "positive"),
    ("Canadian Pharmacies Report Growing Patient Demand for Smart Pens",
     "Pull-through demand validates marketing investment.",
     (1.04, 1.09), (500_000, 1_700_000), "positive"),
    ("NovaBio Health Named to Globe and Mail Top Growing Companies",
     "Media recognition drives brand awareness.",
     (1.03, 1.08), (300_000, 1_200_000), "positive"),
    ("CGM Compatibility Expands to 3 Major Brands in Canada",
     "Broader interoperability increases smart pen value.",
     (1.05, 1.12), (800_000, 2_400_000), "positive"),
    ("NovaBio Health Advisory Board Adds 4 Canadian KOLs",
     "Elite physician panel bolsters credibility.",
     (1.03, 1.08), (300_000, 1_200_000), "positive"),
    ("National Diabetes Screening Identifies Undiagnosed Patients",
     "Expanded diagnosis drives downstream insulin demand.",
     (1.04, 1.10), (600_000, 1_900_000), "positive"),
    ("NovaBio Health Wins Canadian Sustainability Award",
     "ESG recognition builds brand goodwill.",
     (1.03, 1.07), (200_000, 1_000_000), "positive"),

    # 40 NEGATIVE
    ("Parliamentary Hearing Targets Insulin Pricing in Canada",
     "Political pressure creates pricing uncertainty.",
     (0.86, 0.93), (-2_900_000, -1_200_000), "negative"),
    ("GLP-1 Drug Popularity Reduces Insulin-Dependent Population",
     "Weight-loss drugs reduce patients progressing to insulin therapy.",
     (0.85, 0.93), (-3_400_000, -1_400_000), "negative"),
    ("Health Canada Issues Warning on Connected Device Cybersecurity",
     "Regulatory scrutiny of connected health creates compliance burden.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("Provincial Drug Plans Restructure — Smart Pens Deprioritized",
     "Cost-cutting shifts connected pens to less favorable position.",
     (0.85, 0.93), (-3_200_000, -1_300_000), "negative"),
    ("API Supplier Faces Import Ban — Canadian Supply Disrupted",
     "Key ingredient blocked. Prices spike.",
     (0.86, 0.93), (-2_900_000, -1_200_000), "negative"),
    ("NovaBio Health Recalls 30K Devices Across Canada",
     "Voluntary recall disrupts trust and momentum.",
     (0.84, 0.92), (-3_600_000, -1_600_000), "negative"),
    ("Major Private Insurer Drops Smart Pen Coverage",
     "Manulife removes connected pen category. Impact significant.",
     (0.84, 0.92), (-3_600_000, -1_600_000), "negative"),
    ("Patent Cliff — Generic Smart Pen Competitors File in Canada",
     "Key patents expiring. Generic applications submitted.",
     (0.86, 0.93), (-2_900_000, -1_200_000), "negative"),
    ("CBC Investigation on Insulin Pricing Creates Public Outrage",
     "National broadcaster segment generates political pressure.",
     (0.85, 0.93), (-3_200_000, -1_400_000), "negative"),
    ("Competitor Launches Biosimilar at 60% Discount in Canada",
     "Aggressive pricing threatens market share.",
     (0.83, 0.91), (-4_000_000, -1_800_000), "negative"),
    ("Patient Data Breach at Connected Health Platform — Industry Fallout",
     "Breach at another company dampens enthusiasm for connected devices.",
     (0.86, 0.93), (-2_800_000, -1_100_000), "negative"),
    ("Winter Storms Disrupt Pharmaceutical Distribution",
     "Severe weather creates logistics challenges for cold-chain products.",
     (0.87, 0.94), (-2_400_000, -1_000_000), "negative"),
    ("Provincial Reimbursement Rates Cut for Insulin Delivery",
     "Budget constraints compress margins in major provinces.",
     (0.85, 0.93), (-3_200_000, -1_300_000), "negative"),
    ("NovaBio Health CFO Departs Unexpectedly",
     "Executive departure triggers analyst concern.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("Insulin Pen Needle Shortage in Canada",
     "Global supply constraint limits patient starts.",
     (0.87, 0.94), (-2_400_000, -1_000_000), "negative"),
    ("Provincial Attorney Generals Investigate Insulin Pricing",
     "Multi-province investigation creates legal uncertainty.",
     (0.86, 0.93), (-2_800_000, -1_100_000), "negative"),
    ("NovaBio Health Product Liability Settlement — C$8M",
     "Dosing error lawsuit settled. Sets precedent.",
     (0.86, 0.93), (-3_000_000, -1_200_000), "negative"),
    ("Competitor Files Patent Challenge in Federal Court",
     "Review threatens key device patents.",
     (0.86, 0.94), (-2_600_000, -1_100_000), "negative"),
    ("Pharmacy Consolidation Reduces Manufacturer Leverage",
     "Fewer chains means less competitive bidding.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("NovaBio Health Faces Securities Review Over Revenue Recognition",
     "OSC inquiry creates uncertainty.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("Bank of Canada Rate Hike Increases Borrowing Costs",
     "Higher cost of capital constrains investment.",
     (0.88, 0.95), (-1_800_000, -700_000), "negative"),
    ("Canadian Insulin Market Price War Among Biosimilars",
     "Multiple competitors slash prices. Margins compressed.",
     (0.85, 0.93), (-3_400_000, -1_400_000), "negative"),
    ("Health Canada Delays Smart Pen Feature Approval",
     "Regulatory slip pushes feature launch by 6 months.",
     (0.86, 0.93), (-2_800_000, -1_100_000), "negative"),
    ("Negative CMAJ Editorial Questions Connected Pen Value",
     "Influential journal dampens physician enthusiasm.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("NovaBio Health App Outage Disrupts Canadian Patients",
     "Cloud failure prevents data syncing for 48 hours.",
     (0.87, 0.94), (-2_400_000, -1_000_000), "negative"),
    ("Counterfeit Insulin Cartridges Found in Canada",
     "Fake product creates safety concern.",
     (0.85, 0.93), (-3_200_000, -1_400_000), "negative"),
    ("Healthcare Worker Shortage Limits Diabetes Clinic Access",
     "Endocrinologist shortage constrains specialist care.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("NovaBio Health Warehouse Damaged by Spring Flooding",
     "Distribution center incident disrupts Eastern Canada supply.",
     (0.86, 0.93), (-2_800_000, -1_200_000), "negative"),
    ("Patient Advocacy Campaign Against Smart Pen Pricing",
     "Grassroots activism creates negative media cycle.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("Canadian Hospital Consolidation Reduces Formulary Decisions",
     "Fewer buying decisions means losing one account has larger impact.",
     (0.87, 0.94), (-2_400_000, -1_000_000), "negative"),
    ("Competitor Wins Exclusive Canadian Forces Contract",
     "Military locks in rival for 3 years. Volume loss.",
     (0.84, 0.92), (-3_600_000, -1_600_000), "negative"),
    ("Insulin Storage Recall After Potency Issue Discovered",
     "Temperature stability forces market withdrawal of lots.",
     (0.85, 0.93), (-3_200_000, -1_400_000), "negative"),
    ("Health Canada Tightens Post-Market Surveillance for Connected Devices",
     "Additional reporting increases compliance costs.",
     (0.88, 0.95), (-1_800_000, -700_000), "negative"),
    ("NovaBio Health Loses Key Patent in Federal Court",
     "Patent invalidation opens door to generics.",
     (0.85, 0.93), (-3_400_000, -1_400_000), "negative"),
    ("Canadian Pharmacist Association Questions Smart Pen Complexity",
     "Pharmacist concerns create prescribing friction.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("Competitor Hospital Switching Campaign in Canada",
     "Rival offers free 6-month supply to switching health systems.",
     (0.84, 0.92), (-3_600_000, -1_600_000), "negative"),
    ("Canadian Dollar Weakens — Import Costs Rise",
     "FX pressure increases cost of imported components.",
     (0.88, 0.95), (-1_600_000, -600_000), "negative"),
    ("NovaBio Health Credit Rating Downgraded by DBRS",
     "Rating agency cites competitive pressure. Costs rise.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),
    ("Diabetes Awareness Fatigue in Canadian Media",
     "Attention shifts to other health concerns. Campaigns less effective.",
     (0.88, 0.95), (-1_600_000, -600_000), "negative"),
    ("NovaBio Health Board Dispute Over Strategy Leaks to Press",
     "Internal disagreement creates investor uncertainty.",
     (0.87, 0.94), (-2_200_000, -900_000), "negative"),

    # 20 NEUTRAL
    ("Canadian Insulin Market Grows 9% — Competition Intensifies",
     "Expansion offset by biosimilar proliferation.",
     (0.96, 1.06), (-1_000_000, 1_400_000), "neutral"),
    ("Health Canada Proposes Updated Connected Device Guidance",
     "Could clarify or complicate regulatory pathway.",
     (0.96, 1.03), (-1_200_000, 800_000), "neutral"),
    ("Canadian Diabetes Conference — Mixed Reviews for Smart Pens",
     "Enthusiasm tempered by cost-effectiveness questions.",
     (0.96, 1.04), (-1_000_000, 1_000_000), "neutral"),
    ("Federal Healthcare Reform Debate — Insulin Provisions Uncertain",
     "Political uncertainty. Impact unclear.",
     (0.96, 1.03), (-1_200_000, 800_000), "neutral"),
    ("NovaBio Health Annual Report Meets Expectations",
     "No surprises. Analyst consensus unchanged.",
     (0.97, 1.03), (-500_000, 600_000), "neutral"),
    ("Canadian Study Shows Slow Connected Health Adoption by Physicians",
     "Digital health growing but behavior change gradual.",
     (0.96, 1.03), (-1_000_000, 600_000), "neutral"),
    ("Canadian Pharmacy Industry Consolidation Continues",
     "Dynamics shifting. Net impact uncertain.",
     (0.96, 1.04), (-1_000_000, 1_000_000), "neutral"),
    ("Diabetes Demographics Shifting — Younger Onset in Canada",
     "Type 2 diagnosed earlier. Target profile changes.",
     (0.97, 1.04), (-500_000, 1_000_000), "neutral"),
    ("NovaBio Health Patent Review — Mixed Assessment",
     "Some strengthened, others face challenge. Net stable.",
     (0.97, 1.03), (-600_000, 600_000), "neutral"),
    ("Canadian EHR Integration Standards Evolving",
     "Compatibility requirements changing. Adaptation needed.",
     (0.96, 1.03), (-800_000, 600_000), "neutral"),
    ("Competitor Strategic Review of Canadian Insulin Business",
     "Potential divestiture could create opportunity or focused rival.",
     (0.95, 1.05), (-1_200_000, 1_200_000), "neutral"),
    ("Canadian Diabetes Prevalence — Steady Growth",
     "Incremental market growth continues.",
     (0.97, 1.04), (-500_000, 800_000), "neutral"),
    ("Smart Pen Interoperability Standards Under Canadian Discussion",
     "Working group debates. Outcome uncertain.",
     (0.97, 1.03), (-600_000, 600_000), "neutral"),
    ("NovaBio Health Mid-Year Guidance Unchanged",
     "Management reaffirms outlook.",
     (0.97, 1.03), (-400_000, 500_000), "neutral"),
    ("Canadian Endocrinologist Supply Stable",
     "Workforce neither growing nor declining.",
     (0.97, 1.03), (-400_000, 500_000), "neutral"),
    ("Insulin Delivery Market Report — Canada Growing at 8% CAGR",
     "Market growth steady.",
     (0.97, 1.04), (-500_000, 800_000), "neutral"),
    ("Federal Budget Negotiations — Healthcare Flat",
     "No major diabetes program changes expected.",
     (0.97, 1.03), (-500_000, 500_000), "neutral"),
    ("NovaBio Health Supply Chain Audit — Adequate",
     "No critical findings. Some improvements noted.",
     (0.97, 1.03), (-600_000, 500_000), "neutral"),
    ("Smart Pen Awareness Growing But Adoption Gradual in Canada",
     "Physicians aware but switching slow.",
     (0.97, 1.03), (-500_000, 600_000), "neutral"),
    ("NovaBio Health Quarterly Results In Line",
     "No surprises. TSX trades flat.",
     (0.97, 1.03), (-400_000, 400_000), "neutral"),
]
