"""News event pools for the IN / EV scenario.

  COMPETITOR_NEWS_POOL: (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
  DEPT_NEWS_POOL:       (headline, detail, dept_name, k_mult, smax_mult, sentiment)
  GENERAL_NEWS_POOL:    (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
"""

COMPETITOR_NEWS_POOL = [
    # 40 POSITIVE
    ('Government Extends FAME III Subsidies: {{company}} Models Qualify', 'Ministry of Heavy Industries extends EV purchase subsidies under enhanced FAME scheme, widening the buyer pool.', (1.10, 1.20), (220_000_000, 580_000_000), 'positive'),
    ('{{company}} Battery Breakthrough Improves Hot-Climate Cycle Life by 30%', 'New thermal management system addresses India\'s top EV concern: battery degradation in extreme heat.', (1.08, 1.18), (150_000_000, 440_000_000), 'positive'),
    ('NHAI Funds Nationwide EV Charging Network Along Golden Quadrilateral', '8,000 fast-chargers planned along Delhi-Mumbai-Chennai-Kolkata highway network.', (1.06, 1.14), (120_000_000, 370_000_000), 'positive'),
    ('{{company}} Wins Major Fleet Contract with Ola Electric Fleet Division', '10,000-unit purchase order for ride-hailing fleet locks in two years of revenue.', (1.12, 1.22), (290_000_000, 660_000_000), 'positive'),
    ('Autocar India Names {{company}} Top EV Pick for Indian Buyers', 'Reliability and value-for-money scores drive record inbound leads across all segments.', (1.06, 1.12), (120_000_000, 290_000_000), 'positive'),
    ('Lithium Prices Fall as Indian Mining Exploration Accelerates', 'Rajasthan lithium discoveries and global supply stabilisation improve battery cost outlook.', (1.04, 1.10), (150_000_000, 440_000_000), 'positive'),
    ('{{company}} Partners with Shakti Power for Integrated Home Charging', 'Bundled home charger and solar package accelerates adoption among urban homeowners.', (1.07, 1.15), (120_000_000, 330_000_000), 'positive'),
    ('{{company}} Awarded Five-Star GNCAP Safety Rating', 'Top safety score generates extensive Indian media coverage and builds trust.', (1.06, 1.13), (130_000_000, 350_000_000), 'positive'),
    ('Record EV Sales Quarter in India: Market Grows 65% YoY', 'Rapidly falling battery costs and government incentives drive massive volume surge.', (1.08, 1.16), (180_000_000, 480_000_000), 'positive'),
    ('{{company}} Launches Industry-Leading 8-Year Battery Warranty', 'Bold warranty addresses resale value anxiety in price-sensitive Indian market.', (1.07, 1.14), (150_000_000, 390_000_000), 'positive'),
    ('Solid-State Battery JV: {{company}} Partners with IIT Madras', 'Joint development with India\'s top research institute grants early access to next-gen cells.', (1.09, 1.18), (190_000_000, 520_000_000), 'positive'),
    ('{{company}} Named EV Manufacturer of the Year at Auto Expo', 'India\'s most prestigious automotive award reinforces brand credibility.', (1.05, 1.12), (100_000_000, 270_000_000), 'positive'),
    ('Government Fleet Electrification Mandate: {{company}} On GeM Portal', 'EESL mandates 100% EV procurement for central government fleet.', (1.10, 1.19), (220_000_000, 560_000_000), 'positive'),
    ('EV Insurance Costs Fall 20% as Indian Actuarial Data Matures', 'IRDAI-approved lower premiums reduce total cost of ownership for Indian buyers.', (1.04, 1.09), (90_000_000, 250_000_000), 'positive'),
    ('{{company}} OTA Update Delivers 12% Air Conditioning Efficiency Gain', 'Software update optimising AC-range tradeoff delights owners in hot Indian summers.', (1.06, 1.12), (120_000_000, 310_000_000), 'positive'),
    ('BluSmart Selects {{company}} as Preferred EV Supplier for Ride-Hailing', 'Preferred supplier status delivers volume in Delhi-NCR, Bengaluru, and Mumbai.', (1.09, 1.17), (200_000_000, 490_000_000), 'positive'),
    ('{{company}} Pune Plant Expansion Approved: Capacity Doubles', 'Maharashtra MIDC fast-tracks permits for Chakan facility expansion.', (1.08, 1.15), (170_000_000, 410_000_000), 'positive'),
    ('Competitor Recall Diverts 80,000 Indian Buyers: {{company}} Benefits', 'High-profile rival recall creates conversion opportunity across metro cities.', (1.11, 1.20), (240_000_000, 590_000_000), 'positive'),
    ('{{company}} Tops JD Power India EV Satisfaction Study', 'Highest satisfaction score among Indian EV brands. NPS lifts materially.', (1.06, 1.12), (120_000_000, 290_000_000), 'positive'),
    ('Carbon Credit Revenue Exceeds Forecast: {{company}} Books ₹300Cr', 'Strong credit demand generates unexpected non-operating income.', (1.04, 1.09), (150_000_000, 410_000_000), 'positive'),
    ('{{company}} Signs Long-Term Lithium Offtake with KABIL', 'Government-backed mineral sourcing body secures strategic lithium supply for Indian manufacturers.', (1.06, 1.13), (130_000_000, 350_000_000), 'positive'),
    ('State Grid Upgrades in Maharashtra and Karnataka Unlock Tier-2 City EV Adoption', 'Power distribution improvements expand addressable market beyond metro cities.', (1.05, 1.11), (100_000_000, 270_000_000), 'positive'),
    ('{{company}} ADAS Feature Receives ARAI Homologation', 'First mass-market EV with approved Level 2+ ADAS on Indian highways.', (1.09, 1.18), (190_000_000, 500_000_000), 'positive'),
    ('GST Council Reduces EV GST Rate to 3%: Demand Surges', 'Tax reduction makes EVs significantly cheaper than ICE alternatives.', (1.08, 1.16), (180_000_000, 480_000_000), 'positive'),
    ('{{company}} Wins NITI Aayog Clean Mobility Award', 'Government think-tank recognition amplifies credentials with institutional buyers.', (1.05, 1.11), (90_000_000, 240_000_000), 'positive'),
    ('PLI Scheme Disbursement Confirms {{company}} as Qualified Recipient', 'Production-Linked Incentive tranche of ₹200Cr disbursed, rewarding domestic manufacturing.', (1.08, 1.16), (180_000_000, 480_000_000), 'positive'),
    ('Delhi NCR Implements Congestion Charge Exemption for EVs', 'Zero congestion charge for electric vehicles drives adoption in India\'s largest metro area.', (1.06, 1.13), (130_000_000, 350_000_000), 'positive'),
    ('Expressway Charging Network Reaches Mumbai-Pune-Bengaluru Coverage', 'Fast-charging infrastructure along key business corridors removes range anxiety.', (1.05, 1.12), (110_000_000, 310_000_000), 'positive'),
    ('{{company}} Selected for Delhi Metro Feeder Fleet Pilot', 'High-visibility public transit integration creates brand awareness and institutional channel.', (1.07, 1.15), (130_000_000, 350_000_000), 'positive'),
    ('Rupee Strengthens Against Dollar: Battery Import Costs Fall', 'Favourable FX movement reduces bill-of-materials for imported cell modules.', (1.04, 1.09), (100_000_000, 270_000_000), 'positive'),
    ('{{company}} Partners with Reliance Jio for Connected Car Platform', 'Jio connectivity partnership enables class-leading connected car features on Indian 5G.', (1.05, 1.12), (100_000_000, 290_000_000), 'positive'),
    ('DST Awards {{company}} ₹180Cr Clean Technology Grant', 'Department of Science and Technology funds heat-tolerant battery development.', (1.06, 1.13), (130_000_000, 350_000_000), 'positive'),
    ('{{company}} Achieves 4.8 Star Rating on Google Reviews India', 'Organic customer advocacy drives inbound leads across digital channels.', (1.05, 1.11), (90_000_000, 250_000_000), 'positive'),
    ('Indian Engineering Talent Pool Deepens as IITs Launch EV Programmes', 'Dedicated EV engineering courses at top institutions create skilled workforce pipeline.', (1.04, 1.09), (80_000_000, 220_000_000), 'positive'),
    ('{{company}} Named Best Indian EV by Times Auto Awards', 'National newspaper endorsement drives consideration across all Indian metros.', (1.05, 1.11), (100_000_000, 270_000_000), 'positive'),
    ('State Subsidies Stack to ₹3 Lakh Total in Gujarat and Maharashtra', 'Combined central and state incentives create strongest purchase incentive in India.', (1.08, 1.16), (180_000_000, 480_000_000), 'positive'),
    ('{{company}} Extreme Heat Testing in Rajasthan Validates 50°C Performance', 'Desert validation builds confidence for buyers across India\'s hot climate zones.', (1.06, 1.13), (120_000_000, 310_000_000), 'positive'),
    ('Indian Mutual Funds Increase EV Sector Allocation: {{company}} Included', 'Domestic institutional investment signals long-term sector confidence.', (1.04, 1.10), (80_000_000, 220_000_000), 'positive'),
    ('{{company}} Launches Vernacular-Language App in 12 Indian Languages', 'Multilingual digital platform drives 40% increase in Tier-2 city enquiries.', (1.05, 1.12), (100_000_000, 290_000_000), 'positive'),
    ('Union Budget Allocates ₹25,000Cr to Domestic EV Ecosystem', 'Landmark budget allocation anchors EV supply chain in India.', (1.07, 1.15), (150_000_000, 390_000_000), 'positive'),

    # 40 NEGATIVE
    ('FAME Subsidy Clawback: Government Demands Repayment from EV Makers', 'MoHI alleges localisation non-compliance. Subsidy repayment demands create cash flow stress.', (0.84, 0.92), (-660_000_000, -290_000_000), 'negative'),
    ('{{company}} Faces Consumer Forum Cases Over Range Claims in Summer Heat', 'Buyers allege real-world range in 45°C heat is 40% below advertised figures.', (0.83, 0.91), (-740_000_000, -330_000_000), 'negative'),
    ('Extreme Heat Wave Causes EV Battery Fires Across North India', 'Multiple thermal events during 48°C heat wave generate national media panic.', (0.82, 0.90), (-780_000_000, -370_000_000), 'negative'),
    ('Railway Strike Blocks Component Shipments Across India', 'Indian Railways labour action halts parts delivery from port cities to inland plants.', (0.84, 0.92), (-700_000_000, -310_000_000), 'negative'),
    ('Electricity Tariff Hike in Maharashtra Erodes EV Cost Advantage', 'State electricity regulator approves 18% tariff increase for domestic consumers.', (0.86, 0.93), (-480_000_000, -180_000_000), 'negative'),
    ('{{company}} Recalls 25,000 Units Over Charging System Software Defect', 'MoRTH mandatory recall over charging safety concern in monsoon conditions.', (0.82, 0.91), (-680_000_000, -280_000_000), 'negative'),
    ('US-India Trade Tensions Raise Component Import Costs 15%', 'New tariff round covers electronic control units sourced from American suppliers.', (0.85, 0.93), (-550_000_000, -240_000_000), 'negative'),
    ('{{company}} Loses Key Battery Engineer to Chinese Competitor', 'Senior thermal management architect moves to BYD India operations.', (0.87, 0.94), (-440_000_000, -160_000_000), 'negative'),
    ('Viral Campaign Targets {{company}} on Mining Ethics in Jharkhand', 'Environmental activist group challenges domestic mineral sourcing practices.', (0.85, 0.93), (-500_000_000, -200_000_000), 'negative'),
    ('Global Semiconductor Shortage: {{company}} Cuts Production by 22%', 'Chip constraints force major output reduction at Pune facility.', (0.83, 0.92), (-620_000_000, -260_000_000), 'negative'),
    ('{{company}} Credit Rating Downgraded by CRISIL', 'Rating agency cites cash burn and competition. Borrowing costs rise.', (0.87, 0.94), (-460_000_000, -180_000_000), 'negative'),
    ('GST Council Raises EV Rate from 5% to 12% in Surprise Move', 'Unexpected tax increase makes EVs less competitive versus ICE alternatives.', (0.84, 0.92), (-700_000_000, -310_000_000), 'negative'),
    ('{{company}} Denied Environmental Clearance for Tamil Nadu Plant', 'State pollution board blocks planned Chennai-area gigafactory expansion.', (0.86, 0.93), (-480_000_000, -190_000_000), 'negative'),
    ('EV Market Softness: Indian Consumer Purchase Intent Falls 18%', 'Rising interest rates and loan tightening dampen discretionary purchases.', (0.85, 0.93), (-530_000_000, -220_000_000), 'negative'),
    ('{{company}} CFO Resignation Triggers Dalal Street Short Selling', 'Opportunistic short attack on NSE listing. Share price falls sharply.', (0.86, 0.93), (-480_000_000, -190_000_000), 'negative'),
    ('Monsoon Flooding Knocks Out Charging Infrastructure in Mumbai', 'Severe flooding disables charging stations across Maharashtra.', (0.84, 0.92), (-590_000_000, -250_000_000), 'negative'),
    ('Nhava Sheva Port Congestion Delays Component Shipments by 5 Weeks', 'India\'s busiest port faces container backlog. Supply chain disrupted.', (0.85, 0.93), (-520_000_000, -210_000_000), 'negative'),
    ('{{company}} Loses Exclusive Shakti Power Charging Partnership to Rival', 'Competitor secures exclusivity at 2,000 Shakti Power charging locations.', (0.87, 0.94), (-430_000_000, -170_000_000), 'negative'),
    ('Cyclone Damage at Chennai Battery Supplier Disrupts Production', 'Bay of Bengal cyclone damages primary cell supplier. Force majeure declared.', (0.83, 0.92), (-640_000_000, -280_000_000), 'negative'),
    ('{{company}} Consumer Forum Case Settled for ₹600Cr', 'Large settlement sets precedent for future Indian EV litigation.', (0.86, 0.93), (-500_000_000, -200_000_000), 'negative'),
    ('Viral Video of {{company}} Fire in Bengaluru Gets 50M Views', 'Isolated thermal event amplified across Indian social media.', (0.81, 0.91), (-690_000_000, -310_000_000), 'negative'),
    ('India-China Border Tensions Disrupt Battery Component Imports', 'Trade restrictions on Chinese-origin components increase costs.', (0.84, 0.92), (-590_000_000, -260_000_000), 'negative'),
    ('{{company}} ADAS Fails ARAI Homologation Test', 'Regulatory failure requires feature suspension and re-engineering.', (0.85, 0.93), (-520_000_000, -210_000_000), 'negative'),
    ('Supply Chain Audit Finds Labour Violations at {{company}} Tier-2 Supplier', 'Media coverage of working conditions at supplier creates brand damage.', (0.86, 0.93), (-470_000_000, -190_000_000), 'negative'),
    ('RBI Rate Hike Makes Auto Loans 18% More Expensive', 'Monetary tightening pushes EMIs beyond threshold for middle-class families.', (0.84, 0.92), (-590_000_000, -260_000_000), 'negative'),
    ('Auto Workers Union Demands 20% Wage Increase at Pune Plant', 'Labour militancy at key facility threatens production continuity.', (0.85, 0.93), (-530_000_000, -220_000_000), 'negative'),
    ('{{company}} Faces Patent Infringement Ruling from Delhi High Court', 'Court orders royalty payments and ongoing licensing fees to competitor.', (0.86, 0.93), (-560_000_000, -240_000_000), 'negative'),
    ('Consumer Complaints of AC Failure in {{company}} Vehicles During Heatwave', 'Widespread HVAC issues in extreme heat go viral on Indian social media.', (0.85, 0.93), (-490_000_000, -200_000_000), 'negative'),
    ('State Government Reverses EV Road Tax Exemption in Karnataka', 'Policy reversal in key market removes purchase incentive.', (0.86, 0.94), (-440_000_000, -170_000_000), 'negative'),
    ('{{company}} Loses EESL Fleet Contract to Dharma Motors', 'Government procurement body selects established OEM for 5,000-vehicle fleet.', (0.85, 0.93), (-530_000_000, -220_000_000), 'negative'),
    ('Benchmark Indian EV Test Ranks {{company}} Last on Charging Speed', 'Poor DC fast-charging performance widely reported in Indian auto media.', (0.86, 0.94), (-430_000_000, -170_000_000), 'negative'),
    ('Power Grid Failure in UP and Bihar Disrupts Charging for Days', 'Infrastructure inadequacy in northern states raises viability concerns.', (0.86, 0.93), (-470_000_000, -190_000_000), 'negative'),
    ('{{company}} Investigated by CCI for Anti-Competitive Dealer Practices', 'Competition Commission probe creates negative press coverage.', (0.87, 0.94), (-410_000_000, -160_000_000), 'negative'),
    ('Monsoon Season Causes Severe Damage to EV Battery Packs', 'Waterlogging in Delhi and Mumbai damages hundreds of parked EVs.', (0.85, 0.93), (-530_000_000, -220_000_000), 'negative'),
    ('{{company}} Hindi Marketing Campaign Mistranslation Causes Social Media Storm', 'Culturally insensitive translation in regional campaign goes viral.', (0.86, 0.93), (-460_000_000, -180_000_000), 'negative'),
    ('Urban Apartment Residents Face Charging Infrastructure Barriers', 'RWA resistance to EV charger installation limits addressable market.', (0.86, 0.93), (-520_000_000, -210_000_000), 'negative'),
    ('{{company}} Battery Degradation Data Leaks: Indian Owners Alarmed', 'Telemetry showing rapid hot-climate degradation sparks widespread media coverage.', (0.84, 0.92), (-570_000_000, -240_000_000), 'negative'),
    ('Price War Erupts in Indian EV Market: Margins Collapse', 'Dharma, Longway, and ZhongLi cut prices simultaneously. Industry margins compressed.', (0.84, 0.92), (-590_000_000, -260_000_000), 'negative'),
    ('{{company}} Loses IPL Sponsorship to Competitor', 'Failure to renew cricket sponsorship reduces brand visibility during peak season.', (0.87, 0.94), (-430_000_000, -170_000_000), 'negative'),
    ('PLI Scheme Disbursement Delayed by 6 Months Pending Audit', 'Production-Linked Incentive payment delay creates cash flow uncertainty.', (0.86, 0.93), (-460_000_000, -190_000_000), 'negative'),

    # 20 NEUTRAL
    ('Indian EV Market Grows 65% YoY, but Competition Intensifies', 'Massive growth attracts global entrants. Margin compression across the board.', (0.96, 1.06), (-150_000_000, 220_000_000), 'neutral'),
    ('{{company}} Restructures Dealer Network for Tier-2 City Expansion', 'Transition creates friction but opens new geographies.', (0.93, 1.03), (-220_000_000, 150_000_000), 'neutral'),
    ('ARAI Proposes New Safety Standards for Indian EVs', 'Compliance costs increase but {{company}} existing scores help.', (0.95, 1.02), (-290_000_000, 120_000_000), 'neutral'),
    ('BIS Proposes Indian EV Charging Standard IS 17017 Update', 'Standard update requires minor hardware changes. Timelines uncertain.', (0.96, 1.04), (-180_000_000, 130_000_000), 'neutral'),
    ('{{company}} Undertakes Leadership Team Restructure', 'C-suite changes bring talent but introduce short-term execution risk.', (0.94, 1.03), (-210_000_000, 150_000_000), 'neutral'),
    ('Indian Battery Recycling Rules Tighten Under E-Waste Rules', 'New EPR obligations require investment. Magnitude being assessed.', (0.95, 1.02), (-260_000_000, 110_000_000), 'neutral'),
    ('Survey Shows Rising Indian EV Awareness But Range Anxiety Persists', 'Awareness growing but infrastructure concerns limit conversion.', (0.96, 1.04), (-120_000_000, 160_000_000), 'neutral'),
    ('{{company}} Autonomous Pilot Launches on Mumbai-Pune Expressway', 'Limited trial generates press but financial impact immaterial.', (0.97, 1.04), (-130_000_000, 160_000_000), 'neutral'),
    ('Power Grid Study Highlights EV Charging Challenges in Tier-2 Cities', 'Infrastructure gaps identified but suppressed demand confirmed.', (0.96, 1.03), (-150_000_000, 120_000_000), 'neutral'),
    ('{{company}} Completes Mid-Cycle Refresh: Reception Mixed', 'Updated design praised; range improvement smaller than expected.', (0.95, 1.04), (-180_000_000, 190_000_000), 'neutral'),
    ('IT Act Amendment Affects Connected Car Data Collection', 'Regulatory changes require consent adjustments for telematics features.', (0.95, 1.02), (-220_000_000, 90_000_000), 'neutral'),
    ('Indian EV TCO Comparison: {{company}} Mid-Table', 'Total cost of ownership competitive but not leading.', (0.96, 1.03), (-120_000_000, 120_000_000), 'neutral'),
    ('{{company}} Annual Investor Day: NSE Targets Reaffirmed', 'Management confirms roadmap. No material guidance changes.', (0.97, 1.03), (-90_000_000, 130_000_000), 'neutral'),
    ('Indian Auto Sector Talent War: Engineering Salaries Rise 15%', 'Compensation pressure but better talent availability from IIT programmes.', (0.96, 1.02), (-190_000_000, 90_000_000), 'neutral'),
    ('{{company}} Engages Third-Party ESG Audit for NSE Listing', 'Proactive audit ahead of BRSR compliance. Outcome expected positive.', (0.96, 1.03), (-130_000_000, 120_000_000), 'neutral'),
    ('{{company}} Board Changes: Strategy Unchanged', 'Board reshuffle prompts speculation but guidance reaffirmed.', (0.97, 1.03), (-70_000_000, 110_000_000), 'neutral'),
    ('Supply Chain Audit Shows Mixed Results for {{company}}', 'Some lines improved, others flagged for diversification.', (0.96, 1.04), (-120_000_000, 120_000_000), 'neutral'),
    ('{{company}} Files Indian Patent Portfolio Expansion', 'New filings signal direction. Analyst opinions split.', (0.97, 1.03), (-70_000_000, 150_000_000), 'neutral'),
    ('SIAM Conference Highlights Shifting Indian Consumer Preferences', 'Research suggests gradual demand evolution. No disruption imminent.', (0.96, 1.04), (-120_000_000, 120_000_000), 'neutral'),
    ('{{company}} Quarterly Results Meet Dalal Street Expectations', 'Inline results. NSE listing trades flat post-announcement.', (0.97, 1.03), (-70_000_000, 70_000_000), 'neutral'),
]


DEPT_NEWS_POOL = [
    ("Global Lithium Shortage Hits Indian Battery Supply Chain",
     "Lithium prices spike 40%. Indian manufacturers without locked-in contracts face delays.",
     "Operations", 1.40, 0.80, "negative"),
    ("Railway Strike Blocks Component Shipments Across India",
     "Indian Railways labour action halts parts delivery from port cities.",
     "Operations", 1.30, 0.85, "negative"),
    ("Workers Union Calls Strike at Pune Assembly Plant",
     "Labour dispute at key Chakan facility. Output could drop 25%.",
     "Operations", 1.35, 0.75, "negative"),
    ("Critical Assembly Robot Failure Halts Production Line",
     "Imported welding robot fails. Replacement on 21-day lead time.",
     "Operations", 1.35, 0.80, "negative"),
    ("Chinese Battery Cell Supplier Halts Shipments Amid Trade Tensions",
     "India-China friction disrupts primary cell supply. Emergency sourcing at 35% premium.",
     "Operations", 1.40, 0.75, "negative"),
    ("CPCB Tightens Factory Emissions Standards",
     "Central Pollution Control Board requires ₹100Cr scrubber installation.",
     "Operations", 1.25, 0.85, "negative"),
    ("Monsoon Flooding Destroys ₹70Cr in Finished Inventory",
     "Extreme flooding at Maharashtra distribution centre damages 500 vehicles.",
     "Operations", 1.20, 0.80, "negative"),
    ("Nickel Price Spike Raises Battery Pack Costs by 25%",
     "Global supply disruption increases key input costs materially.",
     "Operations", 1.30, 0.85, "negative"),
    ("Quality Audit Reveals Wiring Harness Defects in 6,000 Units",
     "Internal QA flags issue. Rework required on all affected vehicles.",
     "Operations", 1.25, 0.80, "negative"),
    ("Semiconductor Import Controls Cut Chip Allocation by 35%",
     "Government import restrictions reduce chip availability for EV makers.",
     "Operations", 1.35, 0.80, "negative"),
    # Operations positive
    ("PLI Scheme Disburses ₹200Cr to {{company}} for Domestic Production",
     "Production-Linked Incentive programme rewards manufacturing scale-up.",
     "Operations", 0.80, 1.20, "positive"),
    ("New Gigapress Installation Cuts Body Assembly Time by 40%",
     "Single-piece casting at Pune plant eliminates 70 weld points.",
     "Operations", 0.75, 1.25, "positive"),
    ("Long-Term Nickel Contract with NMDC Locks In Below-Market Pricing",
     "Five-year domestic offtake secures key input at 20% below spot.",
     "Operations", 0.80, 1.15, "positive"),
    ("Factory Achieves ISO 14001 Environmental Certification",
     "Certification unlocks green bond financing and reduces insurance.",
     "Operations", 0.85, 1.15, "positive"),
    ("Second Shift at Pune Plant Ramps Up Ahead of Schedule",
     "Night shift fully operational two months early. Capacity doubles.",
     "Operations", 0.75, 1.25, "positive"),
    ("Battery Recycling Line Opens at Gujarat Facility",
     "In-house recycling recovers 90% of cathode materials.",
     "Operations", 0.80, 1.20, "positive"),
    ("Dedicated EV Distribution Hub Opens at Nagpur: Central India",
     "Purpose-built facility cuts delivery time across Tier-2 cities by 3 days.",
     "Operations", 0.85, 1.15, "positive"),
    ("AI Quality Vision System Cuts Defect Rate by 55%",
     "AI inspection catches defects invisible to human inspectors.",
     "Operations", 0.80, 1.20, "positive"),
    ("Solar PPA Signed: Factory Runs on 100% Renewable Power",
     "Rajasthan solar PPA locks in India's cheapest industrial electricity.",
     "Operations", 0.85, 1.15, "positive"),
    ("Strategic Parts Warehouse Opens in Hyderabad for Southern India",
     "Regional hub provides next-day service across Telangana and AP.",
     "Operations", 0.85, 1.15, "positive"),
    # Operations neutral
    ("Industry Shift to LFP Chemistry: Indian Plants Retooling",
     "Lower cost but different process. Investment needed; long-term benefit unclear.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Union Contract Renewal Negotiations Begin at Pune Plant",
     "Current agreement expires in 90 days. Talks expected constructive.",
     "Operations", 1.05, 0.98, "neutral"),
    ("New Factory Inspectorate Protocols Require Additional Training",
     "Compliance reduces productive hours by 3% during transition.",
     "Operations", 1.08, 0.97, "neutral"),
    ("Tier-2 Supplier Acquired by Competitor: Terms Under Review",
     "No immediate disruption but exclusivity risk.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Factory Smart Grid Upgrade: Short-Term Disruption Expected",
     "Electrical modernisation requires weekend shutdowns for 6 weeks.",
     "Operations", 1.05, 0.98, "neutral"),

    ("Rival Files Patent Blocking Key Heat-Tolerant Battery Technology",
     "Competitor secures broad Indian patent on thermal management. Pivot or license required.",
     "R&D", 1.45, 0.80, "negative"),
    ("MoRTH Mandates New Crash Safety Standards: Chassis Redesign Needed",
     "Ministry requirements demand additional structural reinforcement for EVs.",
     "R&D", 1.35, 0.85, "negative"),
    ("Software Vulnerability Discovered in ADAS Module",
     "Critical flaw requires emergency response. Resources diverted.",
     "R&D", 1.30, 0.90, "negative"),
    ("Key Chief Engineer Departs for Chinese Rival",
     "Lead battery architect moves to BYD India R&D centre.",
     "R&D", 1.35, 0.85, "negative"),
    ("Battery Thermal Runaway During 50°C Testing in Rajasthan",
     "Prototype fails extreme heat abuse test. Full investigation required.",
     "R&D", 1.40, 0.80, "negative"),
    ("ARAI Homologation Delayed Over Documentation Gaps",
     "Regulatory body requests additional evidence. Launch timeline at risk.",
     "R&D", 1.25, 0.85, "negative"),
    ("Open-Source Licence Violation in Infotainment Stack",
     "Legal review requires code audit and partial rewrite.",
     "R&D", 1.20, 0.90, "negative"),
    ("Range Testing Discrepancy: ARAI Certification Figures Overstated",
     "Internal audit reveals optimistic hot-weather assumptions.",
     "R&D", 1.30, 0.85, "negative"),
    ("Supplier Discontinues Key Sensor Component",
     "Lidar module EOL forces redesign. 4-month qualification cycle.",
     "R&D", 1.35, 0.80, "negative"),
    ("IIT Research Partner Loses DST Funding",
     "Joint battery programme suspended. R&D must absorb costs.",
     "R&D", 1.25, 0.85, "negative"),
    # R&D positive
    ("Breakthrough in Heat-Tolerant Battery Technology at Pune Lab",
     "Internal team achieves cycle life milestone for tropical climates.",
     "R&D", 0.85, 1.25, "positive"),
    ("New Motor Design Achieves 96% Efficiency: Optimised for Indian Conditions",
     "Proprietary motor handles dust, heat, and humidity exceptionally.",
     "R&D", 0.80, 1.20, "positive"),
    ("ADAS Passes ARAI Homologation on First Attempt",
     "Autonomous stack clears Indian regulatory hurdle ahead of schedule.",
     "R&D", 0.75, 1.25, "positive"),
    ("R&D Team Wins DST Innovation Award: ₹150Cr Grant Attached",
     "Department of Science and Technology recognises thermal management innovation.",
     "R&D", 0.80, 1.20, "positive"),
    ("AI Simulation Platform Cuts Vehicle Testing Time by 50%",
     "Digital twin enables thousands of virtual hot-climate durability tests.",
     "R&D", 0.85, 1.15, "positive"),
    ("Indian Patent Portfolio Reaches 350 Filings",
     "IP moat strengthens competitive position against importers.",
     "R&D", 0.85, 1.20, "positive"),
    ("Strategic Hire: Former ISRO Scientist Joins as VP Engineering",
     "Space programme veteran brings thermal management expertise.",
     "R&D", 0.80, 1.20, "positive"),
    ("Next-Gen Platform Passes All ARAI Milestones 3 Months Early",
     "Accelerated development frees resources for derivative models.",
     "R&D", 0.80, 1.25, "positive"),
    ("Collaborative R&D Agreement with IIT Bombay Signed",
     "Three-year partnership grants access to materials science research.",
     "R&D", 0.85, 1.15, "positive"),
    ("OTA Architecture Praised by CERT-In Security Auditors",
     "Government cybersecurity body rates system best-in-class.",
     "R&D", 0.85, 1.15, "positive"),
    # R&D neutral
    ("New AIS 156 Functional Safety Standard Published",
     "Updated standard requires documentation but aligns with processes.",
     "R&D", 1.08, 0.97, "neutral"),
    ("SIAM Proposes Shared Indian EV Platform Standard",
     "Could reduce costs but limit differentiation. Debate ongoing.",
     "R&D", 1.05, 0.98, "neutral"),
    ("CTO Announces Planned Retirement",
     "Orderly succession. New CTO brings fresh perspective.",
     "R&D", 1.08, 0.96, "neutral"),
    ("Academic Paper Questions LFP Chemistry in Indian Heat",
     "Study creates media attention. Internal assessment shows limited relevance.",
     "R&D", 1.05, 0.98, "neutral"),
    ("R&D Budget Audit Recommends Programme Reallocation",
     "Review suggests shifting resources to emerging technology streams.",
     "R&D", 1.05, 0.98, "neutral"),

    ("Competitor Launches Aggressive 0% EMI Financing Across India",
     "Major rival undercuts with zero-interest EMI scheme. Price objections surge.",
     "Sales", 1.40, 0.80, "negative"),
    ("Indian Consumer Confidence Drops to 18-Month Low",
     "Inflation and rural stress cause buyers to delay purchases.",
     "Sales", 1.30, 0.85, "negative"),
    ("Key Delhi-NCR Dealership Partner Files for Bankruptcy",
     "Dealer collapse creates coverage gaps in India's largest metro market.",
     "Sales", 1.25, 0.80, "negative"),
    ("RBI Rate Hike Makes Auto Loans 18% More Expensive",
     "Tightening pushes EMIs beyond affordability for middle-class families.",
     "Sales", 1.35, 0.85, "negative"),
    ("Major Fleet Customer Cancels 2,000-Unit Government Order",
     "State government budget cuts freeze fleet procurement.",
     "Sales", 1.30, 0.80, "negative"),
    ("Negative Review by Top Indian Auto YouTuber Goes Viral",
     "Video highlighting summer range anxiety gets 8M views.",
     "Sales", 1.25, 0.85, "negative"),
    ("Competitor Launches ₹50,000 Price Match Guarantee",
     "Rival promises to beat any quote. Pricing leverage lost.",
     "Sales", 1.30, 0.85, "negative"),
    ("Regional Sales Manager Exodus: 6 of 12 Zones Uncovered",
     "Compensation dispute triggers departures across key territories.",
     "Sales", 1.35, 0.80, "negative"),
    ("State EV Subsidy Suspended in Maharashtra Pending Election",
     "Key state incentive frozen. Buyer hesitation in biggest market.",
     "Sales", 1.30, 0.85, "negative"),
    ("Competitor Slashes Prices by ₹2 Lakh Across Indian EV Range",
     "Aggressive repricing forces defensive response or margin erosion.",
     "Sales", 1.35, 0.80, "negative"),
    # Sales positive
    ("FAME III Budget Tripled: Subsidies Guaranteed Through 2029",
     "Multi-year subsidy certainty removes buyer hesitation. Pipeline surges.",
     "Sales", 0.80, 1.25, "positive"),
    ("{{company}} Opens Flagship Experience Centre on MG Road, Bengaluru",
     "Premium location drives walk-in traffic in India's tech capital.",
     "Sales", 0.85, 1.20, "positive"),
    ("New Online Configurator Increases Average Order Value by 15%",
     "Multilingual digital platform drives higher variant selection.",
     "Sales", 0.85, 1.15, "positive"),
    ("Corporate EV Benefit Programme Launches: 120 IT Companies Enrolled",
     "Pre-tax employee benefit creates captive buyer channel in Bengaluru and Hyderabad.",
     "Sales", 0.80, 1.20, "positive"),
    ("Referral Programme Generates 40% of Q2 Indian Orders",
     "Owner advocacy critical in trust-based Indian buying culture.",
     "Sales", 0.85, 1.20, "positive"),
    ("Government Scrappage Policy: ₹1.5L ICE Trade-In Bonus",
     "Vehicle scrappage incentive targets cost-conscious segment.",
     "Sales", 0.80, 1.20, "positive"),
    ("Fleet Partnership with Zoomcar and Myles Self-Drive",
     "Preferred vehicle status on major Indian car-sharing platforms.",
     "Sales", 0.80, 1.25, "positive"),
    ("Record Monthly Order Intake: Indian Waitlist Extends to 6 Months",
     "Demand exceeds supply. Pricing power improves across all variants.",
     "Sales", 0.85, 1.20, "positive"),
    ("{{company}} Named Best Value EV by Overdrive Magazine",
     "India's most-read auto magazine endorsement drives consideration.",
     "Sales", 0.85, 1.15, "positive"),
    ("State Transport Fleet Electrification: 10 States Place Orders",
     "Nationwide government procurement drives volume.",
     "Sales", 0.80, 1.25, "positive"),
    # Sales neutral
    ("New Registration Tax Structure Takes Effect Across States",
     "EV advantage varies by state. Buyer behaviour impact unclear.",
     "Sales", 1.05, 0.98, "neutral"),
    ("Industry Report Shows Flat EV Consideration in Tier-2 Cities",
     "Metro awareness high but smaller city conversion not accelerating.",
     "Sales", 1.05, 0.97, "neutral"),
    ("South India Dealer Contract Terms Up for Renegotiation",
     "Opportunity to improve margins but risk of coverage disruption.",
     "Sales", 1.08, 0.96, "neutral"),
    ("Competitor Launches Subscription Model in Bengaluru Pilot",
     "Novel ownership model creates uncertainty.",
     "Sales", 1.05, 0.98, "neutral"),
    ("Online Sales Audit Reveals UX Issues in Regional Language Versions",
     "Drop-off analysis identifies improvements needed.",
     "Sales", 1.05, 0.97, "neutral"),

    ("Viral Social Media Backlash Over AC Failure Complaint",
     "Customer's viral video of AC failure in 45°C heat gets millions of views.",
     "Marketing", 1.45, 0.75, "negative"),
    ("Competitor's IPL Sponsorship Campaign Dominates Mindshare",
     "Rival's cricket sponsorship captures national attention during IPL season.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Bollywood Brand Ambassador Controversy Damages Trust",
     "Celebrity partner involved in scandal. Messaging pivot required.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Greenwashing Accusation by Indian Environmental NGO Goes Viral",
     "Centre for Science and Environment challenges supply chain claims.",
     "Marketing", 1.40, 0.80, "negative"),
    ("Meta Algorithm Change Doubles Indian Cost Per Lead",
     "Platform changes spike customer acquisition cost overnight.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Brand Safety Incident: Ad Appears on Controversial News Channel",
     "Programmatic placement creates backlash. Emergency pull required.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Brand Health Survey Shows Declining Awareness Outside Metros",
     "Annual tracker reveals limited penetration in Tier-2 and Tier-3 cities.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Sponsorship Deal with Major Cricket Tournament Collapses",
     "High-profile partnership cancelled. Paid media must replace at 5x cost.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Competitor Launches Aggressive Comparison Campaign in India",
     "Head-to-head advertising targets {{company}}. Defensive response needed.",
     "Marketing", 1.35, 0.80, "negative"),
    ("Data Breach at Digital Agency Exposes Indian Customer Records",
     "IT Act notification required. Privacy programme investment accelerated.",
     "Marketing", 1.30, 0.80, "negative"),
    # Marketing positive
    ("Brand Wins 'Most Trusted Indian EV' Consumer Award",
     "Industry award boosts credibility across metro and Tier-2 markets.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Viral Delivery Video at India Gate Generates 25M Views",
     "Customer experience video breaks records on Indian social media.",
     "Marketing", 0.80, 1.25, "positive"),
    ("IPL Title Sponsorship Secured at Below-Market Rate",
     "Late cancellation creates rare opportunity. 500M+ viewer reach.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Brand Ambassador Deal with Leading Bollywood Star Signed",
     "Three-year partnership creates credibility across all demographics.",
     "Marketing", 0.80, 1.20, "positive"),
    ("Discovery+ Documentary on Company Mission Airs in India",
     "Organic editorial in premium OTT format. Brand search triples.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Campaign Wins Effie India Gold Award for Marketing Effectiveness",
     "Industry recognition generates press and attracts creative talent.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Indian Owner Community Passes 80,000 Members",
     "Active WhatsApp and social media communities create organic advocacy.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Brand Partnerships with Titan, Fastrack, and Urban Ladder",
     "Co-branding with aspirational Indian lifestyle brands elevates positioning.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Customer NPS Reaches 74: Highest Among Indian EV Brands",
     "Net promoter drives word-of-mouth 4x above industry average.",
     "Marketing", 0.80, 1.20, "positive"),
    ("First-Party Data Platform Cuts Indian Targeting Cost by 45%",
     "In-house data reduces reliance on third-party cookies.",
     "Marketing", 0.85, 1.15, "positive"),
    # Marketing neutral
    ("New Indian Digital Privacy Bill Restricts Ad Targeting",
     "DPDP Act limits behavioural targeting. First-party data compensates.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Annual Brand Tracker Shows Flat Awareness in South India",
     "Awareness stable but not growing in key southern markets.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Marketing Agency Contract Up for Review",
     "Mandatory rebid creates transition risk but opportunity.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Instagram India Algorithm Overhaul Changes Distribution",
     "Organic reach formula changes. Strategy adjustment needed.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Competitor Exits Key Sponsorship: Cricket Opportunity Emerges",
     "Premium cricket sponsorship available. High cost, high visibility.",
     "Marketing", 1.05, 0.97, "neutral"),
]


GENERAL_NEWS_POOL = [
    # 40 POSITIVE
    ("FAME III Subsidies Extended: Vayuha Motors Models Qualify",
     "Enhanced EV subsidy scheme widens the buyer pool across India.",
     (1.06, 1.14), (150_000_000, 440_000_000), "positive"),
    ("NHAI Funds Golden Quadrilateral EV Charging Network",
     "8,000 fast-chargers along India's key highway corridors.",
     (1.04, 1.10), (120_000_000, 290_000_000), "positive"),
    ("Lithium Prices Fall as Global and Domestic Supply Grows",
     "Rajasthan discoveries and global stabilisation improve battery costs.",
     (1.03, 1.08), (150_000_000, 370_000_000), "positive"),
    ("Record Indian EV Sales Quarter: Market Grows 65% YoY",
     "Falling costs and incentives drive massive volume surge.",
     (1.05, 1.12), (150_000_000, 410_000_000), "positive"),
    ("EV Insurance Costs Fall 20% as Indian Data Matures",
     "IRDAI-approved lower premiums reduce TCO for Indian buyers.",
     (1.03, 1.08), (70_000_000, 220_000_000), "positive"),
    ("State Grid Upgrades Unlock Tier-2 City EV Adoption",
     "Power infrastructure in Maharashtra and Karnataka expands market.",
     (1.04, 1.09), (90_000_000, 260_000_000), "positive"),
    ("GST Council Reduces EV Rate to 3%: Demand Surges",
     "Tax reduction makes EVs significantly cheaper than ICE alternatives.",
     (1.05, 1.12), (150_000_000, 370_000_000), "positive"),
    ("Corporate EV Benefit Schemes Expand Across IT Sector",
     "Pre-tax programmes drive adoption among Bengaluru and Hyderabad professionals.",
     (1.04, 1.10), (120_000_000, 290_000_000), "positive"),
    ("EESL Adds Vayuha Motors to Government Procurement List",
     "Central government fleet mandate creates first-mover volume.",
     (1.06, 1.14), (190_000_000, 440_000_000), "positive"),
    ("Carbon Credit Revenue Exceeds Forecast: Windfall for Indian EVs",
     "Strong credit demand from ICE OEMs generates unexpected income.",
     (1.02, 1.06), (220_000_000, 520_000_000), "positive"),
    ("BluSmart Selects Vayuha Motors as Preferred Supplier",
     "Ride-hailing preferred status delivers volume in metro cities.",
     (1.05, 1.12), (190_000_000, 440_000_000), "positive"),
    ("PLI Scheme Disbursement Rewards Domestic Manufacturing",
     "Production-Linked Incentive confirms Vayuha Motors as qualified recipient.",
     (1.03, 1.08), (120_000_000, 290_000_000), "positive"),
    ("Major Legacy Automaker Exits Indian EV Segment",
     "Competitor retreat creates white-space opportunity.",
     (1.05, 1.12), (150_000_000, 410_000_000), "positive"),
    ("Autocar India Names Vayuha Motors Best EV for Indian Buyers",
     "Reliability and value scores drive record leads.",
     (1.04, 1.09), (120_000_000, 290_000_000), "positive"),
    ("Dalal Street Analyst Upgrades Vayuha Motors: Target Raised 40%",
     "Institutional upgrade triggers media coverage and fleet interest.",
     (1.04, 1.10), (120_000_000, 330_000_000), "positive"),
    ("Vayuha Motors Named Indian Manufacturer of the Year at Auto Expo",
     "India's top automotive award reinforces brand credibility.",
     (1.03, 1.08), (80_000_000, 260_000_000), "positive"),
    ("Vayuha Motors Wins NITI Aayog Clean Mobility Award",
     "Government recognition amplifies credentials.",
     (1.03, 1.08), (70_000_000, 220_000_000), "positive"),
    ("Petrol Prices Cross ₹120/litre: EV Value Proposition Surges",
     "High fuel costs accelerate switching across all Indian segments.",
     (1.06, 1.14), (190_000_000, 440_000_000), "positive"),
    ("IIT Study Confirms EVs Best for Indian Climate Goals",
     "Peer-reviewed research supports government EV push.",
     (1.03, 1.08), (70_000_000, 220_000_000), "positive"),
    ("Indian EV Market Crosses 10% Penetration in Passenger Cars",
     "Adoption enters mainstream phase in metro markets.",
     (1.05, 1.12), (150_000_000, 370_000_000), "positive"),
    ("State Subsidies Stack to ₹3 Lakh in Gujarat and Maharashtra",
     "Combined incentives create strongest EV purchase case in India.",
     (1.05, 1.12), (150_000_000, 370_000_000), "positive"),
    ("Vayuha Motors JD Power India Score Hits All-Time High",
     "Ownership satisfaction drives repeat purchase intent.",
     (1.04, 1.09), (120_000_000, 290_000_000), "positive"),
    ("Electricity Tariffs Fall in Tamil Nadu: EV Costs Drop",
     "State tariff reduction widens EV running cost advantage.",
     (1.03, 1.07), (70_000_000, 220_000_000), "positive"),
    ("Vayuha Motors Production Record: 28,000 Units in Quarter",
     "Record quarter demonstrates manufacturing maturity.",
     (1.04, 1.10), (120_000_000, 330_000_000), "positive"),
    ("ARAI Approves Level 2+ ADAS: Vayuha Motors Qualifies",
     "Indian regulatory framework for highway ADAS established.",
     (1.05, 1.12), (150_000_000, 370_000_000), "positive"),
    ("Major Indian Insurer Offers EV-Specific Low-Rate Policy",
     "IRDAI-approved product reduces TCO and removes purchase barrier.",
     (1.03, 1.07), (70_000_000, 220_000_000), "positive"),
    ("NHAI Announces ₹20,000Cr National EV Charging Programme",
     "Nationwide fast-charging along all national highways.",
     (1.04, 1.10), (120_000_000, 290_000_000), "positive"),
    ("Competitor Recall Diverts 100,000 Indian Buyers: Opportunity",
     "High-profile rival recall creates conversion window.",
     (1.06, 1.14), (190_000_000, 480_000_000), "positive"),
    ("India's G20 Presidency Strengthens EV Commitments",
     "International alignment provides demand certainty.",
     (1.04, 1.09), (120_000_000, 290_000_000), "positive"),
    ("Vayuha Motors App Store Launches: Ecosystem Revenue Opens",
     "In-vehicle marketplace creates recurring software income.",
     (1.03, 1.08), (120_000_000, 290_000_000), "positive"),
    ("V2G Revenue Model Approved by State Electricity Boards",
     "Vehicle-to-grid capability adds value proposition.",
     (1.04, 1.09), (120_000_000, 290_000_000), "positive"),
    ("Battery Warranty Standard: Vayuha Motors Already Compliant",
     "Proposed 8-year Indian standard positions Vayuha Motors well.",
     (1.03, 1.07), (70_000_000, 220_000_000), "positive"),
    ("Indian Tech Giants Invest in EV Infrastructure",
     "TCS, Infosys, and Reliance invest in connected EV ecosystem.",
     (1.04, 1.10), (120_000_000, 330_000_000), "positive"),
    ("Used EV Resale Values Surge 30% in India: Confidence Rises",
     "Strong residuals validate ownership and improve financing.",
     (1.04, 1.10), (120_000_000, 290_000_000), "positive"),
    ("Vayuha Motors OTA Delivers 12% AC Efficiency Improvement",
     "Software update addressing heat-efficiency delights owners.",
     (1.04, 1.09), (90_000_000, 280_000_000), "positive"),
    ("National EV Week Drives Record Showroom Traffic Across India",
     "Government-sponsored campaign generates industry-wide boost.",
     (1.03, 1.07), (70_000_000, 220_000_000), "positive"),
    ("Delhi NCR Implements Congestion Charge Exemption for EVs",
     "Zero congestion charge drives adoption in India's capital region.",
     (1.05, 1.12), (130_000_000, 330_000_000), "positive"),
    ("Vayuha Motors Named Best EV by Times Auto Awards",
     "National newspaper endorsement drives metro consideration.",
     (1.04, 1.09), (100_000_000, 270_000_000), "positive"),
    ("Indian Mutual Funds Increase EV Allocation: Vayuha Motors In",
     "Domestic institutional investment signals sector confidence.",
     (1.03, 1.08), (80_000_000, 230_000_000), "positive"),
    ("Union Budget Allocates ₹25,000Cr to EV Ecosystem",
     "Landmark allocation anchors EV supply chain in India.",
     (1.05, 1.12), (150_000_000, 370_000_000), "positive"),

    # 40 NEGATIVE
    ("FAME Subsidy Clawback Demands Hit Indian EV Industry",
     "Government demands repayment from manufacturers. Cash flow stressed.",
     (0.86, 0.93), (-480_000_000, -200_000_000), "negative"),
    ("Extreme Heat Wave Causes Multiple EV Battery Incidents",
     "48°C temperatures trigger thermal events. National media panic.",
     (0.84, 0.92), (-560_000_000, -240_000_000), "negative"),
    ("Railway Strike Disrupts Automotive Supply Chain",
     "Labour action halts parts movement across the country.",
     (0.85, 0.93), (-520_000_000, -220_000_000), "negative"),
    ("RBI Rate Hike: Auto Loan EMIs Surge 18%",
     "Monetary tightening pushes EMIs beyond middle-class affordability.",
     (0.85, 0.93), (-520_000_000, -220_000_000), "negative"),
    ("Electricity Tariff Hikes Across Multiple States",
     "State regulators raise tariffs. EV running cost advantage narrows.",
     (0.87, 0.94), (-410_000_000, -170_000_000), "negative"),
    ("India-China Trade Tensions Disrupt Battery Imports",
     "Import restrictions on Chinese components raise manufacturing costs.",
     (0.86, 0.93), (-480_000_000, -200_000_000), "negative"),
    ("Vayuha Motors Recalls 20,000 Units Over Charging Defect",
     "MoRTH mandatory recall over monsoon-season charging safety.",
     (0.84, 0.92), (-560_000_000, -240_000_000), "negative"),
    ("Semiconductor Import Squeeze Cuts Indian EV Production",
     "Chip supply constraints force output reduction.",
     (0.85, 0.93), (-520_000_000, -220_000_000), "negative"),
    ("Competitor Patent Victory Restricts Key Feature in India",
     "Court ruling blocks popular feature. Workaround in development.",
     (0.88, 0.95), (-260_000_000, -100_000_000), "negative"),
    ("Monsoon Flooding Devastates EV Infrastructure in Mumbai",
     "Severe flooding disables charging and damages parked vehicles.",
     (0.85, 0.93), (-520_000_000, -220_000_000), "negative"),
    ("Power Grid Failures in UP and Bihar Raise EV Viability Concerns",
     "Infrastructure inadequacy limits market beyond metro cities.",
     (0.86, 0.93), (-480_000_000, -200_000_000), "negative"),
    ("GST Council Raises EV Rate to 12% in Surprise Decision",
     "Unexpected tax increase reduces EV price competitiveness.",
     (0.84, 0.92), (-560_000_000, -240_000_000), "negative"),
    ("Nhava Sheva Port Congestion Blocks Component Imports",
     "India's busiest port faces container backlog for weeks.",
     (0.85, 0.93), (-480_000_000, -200_000_000), "negative"),
    ("PLI Disbursement Delayed 6 Months: Cash Flow Impact",
     "Production incentive delay creates financial uncertainty.",
     (0.86, 0.93), (-440_000_000, -180_000_000), "negative"),
    ("Viral Video of EV Fire in Delhi Gets 60M Views",
     "Thermal event generates massive media coverage.",
     (0.84, 0.92), (-560_000_000, -240_000_000), "negative"),
    ("Rupee Weakness Raises Import Costs for Battery Modules",
     "Unfavourable FX increases BOM for imported components.",
     (0.87, 0.94), (-410_000_000, -170_000_000), "negative"),
    ("Consumer Forum Cases Pile Up Over Summer Range Claims",
     "Multiple complaints allege range overstated in hot conditions.",
     (0.85, 0.93), (-480_000_000, -200_000_000), "negative"),
    ("Indian EV Price War: Dharma, Longway, ZhongLi All Cut Prices",
     "Multiple competitors slash prices. Margins collapse.",
     (0.85, 0.93), (-480_000_000, -200_000_000), "negative"),
    ("Cyclone Damage at Supplier Disrupts Production",
     "Bay of Bengal cyclone damages cell supplier. Force majeure.",
     (0.85, 0.93), (-520_000_000, -220_000_000), "negative"),
    ("State EV Road Tax Exemptions Reversed in Karnataka",
     "Policy reversal removes incentive in key southern market.",
     (0.86, 0.93), (-440_000_000, -180_000_000), "negative"),
    ("Vayuha Motors Battery Degradation Data Leaks",
     "Hot-climate telemetry data causes widespread alarm.",
     (0.85, 0.93), (-480_000_000, -200_000_000), "negative"),
    ("Auto Worker Militancy: Pune Plant Slowdown",
     "Industrial action causes 30% output reduction for weeks.",
     (0.86, 0.93), (-370_000_000, -150_000_000), "negative"),
    ("Negative NDTV Investigation on EV Safety Standards",
     "National broadcaster exposé questions industry practices.",
     (0.87, 0.94), (-330_000_000, -130_000_000), "negative"),
    ("Key Battery Patent Invalidated by Indian Patent Office",
     "IP defeat removes competitive moat.",
     (0.88, 0.94), (-330_000_000, -130_000_000), "negative"),
    ("CCI Investigation into EV Pricing Practices",
     "Competition authority scrutiny creates uncertainty.",
     (0.88, 0.95), (-260_000_000, -100_000_000), "negative"),
    ("Vayuha Motors Charging Speed Ranks Last in Benchmark Test",
     "Poor DC charging widely reported in Indian auto media.",
     (0.87, 0.94), (-330_000_000, -130_000_000), "negative"),
    ("Auto Loan Default Rates Rise as EMIs Stretch Budgets",
     "Macro pressure pushes defaults above underwriting assumptions.",
     (0.87, 0.94), (-370_000_000, -150_000_000), "negative"),
    ("RWA Resistance Blocks Charging Installation in Major Cities",
     "Apartment complex governance limits urban EV adoption.",
     (0.86, 0.93), (-440_000_000, -180_000_000), "negative"),
    ("Tariff on Chinese EV Components Raises Costs for All Makers",
     "Government trade policy increases BOM across the sector.",
     (0.86, 0.93), (-440_000_000, -180_000_000), "negative"),
    ("Hindi Marketing Mistranslation Goes Viral",
     "Culturally insensitive ad damages brand in Hindi belt.",
     (0.87, 0.94), (-330_000_000, -130_000_000), "negative"),
    ("CRISIL Warns of Overvaluation in Indian EV Sector",
     "Rating agency report dampens investor sentiment.",
     (0.88, 0.95), (-260_000_000, -100_000_000), "negative"),
    ("Counterfeit Charger Fire in Gurgaon Raises Liability Concerns",
     "Third-party accessory incident creates brand halo risk.",
     (0.88, 0.95), (-290_000_000, -120_000_000), "negative"),
    ("Rising Steel Costs Add ₹60,000 Per Vehicle to BOM",
     "Commodity inflation forces pricing review.",
     (0.88, 0.95), (-330_000_000, -130_000_000), "negative"),
    ("Vayuha Motors Forced Recall Over Charging Port Defect",
     "Monsoon water ingress issue requires recall of 22,000 units.",
     (0.86, 0.93), (-440_000_000, -190_000_000), "negative"),
    ("Global Shipping Crisis Disrupts Indian EV Exports",
     "Container shortage delays international deliveries.",
     (0.87, 0.94), (-330_000_000, -130_000_000), "negative"),
    ("Vayuha Motors Loses Key Patent Challenge in Delhi HC",
     "IP defeat in High Court removes competitive advantage.",
     (0.87, 0.94), (-330_000_000, -130_000_000), "negative"),
    ("MoRTH Investigation into EV Safety Data Reporting",
     "Regulatory scrutiny creates uncertainty.",
     (0.88, 0.95), (-260_000_000, -100_000_000), "negative"),
    ("ADAS Incident on Mumbai Expressway Triggers Investigation",
     "Crash involving autonomous feature creates media storm.",
     (0.87, 0.94), (-370_000_000, -150_000_000), "negative"),
    ("BYD Launches ₹12 Lakh EV in India: Undercuts Entire Market",
     "Chinese entrant's aggressive pricing compresses all margins.",
     (0.85, 0.93), (-480_000_000, -200_000_000), "negative"),
    ("Vayuha Motors Loses IPL Sponsorship to Competitor",
     "Cricket sponsorship loss reduces peak-season brand visibility.",
     (0.87, 0.94), (-370_000_000, -150_000_000), "negative"),

    # 20 NEUTRAL
    ("Indian EV Market Grows 65%, but Competition Intensifies",
     "Massive growth but new entrants compress margins.",
     (0.96, 1.06), (-150_000_000, 220_000_000), "neutral"),
    ("ARAI Proposes Updated Safety Standards",
     "Compliance costs rise but Vayuha Motors existing scores help.",
     (0.96, 1.03), (-220_000_000, 100_000_000), "neutral"),
    ("BIS Proposes Updated Charging Standard",
     "Minor hardware updates required. Timelines uncertain.",
     (0.96, 1.04), (-150_000_000, 100_000_000), "neutral"),
    ("E-Waste Rules Tighten for Battery Recycling",
     "New EPR obligations require investment.",
     (0.96, 1.03), (-190_000_000, 80_000_000), "neutral"),
    ("Survey Shows Rising EV Awareness But Range Anxiety Persists",
     "Metro awareness growing but infrastructure concerns limit conversion.",
     (0.97, 1.04), (-100_000_000, 130_000_000), "neutral"),
    ("Power Grid Study Highlights Tier-2 City Charging Gaps",
     "Infrastructure shortfalls but suppressed demand confirmed.",
     (0.96, 1.03), (-120_000_000, 100_000_000), "neutral"),
    ("Indian EV TCO Comparison: Vayuha Motors Mid-Table",
     "TCO competitive but not leading versus Dharma and Longway.",
     (0.97, 1.03), (-100_000_000, 100_000_000), "neutral"),
    ("Indian Auto Talent War: Engineering Salaries Rise 15%",
     "Compensation pressure but IIT pipeline provides talent.",
     (0.96, 1.03), (-150_000_000, 80_000_000), "neutral"),
    ("DPDP Act Affects Connected Car Data Collection",
     "Privacy law changes require consent adjustments.",
     (0.96, 1.03), (-150_000_000, 70_000_000), "neutral"),
    ("Vayuha Motors Mid-Cycle Refresh: Mixed Reception",
     "Updated design praised; range improvement smaller than expected.",
     (0.96, 1.04), (-150_000_000, 150_000_000), "neutral"),
    ("Annual Investor Day: NSE Targets Reaffirmed",
     "Management confirms roadmap. No guidance changes.",
     (0.97, 1.03), (-70_000_000, 100_000_000), "neutral"),
    ("Indian EV Demographics Shift: Non-Metro Buyers Entering",
     "Smaller city demographics begin purchasing. Different approach needed.",
     (0.97, 1.04), (-70_000_000, 130_000_000), "neutral"),
    ("Hydrogen Vehicle Pilot in India: Limited EV Impact",
     "Alternative powertrain creates debate but volumes negligible.",
     (0.96, 1.03), (-100_000_000, 100_000_000), "neutral"),
    ("Indian EV Subscription Model Gains Traction in Metros",
     "New model creates uncertainty but opens channels.",
     (0.96, 1.04), (-100_000_000, 130_000_000), "neutral"),
    ("NITI Aayog Report Highlights Charging Infrastructure Gaps",
     "Government acknowledges shortfall. Funding expected.",
     (0.96, 1.03), (-100_000_000, 100_000_000), "neutral"),
    ("Indian AV Insurance Framework Proposed",
     "New liability structure adds compliance complexity.",
     (0.97, 1.03), (-70_000_000, 100_000_000), "neutral"),
    ("Used Indian EV Market Grows 80%: Opportunity and Risk",
     "Strong used market validates ownership but may cannibalise new.",
     (0.96, 1.04), (-100_000_000, 130_000_000), "neutral"),
    ("Chinese Tech Company Enters Indian EV Market",
     "New entrant brings resources. Impact unclear near-term.",
     (0.95, 1.04), (-150_000_000, 150_000_000), "neutral"),
    ("Vayuha Motors Annual BRSR Sustainability Report Published",
     "Audit confirms ESG progress. No surprises.",
     (0.97, 1.03), (-70_000_000, 100_000_000), "neutral"),
    ("SIAM Annual Review: Indian EV Outlook Balanced",
     "Industry body report neutral. No major directional signals.",
     (0.96, 1.04), (-100_000_000, 100_000_000), "neutral"),
]
