"""News event pools for the UK / EV scenario.

  COMPETITOR_NEWS_POOL: (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
  DEPT_NEWS_POOL:       (headline, detail, dept_name, k_mult, smax_mult, sentiment)
  GENERAL_NEWS_POOL:    (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
"""

COMPETITOR_NEWS_POOL = [
    # 40 POSITIVE
    ('Government Extends Plug-In Vehicle Grant: {{company}} Models Qualify', 'OZEV confirms continuation of purchase grants for sub-£40k EVs, widening the buyer pool.', (1.10, 1.20), (2_400_000, 6_400_000), 'positive'),
    ('{{company}} Battery Breakthrough Cuts Cost Per kWh by 20%', 'New cell chemistry developed at Coventry R&D centre enters pilot production.', (1.08, 1.18), (1_600_000, 4_800_000), 'positive'),
    ('National Grid Fast-Charging Corridor Project Completed Along M1 and M6', '5,000 new rapid chargers deployed across England, Scotland, and Wales motorway services.', (1.06, 1.14), (1_200_000, 4_000_000), 'positive'),
    ('{{company}} Wins Major Fleet Contract with Royal Mail', '6,000-unit order for last-mile delivery vehicles locks in two years of fleet revenue.', (1.12, 1.22), (3_200_000, 7_200_000), 'positive'),
    ('What Car? Names {{company}} Best EV for British Drivers', 'Reliability and value scores drive record inbound leads across all UK segments.', (1.06, 1.12), (1_200_000, 3_200_000), 'positive'),
    ('Raw Material Costs Fall as Global Lithium Supply Stabilises', 'Battery commodity prices drop 22% YoY, improving EV gross margins across all manufacturers.', (1.04, 1.10), (1_600_000, 4_800_000), 'positive'),
    ('{{company}} Partners with Octopus Energy on Integrated Home Charging', 'Bundled smart tariff and home charger package accelerates adoption among suburban buyers.', (1.07, 1.15), (1_200_000, 3_600_000), 'positive'),
    ('{{company}} Awarded Five-Star Euro NCAP Safety Rating', 'Top safety score generates extensive UK media coverage and drives purchase intent.', (1.06, 1.13), (1_400_000, 3_800_000), 'positive'),
    ('Record EV Sales Quarter in UK: Market Share Passes 25%', 'Pent-up demand and Benefit-in-Kind advantages drive industry-wide volume surge.', (1.08, 1.16), (1_900_000, 5_100_000), 'positive'),
    ('{{company}} Launches 10-Year Battery Warranty: Industry First in UK', 'Bold warranty eliminates residual value anxiety and drives enquiry surge.', (1.07, 1.14), (1_600_000, 4_200_000), 'positive'),
    ('Solid-State Battery JV Announced: {{company}} Secures Early Access', 'Joint venture with Imperial College London grants exclusive early-production allocation.', (1.09, 1.18), (2_000_000, 5_600_000), 'positive'),
    ('{{company}} Named EV Manufacturer of the Year at UK Car of the Year Awards', 'Prestigious award reinforces brand credibility in competitive British market.', (1.05, 1.12), (1_100_000, 3_000_000), 'positive'),
    ('Government Fleet Electrification Mandate: {{company}} On Crown Commercial List', 'Whitehall mandates 100% ZEV government fleet by 2027; listed suppliers gain volume.', (1.10, 1.19), (2_400_000, 6_000_000), 'positive'),
    ('EV Insurance Costs Fall 16% as UK Actuarial Data Matures', 'Lower premiums reduce total cost of ownership, widening the addressable market.', (1.04, 1.09), (1_000_000, 2_700_000), 'positive'),
    ('{{company}} OTA Update Delivers 10% Range Improvement Overnight', 'Software update delights existing UK owners and generates viral media coverage.', (1.06, 1.12), (1_200_000, 3_400_000), 'positive'),
    ('Uber UK Selects {{company}} as Preferred EV Supplier', 'Preferred status delivers guaranteed volume in London, Manchester, and Birmingham.', (1.09, 1.17), (2_200_000, 5_300_000), 'positive'),
    ('{{company}} Coventry Plant Expansion Approved: Capacity Doubles', 'Planning permission granted for £180M facility expansion in West Midlands.', (1.08, 1.15), (1_800_000, 4_500_000), 'positive'),
    ('Competitor Recall Diverts 50,000 UK Buyers: {{company}} Captures Demand', 'High-profile rival recall creates conversion opportunity across the UK.', (1.11, 1.20), (2_600_000, 6_400_000), 'positive'),
    ('{{company}} Tops Auto Trader UK EV Ownership Satisfaction Survey', 'Highest satisfaction score for a UK-built EV. Net Promoter Score lifts materially.', (1.06, 1.12), (1_200_000, 3_200_000), 'positive'),
    ('Carbon Credit Revenue Exceeds Forecast: {{company}} Books £28M Windfall', 'Strong ZEV credit demand from legacy OEMs generates unexpected income.', (1.04, 1.09), (1_600_000, 4_500_000), 'positive'),
    ('{{company}} Signs Long-Term Lithium Offtake with British Lithium', 'Multi-year Cornish lithium supply contract hedges against commodity volatility.', (1.06, 1.13), (1_400_000, 3_800_000), 'positive'),
    ('National Grid Upgrade Unlocks Rural and Scottish EV Adoption', 'Grid infrastructure investment expands addressable market into underserved regions.', (1.05, 1.11), (1_100_000, 3_000_000), 'positive'),
    ('{{company}} ADAS Feature Achieves DVSA Level 3 Regulatory Approval', 'First mass-market EV with approved Level 3 autonomy on UK motorways.', (1.09, 1.18), (2_000_000, 5_400_000), 'positive'),
    ('Company Car BIK Rate Frozen at 2%: Fleet Demand Accelerates', 'Treasury confirms zero/low BIK rate extension, driving corporate EV adoption.', (1.06, 1.13), (1_400_000, 3_600_000), 'positive'),
    ('{{company}} Wins King\'s Award for Enterprise in Sustainability', 'Royal recognition amplifies ESG credentials and attracts institutional investor interest.', (1.05, 1.11), (1_000_000, 2_600_000), 'positive'),
    ('UK-EU Trade Deal Eliminates Rules-of-Origin Tariff on British EVs', 'Removal of 10% tariff opens EU export market for UK-manufactured electric vehicles.', (1.08, 1.16), (1_900_000, 5_100_000), 'positive'),
    ('2030 ICE Sales Ban Reaffirmed: Long-Term EV Demand Certainty', 'Government confirms petrol and diesel new car sales ban from 2030, providing demand visibility.', (1.07, 1.14), (1_600_000, 4_200_000), 'positive'),
    ('Motorway Services Rapid Charging Network Reaches 100% Coverage', 'Every motorway service area in England now has 150kW+ rapid chargers.', (1.05, 1.12), (1_200_000, 3_600_000), 'positive'),
    ('{{company}} Selected for Metropolitan Police EV Fleet Pilot', 'High-visibility validation with London\'s police force opens institutional channel.', (1.07, 1.15), (1_600_000, 4_200_000), 'positive'),
    ('Sterling Strengthens: Import Component Costs Fall', 'Favourable FX movement reduces bill-of-materials cost for imported battery modules.', (1.04, 1.09), (1_100_000, 3_000_000), 'positive'),
    ('{{company}} Partners with Tesco for Destination Charging at 800 Stores', 'Free charging at UK\'s largest supermarket creates brand touchpoints during weekly shops.', (1.05, 1.12), (1_100_000, 3_400_000), 'positive'),
    ('Innovate UK Awards {{company}} £20M Clean Technology Grant', 'Grant funds next-generation solid-state battery development programme.', (1.06, 1.13), (1_400_000, 3_800_000), 'positive'),
    ('{{company}} Achieves Record 4.8 Star Trustpilot Rating', 'Organic customer advocacy drives unprecedented inbound lead volume.', (1.05, 1.11), (1_000_000, 2_800_000), 'positive'),
    ('Automotive Investment in West Midlands Creates EV Manufacturing Hub', 'Regional cluster effect attracts supplier investment and skilled workforce.', (1.04, 1.09), (1_000_000, 2_600_000), 'positive'),
    ('{{company}} Named Best British EV by The Sunday Times Driving', 'National newspaper endorsement drives consideration among premium buyers.', (1.05, 1.11), (1_100_000, 3_000_000), 'positive'),
    ('Scotland Offers Additional £3,000 EV Grant Stacking Opportunity', 'Scottish Government supplement creates strongest UK purchase incentive north of border.', (1.06, 1.14), (1_600_000, 4_200_000), 'positive'),
    ('{{company}} Cold-Weather Testing in Northern Scotland Validates Performance', 'Highland winter validation builds confidence for Scottish and Northern English buyers.', (1.05, 1.11), (1_000_000, 2_800_000), 'positive'),
    ('UK Pension Funds Increase EV Sector Allocation: {{company}} Included', 'Institutional investment from major UK pension schemes signals long-term confidence.', (1.04, 1.10), (1_000_000, 2_800_000), 'positive'),
    ('{{company}} Launches Right-Hand-Drive Exclusive Features', 'UK-specific design touches and features create differentiation versus imported rivals.', (1.05, 1.12), (1_100_000, 3_200_000), 'positive'),
    ('Autumn Statement Allocates £2.4B to UK EV Manufacturing Support', 'Landmark investment programme anchors EV supply chain in Britain.', (1.07, 1.15), (1_600_000, 4_200_000), 'positive'),

    # 40 NEGATIVE
    ('Plug-In Vehicle Grant Scrapped in Surprise Treasury Decision', 'Removal of purchase incentive creates buyer hesitation. Orders pause across the UK.', (0.84, 0.92), (-7_200_000, -3_200_000), 'negative'),
    ('{{company}} Faces Class-Action Over Advertised Range Not Matching WLTP', 'UK plaintiffs allege real-world range materially underperforms WLTP certification figures.', (0.83, 0.91), (-8_000_000, -3_600_000), 'negative'),
    ('Beast from the East Returns: EVs Stranded Across Northern England', 'Extreme cold snap generates wall-to-wall negative coverage of EV winter performance.', (0.83, 0.91), (-8_000_000, -3_600_000), 'negative'),
    ('Channel Ports Gridlock: Post-Brexit Customs Delays Hit Parts Deliveries', 'Dover and Folkestone congestion adds 5 days to European component lead times.', (0.84, 0.92), (-7_600_000, -3_400_000), 'negative'),
    ('Energy Price Cap Increase Erodes EV Running Cost Advantage', 'Ofgem price cap rise narrows the gap between EV and ICE operating costs.', (0.86, 0.93), (-5_200_000, -2_000_000), 'negative'),
    ('{{company}} Recalls 18,000 Units Over Brake Software Defect', 'DVSA mandatory recall over delayed brake response in wet conditions.', (0.82, 0.91), (-7_400_000, -3_000_000), 'negative'),
    ('Post-Brexit Rules-of-Origin Tariff Imposed on UK EVs Exported to EU', 'Local content requirements not met; 10% tariff applied to EU-bound vehicles.', (0.84, 0.92), (-7_200_000, -3_200_000), 'negative'),
    ('{{company}} Loses Key Battery Engineer to German Rival', 'Senior thermal management architect leaves for Munich. Brain drain risk intensifies.', (0.87, 0.94), (-4_800_000, -1_800_000), 'negative'),
    ('Viral Campaign Targets {{company}} on Cobalt Supply Chain Ethics', 'Extinction Rebellion campaign challenges mining practices. Brand trust drops.', (0.85, 0.93), (-5_400_000, -2_200_000), 'negative'),
    ('Global Semiconductor Shortage: {{company}} Cuts UK Production by 20%', 'Chip constraints force output reduction at Coventry facility.', (0.83, 0.92), (-6_700_000, -2_800_000), 'negative'),
    ('{{company}} Credit Rating Downgraded by Moody\'s', 'Rating agency cites cash burn and competitive pressure. Borrowing costs rise.', (0.87, 0.94), (-5_000_000, -1_900_000), 'negative'),
    ('New UK Carbon Border Adjustment Mechanism Raises Manufacturing Costs', 'CBAM import levies add £350 per vehicle to battery module costs.', (0.86, 0.93), (-5_600_000, -2_400_000), 'negative'),
    ('{{company}} Denied Planning Permission for Sunderland Expansion', 'Local council blocks gigafactory expansion. Capacity growth delayed.', (0.86, 0.93), (-5_200_000, -2_000_000), 'negative'),
    ('UK EV Market Softness: Consumer Purchase Intent Falls 15%', 'Cost-of-living crisis dampens discretionary vehicle purchases.', (0.85, 0.93), (-5_800_000, -2_400_000), 'negative'),
    ('{{company}} CFO Resignation Triggers City Short Seller Attack', 'Opportunistic short report published day of departure. LSE share price falls.', (0.86, 0.93), (-5_200_000, -2_000_000), 'negative'),
    ('Storm Isha Knocks Out Charging Infrastructure Across Scotland', 'Multi-day power outage leaves Scottish EV owners stranded. Media frenzy.', (0.84, 0.92), (-6_400_000, -2_700_000), 'negative'),
    ('Felixstowe Port Strike Delays {{company}} Component Shipments', 'Dockworker action at UK\'s largest container port disrupts supply chain.', (0.85, 0.93), (-5_600_000, -2_200_000), 'negative'),
    ('{{company}} Loses Exclusive BP Pulse Charging Partnership to Rival', 'Competitor secures exclusivity at 3,000 BP forecourt charging locations.', (0.87, 0.94), (-4_600_000, -1_800_000), 'negative'),
    ('Flooding at Midlands Battery Supplier Disrupts Production', 'Autumn flooding damages primary cell supplier facility. Force majeure declared.', (0.83, 0.92), (-6_900_000, -3_000_000), 'negative'),
    ('{{company}} Product Liability Case Settled for £60M', 'Settlement sets precedent for future UK EV litigation exposure.', (0.86, 0.93), (-5_400_000, -2_200_000), 'negative'),
    ('Viral Video of {{company}} Fire in London Car Park Gets 40M Views', 'Isolated thermal event generates disproportionate UK media coverage.', (0.81, 0.91), (-7_600_000, -3_400_000), 'negative'),
    ('UK Import Tariff on Chinese EV Components Raises Costs', 'Trade policy raises bill-of-materials for UK manufacturers using Chinese cells.', (0.84, 0.92), (-6_400_000, -2_700_000), 'negative'),
    ('{{company}} ADAS Fails DVSA Motorway Safety Audit', 'Audit failure requires feature suspension. Key selling point removed.', (0.85, 0.93), (-5_600_000, -2_200_000), 'negative'),
    ('Supply Chain Audit Finds Labour Violations at {{company}} Overseas Supplier', 'Modern slavery concerns force rapid supplier transition. Significant cost impact.', (0.86, 0.93), (-5_200_000, -2_000_000), 'negative'),
    ('Bank of England Rate Hike Makes Car Finance 16% More Expensive', 'Monetary tightening pushes PCP monthly costs beyond threshold for many buyers.', (0.84, 0.92), (-6_400_000, -2_700_000), 'negative'),
    ('Unite Union Demands 14% Wage Increase at Coventry Plant', 'Hardline bargaining threatens production continuity at main assembly facility.', (0.85, 0.93), (-5_800_000, -2_400_000), 'negative'),
    ('{{company}} Faces Patent Infringement Ruling in UK High Court', 'Court requires retroactive royalty payments and ongoing per-unit licensing.', (0.86, 0.93), (-6_000_000, -2_500_000), 'negative'),
    ('Which? Consumer Report Cites {{company}} for Poor After-Sales Service', 'Low satisfaction scores widely reported in UK consumer press.', (0.85, 0.93), (-5_200_000, -2_000_000), 'negative'),
    ('Government Delays 2030 ICE Ban to 2035: EV Demand Uncertainty', 'Policy reversal creates confusion and buyer wait-and-see behaviour.', (0.84, 0.92), (-6_400_000, -2_700_000), 'negative'),
    ('{{company}} Loses NHS Fleet Contract to Lower-Cost Rival', 'NHS procurement selects cheaper Chinese alternative for 5,000-vehicle fleet.', (0.85, 0.93), (-5_800_000, -2_400_000), 'negative'),
    ('UK EV Charging Postcode Lottery Report Goes Viral', 'Disparity in charging access generates negative press about EV viability outside cities.', (0.86, 0.94), (-4_800_000, -1_800_000), 'negative'),
    ('Brexit Red Tape Adds 48 Hours to Every Cross-Channel Parts Shipment', 'Ongoing customs friction increases supply chain costs and delays.', (0.86, 0.93), (-5_200_000, -2_000_000), 'negative'),
    ('{{company}} Investigated by CMA for Dealer Contract Terms', 'Competition authority probe forces contract renegotiation and negative press.', (0.87, 0.94), (-4_400_000, -1_600_000), 'negative'),
    ('North Sea Wind Farm Failure Causes Regional Power Grid Instability', 'Intermittent grid outages in Northern England raise EV charging reliability concerns.', (0.86, 0.93), (-5_200_000, -2_000_000), 'negative'),
    ('{{company}} Welsh-Language Marketing Omission Causes Backlash', 'Failure to provide Welsh-language materials damages brand in Wales market.', (0.87, 0.94), (-4_400_000, -1_600_000), 'negative'),
    ('Cost-of-Living Crisis Diverts Consumer Spending Away from New Cars', 'Mortgage rate shock and energy bills reduce discretionary spending on vehicles.', (0.85, 0.93), (-5_600_000, -2_200_000), 'negative'),
    ('{{company}} Battery Degradation Data Leaks: UK Owners Concerned', 'Telemetry data showing above-expected degradation in British conditions sparks coverage.', (0.84, 0.92), (-6_200_000, -2_600_000), 'negative'),
    ('Competitor Launches Aggressive Price War in UK Market', 'Two rivals cut prices by £4,000 simultaneously. Sector margins compressed.', (0.84, 0.92), (-6_400_000, -2_700_000), 'negative'),
    ('{{company}} Loses Sponsorship of Top Gear TV Segment', 'Programme restructuring drops {{company}} feature slot. Brand visibility declines.', (0.87, 0.94), (-4_600_000, -1_800_000), 'negative'),
    ('Treasury Introduces Road Tax Parity for EVs from April', 'VED exemption removed. EVs now pay same road tax as ICE vehicles.', (0.85, 0.93), (-5_600_000, -2_200_000), 'negative'),

    # 20 NEUTRAL
    ('UK EV Market Grows 35% YoY, but Competition Intensifies', 'Total sales surge but new entrants from Asia compress margins across the board.', (0.96, 1.06), (-1_600_000, 2_400_000), 'neutral'),
    ('{{company}} Restructures Dealer Network for Direct Sales', 'Transition creates friction with franchise partners but should improve margins.', (0.93, 1.03), (-2_400_000, 1_600_000), 'neutral'),
    ('DVSA Proposes New Safety Standards for EVs', 'Compliance costs increase but {{company}} existing scores provide a head start.', (0.95, 1.02), (-3_200_000, 1_200_000), 'neutral'),
    ('Industry Body Proposes UK Charging Protocol Standard', 'Proposed standard requires minor hardware updates. Timelines uncertain.', (0.96, 1.04), (-1_900_000, 1_400_000), 'neutral'),
    ('{{company}} Undertakes Leadership Team Restructure', 'C-suite reshuffle brings talent but introduces short-term execution risk.', (0.94, 1.03), (-2_200_000, 1_600_000), 'neutral'),
    ('UK Battery Recycling Regulations Tighten Under Environment Act', 'New obligations require investment. Magnitude being quantified.', (0.95, 1.02), (-2_800_000, 1_100_000), 'neutral'),
    ('Survey Shows Rising UK EV Awareness But Flat Purchase Timelines', 'Awareness improves but conversion constrained by cost-of-living pressures.', (0.96, 1.04), (-1_200_000, 1_800_000), 'neutral'),
    ('{{company}} Autonomous Pilot Launches on M25', 'Limited motorway trial generates press but financial contribution immaterial.', (0.97, 1.04), (-1_400_000, 1_800_000), 'neutral'),
    ('National Grid Study Highlights EV Charging Load Challenges', 'Study identifies bottlenecks but confirms scale of suppressed demand.', (0.96, 1.03), (-1_600_000, 1_200_000), 'neutral'),
    ('{{company}} Completes Mid-Cycle Refresh: Mixed Reception', 'Updated exterior praised but range improvement smaller than expected.', (0.95, 1.04), (-1_900_000, 2_000_000), 'neutral'),
    ('UK GDPR Update Affects {{company}} Connected Car Data', 'ICO guidance requires consent adjustments. Some features modestly reduced.', (0.95, 1.02), (-2_400_000, 1_000_000), 'neutral'),
    ('UK EV TCO Comparison: {{company}} Mid-Table', 'TCO competitive but not leading versus best-in-class alternatives.', (0.96, 1.03), (-1_200_000, 1_200_000), 'neutral'),
    ('{{company}} Annual Investor Day: Targets Reaffirmed', 'Management confirms five-year roadmap. No material guidance changes.', (0.97, 1.03), (-960_000, 1_400_000), 'neutral'),
    ('UK Automotive Talent War: Engineering Salaries Rise 10%', 'Retention investment necessary. Partially offset by reduced recruitment cost.', (0.96, 1.02), (-2_000_000, 1_000_000), 'neutral'),
    ('{{company}} Engages Third-Party ESG Audit for LSE Requirements', 'Proactive audit likely to confirm compliance. Outcome uncertain.', (0.96, 1.03), (-1_400_000, 1_200_000), 'neutral'),
    ('{{company}} Board Changes: Strategy Unchanged', 'Board reshuffle prompts City speculation but guidance reaffirmed.', (0.97, 1.03), (-800_000, 1_200_000), 'neutral'),
    ('Supply Chain Audit Reveals Mixed Results for {{company}}', 'Some lines improved, others flagged for diversification.', (0.96, 1.04), (-1_200_000, 1_200_000), 'neutral'),
    ('{{company}} Files UK Patent Portfolio Expansion', 'New IP filings signal future direction. Analyst opinions split.', (0.97, 1.03), (-800_000, 1_600_000), 'neutral'),
    ('SMMT Conference Highlights Shifting UK Consumer Preferences', 'Research suggests gradual demand evolution. No immediate disruption.', (0.96, 1.04), (-1_200_000, 1_200_000), 'neutral'),
    ('{{company}} Quarterly Earnings Meet City Expectations', 'Inline results neither excite nor concern. LSE listing trades flat.', (0.97, 1.03), (-800_000, 800_000), 'neutral'),
]


DEPT_NEWS_POOL = [
    # Operations negative
    ("Global Lithium Shortage Impacts UK Battery Supply Chain",
     "Lithium prices spike 40%. Manufacturers without locked-in contracts face delays.",
     "Operations", 1.40, 0.80, "negative"),
    ("Felixstowe Port Strike Blocks Component Shipments",
     "Dockworker action at UK's largest container port halts inbound parts delivery.",
     "Operations", 1.30, 0.85, "negative"),
    ("Unite Calls Strike at Coventry Assembly Plant",
     "Labour dispute at key facility threatens Q3 targets. Output could drop 25%.",
     "Operations", 1.35, 0.75, "negative"),
    ("Critical Assembly Robot Failure Halts Production Line",
     "Proprietary welding robot fails. Replacement parts on 14-day lead time from Japan.",
     "Operations", 1.35, 0.80, "negative"),
    ("European Battery Cell Supplier Declares Force Majeure",
     "Key Tier-1 supplier cites factory fire. Alternative sourcing at 30% premium.",
     "Operations", 1.40, 0.75, "negative"),
    ("Environment Agency Tightens Factory Emissions Standards",
     "New regulations require £11M scrubber installation. Production paused during fit-out.",
     "Operations", 1.25, 0.85, "negative"),
    ("Flooding Destroys £7M in Finished Inventory at Midlands Depot",
     "Autumn flooding damages 300 vehicles awaiting dispatch. Insurance claim filed.",
     "Operations", 1.20, 0.80, "negative"),
    ("Cobalt Price Spike Raises Battery Costs by 22%",
     "Geopolitical instability disrupts cobalt supply. Margins compressed.",
     "Operations", 1.30, 0.85, "negative"),
    ("Quality Audit Reveals Defective Wiring Harness in 4,000 Units",
     "Internal QA flags issue before delivery. Rework required on all affected vehicles.",
     "Operations", 1.25, 0.80, "negative"),
    ("Post-Brexit Customs Delays Cut Semiconductor Allocation by 30%",
     "Additional border checks reduce just-in-time delivery reliability for chips.",
     "Operations", 1.35, 0.80, "negative"),
    # Operations positive
    ("UK Government Awards £50M Advanced Manufacturing Grant",
     "Levelling Up Fund grant for Midlands EV production accelerates factory upgrades.",
     "Operations", 0.80, 1.20, "positive"),
    ("New Gigapress Installation at Coventry Cuts Body Assembly Time 40%",
     "Single-piece casting eliminates 70 weld points. Throughput and quality improve.",
     "Operations", 0.75, 1.25, "positive"),
    ("Long-Term Nickel Contract Locks In Below-Market Pricing",
     "Five-year offtake agreement secures key input at 18% below LME spot.",
     "Operations", 0.80, 1.15, "positive"),
    ("Factory Achieves ISO 14001 Environmental Certification",
     "Certification unlocks green bond financing and reduces insurance premiums.",
     "Operations", 0.85, 1.15, "positive"),
    ("Second Shift Ramp-Up at West Midlands Plant Completes Early",
     "Night shift fully operational two months ahead of schedule. Capacity doubles.",
     "Operations", 0.75, 1.25, "positive"),
    ("New Battery Recycling Line Opens at Welsh Facility",
     "In-house recycling recovers 92% of cathode materials. Costs drop.",
     "Operations", 0.80, 1.20, "positive"),
    ("Dedicated EV Distribution Hub Opens Near Birmingham",
     "Purpose-built facility cuts average delivery time across England by 2 days.",
     "Operations", 0.85, 1.15, "positive"),
    ("AI Quality Vision System Cuts Defect Rate by 60%",
     "AI inspection catches defects invisible to human inspectors. Warranty claims fall.",
     "Operations", 0.80, 1.20, "positive"),
    ("Renewable Energy PPA Signed: Factory Runs on 100% Wind Power",
     "Offshore wind PPA locks in competitive electricity rates and eliminates Scope 2.",
     "Operations", 0.85, 1.15, "positive"),
    ("Strategic Parts Warehouse Opens in Edinburgh for Scotland",
     "Regional hub provides next-day service coverage across Scotland and Northern England.",
     "Operations", 0.85, 1.15, "positive"),
    # Operations neutral
    ("Industry Shift to LFP Chemistry: UK Plants Retooling Required",
     "Lower cost chemistry requires line modifications. Long-term benefit unclear.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Unite Contract Renewal Negotiations Begin at Coventry Plant",
     "Current agreement expires in 90 days. Talks expected constructive.",
     "Operations", 1.05, 0.98, "neutral"),
    ("HSE Safety Protocols Require Additional Training Hours",
     "Compliance straightforward but reduces productive hours by 3% during transition.",
     "Operations", 1.08, 0.97, "neutral"),
    ("Tier-2 Supplier Acquired by Competitor: Terms Under Review",
     "No immediate disruption but exclusivity risk. Alternative qualification underway.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Factory Smart Grid Upgrade: Short-Term Disruption Expected",
     "Electrical modernisation requires weekend shutdowns for 6 weeks.",
     "Operations", 1.05, 0.98, "neutral"),

    # R&D negative
    ("Rival Files Patent Blocking Key Battery Technology in UK",
     "Competitor secures broad UK patent on solid-state architecture. Pivot or license required.",
     "R&D", 1.45, 0.80, "negative"),
    ("DVSA Mandates New Crash Safety Standards for EVs",
     "Additional structural testing requirements. Chassis redesign needed.",
     "R&D", 1.35, 0.85, "negative"),
    ("Software Vulnerability Discovered in ADAS Module",
     "Critical flaw requires emergency R&D response. Resources diverted from roadmap.",
     "R&D", 1.30, 0.90, "negative"),
    ("Key Chief Engineer Departs for German Rival",
     "Lead powertrain architect leaves for Munich. 6-month knowledge gap.",
     "R&D", 1.35, 0.85, "negative"),
    ("Battery Thermal Runaway During UK Type Approval Testing",
     "Prototype fails abuse test at MIRA facility. Investigation required.",
     "R&D", 1.40, 0.80, "negative"),
    ("EU Type Approval Delayed Over Documentation Gaps",
     "Regulatory reviewer requests additional evidence. EU launch timeline at risk.",
     "R&D", 1.25, 0.85, "negative"),
    ("Open-Source Licence Violation Found in Infotainment Stack",
     "Legal review requires code audit and partial rewrite.",
     "R&D", 1.20, 0.90, "negative"),
    ("WLTP Range Testing Discrepancy: Certification Review Required",
     "Internal audit reveals optimistic assumptions. Re-certification needed.",
     "R&D", 1.30, 0.85, "negative"),
    ("Supplier Discontinues Key Sensor Component",
     "Lidar module EOL forces perception hardware redesign. 4-month cycle.",
     "R&D", 1.35, 0.80, "negative"),
    ("Warwick University Research Partner Loses UKRI Funding",
     "Joint battery programme suspended. R&D must absorb costs internally.",
     "R&D", 1.25, 0.85, "negative"),
    # R&D positive
    ("Breakthrough in Solid-State Battery at Coventry R&D Centre",
     "Internal team achieves energy density milestone. Patent filing underway.",
     "R&D", 0.85, 1.25, "positive"),
    ("New Motor Design Achieves 97% Efficiency: Best in UK Market",
     "Proprietary motor topology delivers class-leading efficiency and range.",
     "R&D", 0.80, 1.20, "positive"),
    ("ADAS Passes DVSA Level 3 Validation on First Attempt",
     "Autonomous stack clears UK regulatory hurdle ahead of schedule.",
     "R&D", 0.75, 1.25, "positive"),
    ("R&D Team Wins Innovate UK Award: £18M Grant Attached",
     "UKRI grant fully funds next-gen battery prototype phase.",
     "R&D", 0.80, 1.20, "positive"),
    ("AI Simulation Platform Cuts Vehicle Testing Time by 50%",
     "Digital twin enables thousands of virtual crash and durability tests weekly.",
     "R&D", 0.85, 1.15, "positive"),
    ("UK Patent Portfolio Reaches 450 Filings: Strongest in Segment",
     "IP moat discourages competitors and enables licensing revenue.",
     "R&D", 0.85, 1.20, "positive"),
    ("Strategic Hire: Former Jaguar Land Rover VP Joins as Chief Engineer",
     "Appointment brings deep UK automotive expertise and supplier relationships.",
     "R&D", 0.80, 1.20, "positive"),
    ("Next-Gen Platform Passes All Safety Milestones 3 Months Early",
     "Accelerated timeline frees resources for future model derivatives.",
     "R&D", 0.80, 1.25, "positive"),
    ("Collaborative R&D Agreement with Oxford University Signed",
     "Three-year partnership grants access to materials science and talent.",
     "R&D", 0.85, 1.15, "positive"),
    ("OTA Architecture Praised by NCSC Security Auditors",
     "National Cyber Security Centre rates system best-in-class.",
     "R&D", 0.85, 1.15, "positive"),
    # R&D neutral
    ("New BSI Functional Safety Standard Published for UK EVs",
     "Updated standard requires documentation but aligns with existing processes.",
     "R&D", 1.08, 0.97, "neutral"),
    ("Industry Consortium Proposes Shared UK EV Platform Standard",
     "Could reduce costs but limit differentiation. Debate ongoing.",
     "R&D", 1.05, 0.98, "neutral"),
    ("CTO Announces Planned Retirement",
     "Orderly succession underway. New CTO brings fresh perspective.",
     "R&D", 1.08, 0.96, "neutral"),
    ("Academic Paper Questions NMC Chemistry Viability for UK Climate",
     "Study creates media attention. Internal assessment shows limited relevance.",
     "R&D", 1.05, 0.98, "neutral"),
    ("R&D Budget Audit Recommends Programme Reallocation",
     "Review suggests shifting resources from mature to emerging streams.",
     "R&D", 1.05, 0.98, "neutral"),

    # Sales negative
    ("Competitor Launches 0% PCP Finance Across UK",
     "Major rival undercuts with zero-interest personal contract purchase. Objections surge.",
     "Sales", 1.40, 0.80, "negative"),
    ("UK Consumer Confidence Drops to 18-Month Low",
     "Cost-of-living crisis causes buyers to delay large purchases. Conversion falls.",
     "Sales", 1.30, 0.85, "negative"),
    ("Key Regional Dealer Group Enters Administration",
     "Dealer network collapse creates sales coverage gaps in South East England.",
     "Sales", 1.25, 0.80, "negative"),
    ("Bank of England Rate Hike Makes PCP Finance 15% More Expensive",
     "Monetary tightening pushes monthly payments beyond threshold for many buyers.",
     "Sales", 1.35, 0.85, "negative"),
    ("Major Fleet Customer Cancels 1,500-Unit NHS Order",
     "NHS Trust budget cuts lead to fleet purchase freeze.",
     "Sales", 1.30, 0.80, "negative"),
    ("Negative Review by UK's Top Motoring YouTuber Goes Viral",
     "Video with 4M views highlights range anxiety concerns. Leads drop 20%.",
     "Sales", 1.25, 0.85, "negative"),
    ("Competitor Launches Price Match Guarantee Across UK Dealers",
     "Rival promises to beat any quote by £500. Pricing leverage lost.",
     "Sales", 1.30, 0.85, "negative"),
    ("Regional Sales Manager Exodus: Coverage Gaps in 4 Regions",
     "Compensation dispute triggers departures across Midlands and North.",
     "Sales", 1.35, 0.80, "negative"),
    ("Treasury Scraps BIK Rate Freeze: Company Car Demand Softens",
     "Benefit-in-Kind rate increase reduces fleet channel pipeline.",
     "Sales", 1.30, 0.85, "negative"),
    ("Competitor Slashes Prices by £5,000 Across UK EV Range",
     "Aggressive repricing forces defensive response or margin erosion.",
     "Sales", 1.35, 0.80, "negative"),
    # Sales positive
    ("Treasury Extends 2% BIK Rate for EVs Through 2028",
     "Multi-year Benefit-in-Kind certainty drives fleet order pipeline surge.",
     "Sales", 0.80, 1.25, "positive"),
    ("{{company}} Opens Flagship Showroom on Oxford Street",
     "Premium West End location drives walk-in traffic and brand awareness.",
     "Sales", 0.85, 1.20, "positive"),
    ("New Online Configurator Increases Average Order Value by 13%",
     "Redesigned digital experience drives higher trim and option rates.",
     "Sales", 0.85, 1.15, "positive"),
    ("Employer EV Salary Sacrifice Scheme Launches: 100 Companies Join",
     "Pre-tax benefit creates captive buyer channel with minimal acquisition cost.",
     "Sales", 0.80, 1.20, "positive"),
    ("Referral Programme Generates 32% of Q2 UK Orders",
     "Owner advocacy reaches critical mass across London and South East.",
     "Sales", 0.85, 1.20, "positive"),
    ("Government Scrappage Scheme: £5,000 ICE Trade-In Bonus",
     "Trade-in incentive targets cost-conscious segment. Showroom traffic spikes.",
     "Sales", 0.80, 1.20, "positive"),
    ("Fleet Partnership with Lex Autolease and Alphabet Signed",
     "Preferred vehicle status on major UK leasing platforms drives fleet volume.",
     "Sales", 0.80, 1.25, "positive"),
    ("Record Monthly Order Intake: UK Waitlist Extends to 4 Months",
     "Demand exceeds supply. Pricing power improves, discounting eliminated.",
     "Sales", 0.85, 1.20, "positive"),
    ("{{company}} Named Best Value EV by Auto Express",
     "Influential magazine endorsement drives purchase consideration.",
     "Sales", 0.85, 1.15, "positive"),
    ("Local Authority Fleet Electrification: 20 UK Councils Place Orders",
     "Nationwide municipal procurement drives volume without direct sales cost.",
     "Sales", 0.80, 1.25, "positive"),
    # Sales neutral
    ("New VED Structure Takes Effect: EV Advantage Narrowed",
     "Road tax changes reduce but don't eliminate EV cost advantage.",
     "Sales", 1.05, 0.98, "neutral"),
    ("SMMT Report Shows Flat EV Consideration Scores in UK",
     "Awareness high but conversion not accelerating. Status quo persists.",
     "Sales", 1.05, 0.97, "neutral"),
    ("Home Counties Dealer Contract Terms Up for Renegotiation",
     "Opportunity to improve margins but risk of coverage disruption.",
     "Sales", 1.08, 0.96, "neutral"),
    ("Competitor Launches Subscription Model in London Pilot",
     "Novel ownership model creates uncertainty. Buyers may delay decisions.",
     "Sales", 1.05, 0.98, "neutral"),
    ("Online Sales Audit Reveals UX Friction Points",
     "Drop-off analysis identifies improvements. Fix in progress.",
     "Sales", 1.05, 0.97, "neutral"),

    # Marketing negative
    ("Viral Social Media Backlash Over Quality Complaint",
     "Customer's viral video of panel gap issue gets millions of UK views.",
     "Marketing", 1.45, 0.75, "negative"),
    ("Competitor's Premier League Ad Campaign Dominates Mindshare",
     "Rival's high-budget football sponsorship captures national attention.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Influencer Partnership Scandal Damages Brand Trust",
     "Key UK brand ambassador involved in controversy. Messaging pivot required.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Greenwashing Accusation by UK Environmental Group Goes Viral",
     "Friends of the Earth challenges supply chain claims. Trust drops.",
     "Marketing", 1.40, 0.80, "negative"),
    ("Meta Algorithm Change Doubles UK Cost Per Lead",
     "Platform overhauls targeting. Customer acquisition cost spikes overnight.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Brand Safety Incident: Ad Appears Next to Controversial UK Content",
     "Programmatic placement in damaging context. Emergency media pull required.",
     "Marketing", 1.25, 0.85, "negative"),
    ("YouGov Brand Health Survey Downgrades {{company}}",
     "Annual tracker shows declining unaided recall in UK market.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Sponsorship Deal with Glastonbury Festival Collapses",
     "High-profile event integration cancelled. Paid media must replace at 5x cost.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Competitor Launches Aggressive Comparison Campaign in UK",
     "Head-to-head advertising targets {{company}}. Defensive response required.",
     "Marketing", 1.35, 0.80, "negative"),
    ("Data Breach at UK Marketing Agency Exposes Customer Records",
     "ICO notification required. Accelerated privacy programme investment needed.",
     "Marketing", 1.30, 0.80, "negative"),
    # Marketing positive
    ("Brand Wins 'Most Trusted UK EV' Consumer Award",
     "Industry award boosts credibility. Campaigns gain natural amplification.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Viral Delivery Video at Tower Bridge Generates 15M Views",
     "Customer experience video breaks platform records. Zero-cost brand surge.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Premier League Advertising Slot Secured at Below-Market Rate",
     "Late cancellation creates opportunity. Reach across all UK demographics.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Brand Ambassador Deal Signed with British Olympic Champion",
     "Partnership creates credibility across active lifestyle demographics.",
     "Marketing", 0.80, 1.20, "positive"),
    ("BBC Documentary on Sustainability Mission Airs on BBC Two",
     "Organic editorial in premium format. Brand search volume triples.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Campaign Wins D&AD Pencil Award for Creative Excellence",
     "UK creative industry recognition generates press and attracts talent.",
     "Marketing", 0.85, 1.15, "positive"),
    ("UK Owner Community Passes 50,000 Members",
     "Self-sustaining fan community creates authentic content at scale.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Brand Partnerships with Barbour, Dyson, and McLaren Announced",
     "Co-branding with iconic British brands elevates positioning.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Customer NPS Reaches 77: Highest in UK EV Segment",
     "Net promoter score drives word-of-mouth growth 3x above average.",
     "Marketing", 0.80, 1.20, "positive"),
    ("First-Party Data Platform Cuts UK Targeting Cost by 42%",
     "In-house data reduces reliance on third-party cookies.",
     "Marketing", 0.85, 1.15, "positive"),
    # Marketing neutral
    ("New UK Digital Privacy Regulation Restricts Ad Targeting",
     "ICO guidance limits behavioural targeting. First-party data compensates.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Annual Brand Tracker Shows Flat UK Awareness",
     "Awareness stable but not growing. Current mix sustaining reach.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Marketing Agency Contract Up for Competitive Review",
     "Mandatory rebid creates transition risk but opportunity for improvement.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("TikTok UK Algorithm Overhaul Changes Distribution",
     "Organic reach changes. Content strategy adjustment needed.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Competitor Exits Key UK Sponsorship: Opportunity Emerges",
     "Premium Six Nations rugby sponsorship available. High cost, high visibility.",
     "Marketing", 1.05, 0.97, "neutral"),
]


GENERAL_NEWS_POOL = [
    # 40 POSITIVE
    ("Government Extends Plug-In Vehicle Grant: Albion Motors Models Qualify",
     "OZEV confirms continuation of purchase grants for qualifying EVs.",
     (1.06, 1.14), (1_600_000, 4_800_000), "positive"),
    ("National Grid Rapid Charging Motorway Network Completed",
     "Every motorway service area now has 150kW+ rapid chargers.",
     (1.04, 1.10), (1_200_000, 3_200_000), "positive"),
    ("Raw Material Costs Fall as Global Lithium Supply Stabilises",
     "Battery commodity prices drop 22% YoY, improving UK EV margins.",
     (1.03, 1.08), (1_600_000, 4_000_000), "positive"),
    ("Record EV Sales Quarter in UK: Market Share Hits 28%",
     "BIK advantages and falling costs drive industry-wide volume surge.",
     (1.05, 1.12), (1_600_000, 4_400_000), "positive"),
    ("EV Insurance Costs Fall 16% as UK Actuarial Data Matures",
     "Lower premiums reduce total cost of ownership for British buyers.",
     (1.03, 1.08), (800_000, 2_400_000), "positive"),
    ("National Grid Upgrade Unlocks Rural and Scottish EV Adoption",
     "Infrastructure investment expands addressable market across the UK.",
     (1.04, 1.09), (960_000, 2_800_000), "positive"),
    ("2030 ICE Sales Ban Reaffirmed: Long-Term Certainty for UK EVs",
     "Government confirms petrol/diesel ban provides demand visibility.",
     (1.05, 1.12), (1_600_000, 4_000_000), "positive"),
    ("Company Car BIK Rate Frozen at 2%: Fleet Demand Surges",
     "Treasury confirmation drives massive corporate EV adoption pipeline.",
     (1.04, 1.10), (1_200_000, 3_200_000), "positive"),
    ("Crown Commercial Service Adds Albion Motors to Government Fleet List",
     "Approved vendor status gains first-mover volume in public sector.",
     (1.06, 1.14), (2_000_000, 4_800_000), "positive"),
    ("ZEV Credit Revenue Exceeds Forecast: Windfall Income",
     "Strong credit demand from legacy OEMs generates unexpected income.",
     (1.02, 1.06), (2_400_000, 5_600_000), "positive"),
    ("Uber UK Selects Albion Motors as Preferred EV Supplier",
     "Preferred status delivers guaranteed volume in major UK cities.",
     (1.05, 1.12), (2_000_000, 4_800_000), "positive"),
    ("UK-EU Trade Deal Eliminates Rules-of-Origin Tariff",
     "Removal of 10% tariff opens European export market for UK-built EVs.",
     (1.03, 1.08), (1_200_000, 3_200_000), "positive"),
    ("Major Legacy Automaker Exits UK EV Segment: Share Available",
     "Competitor retreat creates white-space opportunity.",
     (1.05, 1.12), (1_600_000, 4_400_000), "positive"),
    ("What Car? Names Albion Motors Best EV for British Drivers",
     "Reliability and value scores drive record inbound leads.",
     (1.04, 1.09), (1_200_000, 3_200_000), "positive"),
    ("City Analyst Upgrades Albion Motors to Buy: Target Raised 35%",
     "Institutional upgrade triggers media coverage and fleet procurement.",
     (1.04, 1.10), (1_200_000, 3_600_000), "positive"),
    ("Albion Motors Named UK Manufacturer of the Year",
     "Award reinforces brand credibility in competitive British market.",
     (1.03, 1.08), (960_000, 2_800_000), "positive"),
    ("Albion Motors Wins King's Award for Enterprise",
     "Royal recognition amplifies ESG credentials and investor interest.",
     (1.03, 1.08), (800_000, 2_400_000), "positive"),
    ("Oil Prices Surge Past £100/bbl: EV Value Proposition Strengthens",
     "High fuel costs accelerate switching from ICE across all UK segments.",
     (1.06, 1.14), (2_000_000, 4_800_000), "positive"),
    ("Imperial College Study Confirms EVs Best for UK Climate Targets",
     "Peer-reviewed research neutralises anti-EV arguments.",
     (1.03, 1.08), (800_000, 2_400_000), "positive"),
    ("UK EV Market Crosses 20% Penetration: Mainstream Phase Begins",
     "Adoption curve enters mainstream. Late adopters begin considering EVs.",
     (1.05, 1.12), (1_600_000, 4_000_000), "positive"),
    ("Home Charger Grant Extended 3 Years Under EVHS",
     "EV Homecharge Scheme extension removes charging infrastructure barrier.",
     (1.03, 1.08), (960_000, 2_800_000), "positive"),
    ("Albion Motors Auto Trader Satisfaction Score Hits All-Time High",
     "Highest UK ownership satisfaction drives referral rates.",
     (1.04, 1.09), (1_200_000, 3_200_000), "positive"),
    ("Energy Prices Fall 8%: EV Running Cost Advantage Widens",
     "Ofgem cap reduction makes EV ownership savings even more compelling.",
     (1.03, 1.07), (800_000, 2_400_000), "positive"),
    ("Albion Motors Production Record: 18,000 Units in Quarter",
     "Record quarter demonstrates manufacturing maturity.",
     (1.04, 1.10), (1_200_000, 3_600_000), "positive"),
    ("DVSA Approves Level 3 Autonomy: Albion Motors ADAS Qualifies",
     "UK regulatory framework for motorway autonomy established.",
     (1.05, 1.12), (1_600_000, 4_000_000), "positive"),
    ("Major UK Insurer Offers EV-Specific Low-Rate Policy",
     "New product from Aviva reduces TCO and removes purchase barrier.",
     (1.03, 1.07), (800_000, 2_400_000), "positive"),
    ("Government Announces £2B National EV Charging Fund",
     "Nationwide rapid charging network will eliminate range anxiety.",
     (1.04, 1.10), (1_200_000, 3_200_000), "positive"),
    ("Competitor Recall Diverts 40,000 UK Buyers: Switching Window",
     "Rival recall creates conversion opportunity. Conquest marketing activated.",
     (1.06, 1.14), (2_000_000, 5_200_000), "positive"),
    ("COP Climate Summit Strengthens UK EV Commitments",
     "International alignment provides long-term demand certainty.",
     (1.04, 1.09), (1_200_000, 3_200_000), "positive"),
    ("Albion Motors App Store Launch Opens Ecosystem Revenue",
     "In-vehicle marketplace creates recurring software income.",
     (1.03, 1.08), (1_200_000, 3_200_000), "positive"),
    ("V2G Revenue Model Approved by Ofgem",
     "Vehicle-to-grid capability adds new value proposition for UK owners.",
     (1.04, 1.09), (1_200_000, 3_200_000), "positive"),
    ("Battery Warranty Standard: Albion Motors Already Compliant",
     "Proposed 10-year UK standard positions Albion Motors well.",
     (1.03, 1.07), (800_000, 2_400_000), "positive"),
    ("UK Tech Sector Invests in EV Infrastructure: Ecosystem Grows",
     "ARM, Dyson, and others invest in connected EV ecosystem.",
     (1.04, 1.10), (1_200_000, 3_600_000), "positive"),
    ("Used EV Resale Values Surge 22% in UK: Confidence Rises",
     "Strong residuals reduce effective cost and improve PCP terms.",
     (1.04, 1.10), (1_200_000, 3_200_000), "positive"),
    ("Albion Motors OTA Update Delivers 10% Range Improvement",
     "Software efficiency update delights owners. Viral media coverage.",
     (1.04, 1.09), (960_000, 3_000_000), "positive"),
    ("National EV Awareness Week Drives Record Showroom Traffic",
     "DfT-sponsored campaign generates industry-wide foot traffic.",
     (1.03, 1.07), (800_000, 2_400_000), "positive"),
    ("Scotland Offers Additional £3,000 Grant: Stacking Opportunity",
     "Scottish Government supplement creates strongest UK incentive.",
     (1.05, 1.12), (1_400_000, 3_600_000), "positive"),
    ("Albion Motors Named Best British EV by Sunday Times Driving",
     "National newspaper endorsement drives premium buyer consideration.",
     (1.04, 1.09), (1_100_000, 3_000_000), "positive"),
    ("UK Pension Funds Increase EV Allocation: Albion Motors Included",
     "Institutional investment signals long-term sector confidence.",
     (1.03, 1.08), (960_000, 2_800_000), "positive"),
    ("Autumn Statement Allocates £2.4B to UK EV Manufacturing",
     "Landmark programme anchors EV supply chain in Britain.",
     (1.05, 1.12), (1_600_000, 4_000_000), "positive"),

    # 40 NEGATIVE
    ("Plug-In Vehicle Grant Scrapped in Treasury Spending Review",
     "Purchase incentive removal creates buyer hesitation. Orders pause.",
     (0.86, 0.93), (-5_200_000, -2_200_000), "negative"),
    ("Beast from the East Returns: EVs Stranded Across UK",
     "Extreme cold generates negative coverage of EV winter performance.",
     (0.84, 0.92), (-6_000_000, -2_600_000), "negative"),
    ("Post-Brexit Customs Gridlock Disrupts UK Supply Chain",
     "Channel port congestion adds days to European component deliveries.",
     (0.85, 0.93), (-5_600_000, -2_400_000), "negative"),
    ("Bank of England Rate Hike: PCP Finance Costs Surge",
     "Monetary tightening pushes monthly payments beyond buyer threshold.",
     (0.85, 0.93), (-5_600_000, -2_400_000), "negative"),
    ("Energy Price Cap Increase Erodes EV Running Cost Advantage",
     "Ofgem cap rise narrows gap between EV and ICE operating costs.",
     (0.87, 0.94), (-4_400_000, -1_800_000), "negative"),
    ("Post-Brexit Rules-of-Origin Tariff Hits UK EV Exports to EU",
     "10% tariff applied to EU-bound vehicles not meeting local content rules.",
     (0.86, 0.93), (-5_200_000, -2_200_000), "negative"),
    ("Albion Motors Recalls 14,000 Units Over Brake Software Defect",
     "DVSA mandatory recall over braking issue in wet conditions.",
     (0.84, 0.92), (-6_000_000, -2_600_000), "negative"),
    ("Semiconductor Shortage: UK Production Cut 18%",
     "Global chip constraints force output reduction at Coventry.",
     (0.85, 0.93), (-5_600_000, -2_400_000), "negative"),
    ("Competitor Patent Victory Restricts Key Feature in UK",
     "Court ruling blocks ADAS feature. Workaround in development.",
     (0.88, 0.95), (-3_200_000, -1_200_000), "negative"),
    ("Cost-of-Living Crisis Diverts Spending from New Cars",
     "Mortgage rates and energy bills reduce discretionary vehicle spending.",
     (0.85, 0.93), (-5_600_000, -2_200_000), "negative"),
    ("Storm Damage Knocks Out Charging in Northern England",
     "Multi-day outage leaves EV owners stranded. Media frenzy erupts.",
     (0.85, 0.93), (-5_600_000, -2_400_000), "negative"),
    ("Negative Panorama Investigation on UK EV Range Claims",
     "BBC programme challenges advertised range figures nationwide.",
     (0.86, 0.93), (-4_800_000, -2_000_000), "negative"),
    ("Felixstowe Port Strike Blocks Component Imports",
     "Dock action disrupts supply chain for weeks.",
     (0.85, 0.93), (-5_200_000, -2_200_000), "negative"),
    ("Government Delays 2030 ICE Ban to 2035",
     "Policy reversal creates confusion and buyer hesitation.",
     (0.84, 0.92), (-6_000_000, -2_600_000), "negative"),
    ("Viral Video of EV Fire in London Car Park Gets 35M Views",
     "Isolated thermal event generates disproportionate media coverage.",
     (0.84, 0.92), (-6_000_000, -2_600_000), "negative"),
    ("Sterling Weakness Raises Import Costs for Components",
     "Unfavourable FX increases bill-of-materials for imported modules.",
     (0.87, 0.94), (-4_400_000, -1_800_000), "negative"),
    ("Albion Motors Faces Class-Action Over WLTP Range Claims",
     "Plaintiffs allege real-world range materially underperforms certification.",
     (0.85, 0.93), (-5_600_000, -2_400_000), "negative"),
    ("UK EV Price War: Margins Compressed Across Sector",
     "Multiple competitors cut prices simultaneously.",
     (0.85, 0.93), (-5_200_000, -2_200_000), "negative"),
    ("North Sea Wind Farm Failure Causes Grid Instability",
     "Power outages raise EV charging reliability concerns.",
     (0.86, 0.93), (-4_800_000, -2_000_000), "negative"),
    ("Treasury Introduces VED Parity for EVs",
     "Road tax exemption removed. EVs pay same as ICE vehicles.",
     (0.85, 0.93), (-5_200_000, -2_200_000), "negative"),
    ("Albion Motors Battery Degradation Data Leaks",
     "Internal telemetry shows above-expected degradation. Owners concerned.",
     (0.85, 0.93), (-5_200_000, -2_200_000), "negative"),
    ("Automotive Labour Shortage Drives UK Wage Inflation 12%",
     "Compensation increases compress margins industry-wide.",
     (0.88, 0.95), (-3_600_000, -1_400_000), "negative"),
    ("Negative Channel 4 Documentary on EV Mining Practices",
     "Dispatches exposé creates consumer guilt and purchase hesitation.",
     (0.87, 0.94), (-3_600_000, -1_400_000), "negative"),
    ("Key Battery Patent Invalidated by UK IPO",
     "Intellectual Property Office defeat removes competitive moat.",
     (0.88, 0.94), (-3_600_000, -1_400_000), "negative"),
    ("CMA Investigation into EV Pricing Practices",
     "Competition authority scrutiny creates uncertainty.",
     (0.88, 0.95), (-3_200_000, -1_200_000), "negative"),
    ("Unite Dispute: Coventry Production Slowdown",
     "Industrial relations breakdown causes 30% output reduction.",
     (0.86, 0.93), (-4_400_000, -1_800_000), "negative"),
    ("UK EV Charging Speed Test: Albion Motors Ranks Last",
     "Poor DC charging performance widely reported.",
     (0.87, 0.94), (-4_000_000, -1_600_000), "negative"),
    ("Customer Finance Default Rates Rise Across UK",
     "Economic pressure pushes vehicle loan defaults above assumptions.",
     (0.87, 0.94), (-4_400_000, -1_800_000), "negative"),
    ("Autumn Flooding Damages Midlands Distribution Centre",
     "Seasonal flooding destroys finished inventory.",
     (0.86, 0.93), (-4_800_000, -2_000_000), "negative"),
    ("UK Import Tariff on Chinese EV Components Raises Costs",
     "Trade policy increases bill-of-materials for all UK assemblers.",
     (0.86, 0.93), (-4_800_000, -2_000_000), "negative"),
    ("Welsh Marketing Omission Causes Backlash",
     "Failure to provide Welsh materials damages brand in Wales.",
     (0.87, 0.94), (-3_600_000, -1_400_000), "negative"),
    ("Bank of England Warns of EV Sector Overvaluation",
     "Financial stability report highlights risk. Investor sentiment retreats.",
     (0.88, 0.95), (-3_200_000, -1_200_000), "negative"),
    ("Counterfeit Charger Fire in Birmingham Raises Liability Questions",
     "Third-party accessory incident creates brand halo risk.",
     (0.88, 0.95), (-3_600_000, -1_400_000), "negative"),
    ("Rising Steel Costs Add £700 Per Vehicle to BOM",
     "Commodity inflation forces pricing review or margin acceptance.",
     (0.88, 0.95), (-3_600_000, -1_400_000), "negative"),
    ("Albion Motors Forced Recall Over Charging Port Defect",
     "Safety issue requires recall of 22,000 UK vehicles.",
     (0.86, 0.93), (-4_800_000, -2_000_000), "negative"),
    ("Global Shipping Crisis Disrupts UK Vehicle Exports",
     "Container shortage delays deliveries by 8+ weeks.",
     (0.87, 0.94), (-4_000_000, -1_600_000), "negative"),
    ("Albion Motors Loses Key UK Battery Patent Challenge",
     "IP defeat removes competitive moat.",
     (0.87, 0.94), (-3_600_000, -1_400_000), "negative"),
    ("DVSA Investigation into EV Safety Reporting",
     "Regulatory scrutiny creates uncertainty despite no wrongdoing alleged.",
     (0.88, 0.95), (-3_200_000, -1_200_000), "negative"),
    ("Autonomous Vehicle Crash Investigation on M25",
     "ADAS incident creates media firestorm and potential restrictions.",
     (0.87, 0.94), (-4_000_000, -1_600_000), "negative"),
    ("Competitor Launches Aggressive UK Entry with £25K EV",
     "New entrant undercuts market. Margins compressed sector-wide.",
     (0.85, 0.93), (-5_200_000, -2_200_000), "negative"),

    # 20 NEUTRAL
    ("UK EV Market Grows 35% YoY, but Competition Intensifies",
     "Sales surge but Asian and legacy entrants compress margins.",
     (0.96, 1.06), (-1_600_000, 2_400_000), "neutral"),
    ("DVSA Proposes New Safety Testing Standards",
     "Compliance costs increase but Albion Motors scores provide head start.",
     (0.96, 1.03), (-2_400_000, 1_200_000), "neutral"),
    ("Industry Body Proposes UK Charging Standard",
     "Minor hardware updates required. Timelines uncertain.",
     (0.96, 1.04), (-1_600_000, 1_200_000), "neutral"),
    ("UK Battery Recycling Regulations Tighten",
     "New obligations require investment. Magnitude being quantified.",
     (0.96, 1.03), (-2_000_000, 960_000), "neutral"),
    ("Survey Shows Rising UK EV Awareness But Flat Purchase Intent",
     "Awareness improves but conversion constrained by cost of living.",
     (0.97, 1.04), (-1_200_000, 1_600_000), "neutral"),
    ("National Grid Study Highlights Charging Load Challenges",
     "Bottlenecks identified but suppressed demand confirmed.",
     (0.96, 1.03), (-1_200_000, 1_200_000), "neutral"),
    ("UK EV TCO Comparison: Albion Motors Mid-Table",
     "TCO competitive but not leading versus best alternatives.",
     (0.97, 1.03), (-1_200_000, 1_200_000), "neutral"),
    ("UK Auto Talent War: Engineering Salaries Rise 10%",
     "Retention investment necessary. Partially offset by recruitment savings.",
     (0.96, 1.03), (-1_600_000, 960_000), "neutral"),
    ("UK GDPR Update Affects Connected Car Data Collection",
     "ICO guidance requires consent adjustments. Features modestly reduced.",
     (0.96, 1.03), (-1_600_000, 800_000), "neutral"),
    ("Albion Motors Mid-Cycle Refresh: Mixed Reception",
     "Updated design praised; range improvement smaller than expected.",
     (0.96, 1.04), (-1_600_000, 1_600_000), "neutral"),
    ("Annual Investor Day: UK Targets Reaffirmed",
     "Management confirms roadmap. No material guidance changes.",
     (0.97, 1.03), (-800_000, 1_200_000), "neutral"),
    ("UK EV Demographics Shift: Older Buyers Entering Market",
     "Late adopters begin purchasing. Different approach may be needed.",
     (0.97, 1.04), (-800_000, 1_600_000), "neutral"),
    ("Hydrogen Vehicle Launch in UK: Limited EV Impact",
     "Alternative powertrain creates debate but volumes negligible.",
     (0.96, 1.03), (-1_200_000, 1_200_000), "neutral"),
    ("UK EV Subscription Model Gains Traction",
     "New ownership model creates uncertainty but opens channels.",
     (0.96, 1.04), (-1_200_000, 1_600_000), "neutral"),
    ("DfT Report Highlights UK Charging Gaps",
     "Government acknowledges shortfall. Funding expected.",
     (0.96, 1.03), (-1_200_000, 1_200_000), "neutral"),
    ("UK Autonomous Vehicle Insurance Framework Proposed",
     "New liability structure could help ADAS adoption but adds complexity.",
     (0.97, 1.03), (-800_000, 1_200_000), "neutral"),
    ("Used UK EV Market Grows 50%: Opportunity and Cannibalisation",
     "Strong used market validates ownership but diverts some new demand.",
     (0.96, 1.04), (-1_200_000, 1_600_000), "neutral"),
    ("Major Tech Company Enters UK EV Market",
     "New entrant brings deep pockets. Impact unclear near-term.",
     (0.95, 1.04), (-1_600_000, 1_600_000), "neutral"),
    ("Albion Motors Annual Sustainability Report Published",
     "Third-party audit confirms ESG progress. No surprises.",
     (0.97, 1.03), (-800_000, 1_200_000), "neutral"),
    ("SMMT Annual Review: UK EV Sector Outlook Unchanged",
     "Industry body report balanced. No material directional signals.",
     (0.96, 1.04), (-1_200_000, 1_200_000), "neutral"),
]
