"""News event pools for the US / EV scenario.

  COMPETITOR_NEWS_POOL: (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
  DEPT_NEWS_POOL:       (headline, detail, dept_name, k_mult, smax_mult, sentiment)
  GENERAL_NEWS_POOL:    (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
"""

COMPETITOR_NEWS_POOL = [
    # 40 POSITIVE
    ('Government Expands EV Tax Credits: {{company}} Positioned to Benefit', 'New federal policy extends $7,500 EV credits to higher income brackets, widening the addressable buyer pool.', (1.1, 1.2), (3000000, 8000000), 'positive'),
    ('{{company}} Battery Breakthrough Cuts Cost Per kWh by 18%', 'New cell chemistry enters pilot production, putting {{company}} ahead of rivals on range-per-dollar.', (1.08, 1.18), (2000000, 6000000), 'positive'),
    ('Charging Infrastructure Bill Passes: Nationwide Network Expansion Begins', '50,000 new fast-chargers to be deployed over 3 years, reducing range anxiety for all EV buyers.', (1.06, 1.14), (1600000, 5000000), 'positive'),
    ('{{company}} Wins Major Fleet Contract with National Logistics Provider', '10,000-unit purchase order locks in two years of fleet revenue ahead of schedule.', (1.12, 1.22), (4000000, 9000000), 'positive'),
    ('Consumer Reports Names {{company}} Top EV Pick for Third Consecutive Year', 'Reliability and software scores drive record inbound leads from early adopter segment.', (1.06, 1.12), (1600000, 4000000), 'positive'),
    ('Raw Material Costs Fall as Lithium Supply Stabilises', 'Battery commodity prices drop 22% YoY, materially improving EV gross margins across all players.', (1.04, 1.1), (2000000, 6000000), 'positive'),
    ('{{company}} Announces Strategic Partnership with Major Energy Provider', 'Integrated home-charging and utility billing deal accelerates adoption among suburban buyers.', (1.07, 1.15), (1600000, 4400000), 'positive'),
    ('{{company}} Awarded Five-Star Euro NCAP Safety Rating', 'Top safety score generates extensive media coverage and accelerates purchase intent across all segments.', (1.06, 1.13), (1800000, 4800000), 'positive'),
    ('Record EV Sales Quarter: Market Demand Exceeds All Forecasts', 'Pent-up consumer demand and falling battery costs drive industry-wide volume surge.', (1.08, 1.16), (2400000, 6400000), 'positive'),
    ('{{company}} Launches Industry-Leading 10-Year Battery Warranty', 'Bold warranty programme eliminates residual value anxiety and drives surge in retail enquiries.', (1.07, 1.14), (2000000, 5200000), 'positive'),
    ('Solid-State Battery Partnership Announced: {{company}} Secures Early Access', 'Joint development agreement grants exclusive early-production allocation of next-gen cells.', (1.09, 1.18), (2600000, 7000000), 'positive'),
    ('{{company}} Named EV Manufacturer of the Year at Global Auto Awards', 'Prestigious award reinforces brand credibility and generates a significant PR uplift.', (1.05, 1.12), (1400000, 3800000), 'positive'),
    ('Federal Fleet Electrification Mandate Accelerates: {{company}} On Approved Vendor List', 'Government procurement rules require 50% EV fleet by 2027; approved vendors gain first-mover volume.', (1.1, 1.19), (3000000, 7600000), 'positive'),
    ('EV Insurance Costs Fall 15% as Safety Data Matures', 'Lower insurance premiums reduce total cost of ownership, expanding the addressable market.', (1.04, 1.09), (1200000, 3400000), 'positive'),
    ('{{company}} Software Update Delivers 12% Range Improvement Overnight', 'Over-the-air update delights existing owners and generates viral social media coverage.', (1.06, 1.12), (1600000, 4200000), 'positive'),
    ('Major Ride-Share Platform Selects {{company}} as Preferred EV Supplier', 'Preferred supplier status delivers guaranteed volume and prominent in-app brand placement.', (1.09, 1.17), (2800000, 6600000), 'positive'),
    ('{{company}} Gigafactory Expansion Approved: Capacity Doubles by Year 3', 'Regulatory green light for factory expansion removes supply constraint and cuts unit costs.', (1.08, 1.15), (2200000, 5600000), 'positive'),
    ('Competitor Recall Diverts 80,000 Buyers: {{company}} Captures Switching Demand', 'High-profile rival recall creates a conversion opportunity; {{company}} activates conquest marketing.', (1.11, 1.2), (3200000, 8000000), 'positive'),
    ('{{company}} Tops J.D. Power EV Ownership Satisfaction Study', 'Highest-ever satisfaction score for a mainstream EV brand; NPS lifts materially.', (1.06, 1.12), (1600000, 4000000), 'positive'),
    ('Carbon Credit Revenue Exceeds Forecast: {{company}} Books $40M Windfall', 'Strong credit demand from legacy OEMs generates unexpected non-operating income.', (1.04, 1.09), (2000000, 5600000), 'positive'),
    ('{{company}} Signs Long-Term Lithium Offtake Agreement: Input Costs Locked', 'Multi-year supply contract hedges {{company}} against commodity volatility for three years.', (1.06, 1.13), (1800000, 4800000), 'positive'),
    ('National Grid Upgrade Programme Unlocks Rural EV Adoption', 'Infrastructure investment expands the addressable market into previously underserved regions.', (1.05, 1.11), (1400000, 3800000), 'positive'),
    ('{{company}} Autonomous Feature Achieves Level 3 Regulatory Approval', 'First mass-market EV with approved Level 3 autonomy; premium trim attach rate surges.', (1.09, 1.18), (2600000, 6800000), 'positive'),
    ('Employer EV Salary-Sacrifice Schemes Expand: Fleet Demand Accelerates', 'Tax-efficient employee benefit scheme adoption drives strong commercial pipeline growth.', (1.06, 1.13), (1800000, 4600000), 'positive'),
    ('{{company}} Wins Sustainability Leadership Award from UN Climate Body', "Recognition amplifies {{company}}'s ESG credentials and attracts institutional investor interest.", (1.05, 1.11), (1200000, 3200000), 'positive'),
    ('New State Mandate Bans ICE Vehicle Sales from 2030: EV Demand Pulled Forward', 'Legislative certainty accelerates consumer switching timelines across multiple regions.', (1.08, 1.16), (2400000, 6200000), 'positive'),
    ('{{company}} App Store Launch Unlocks Third-Party Ecosystem Revenue', 'In-vehicle app marketplace opens recurring software income stream and tech-segment appeal.', (1.06, 1.12), (1600000, 4400000), 'positive'),
    ('University Study Ranks {{company}} Battery as Safest in Class', 'Independent thermal-runaway research generates positive media and reduces buyer risk perception.', (1.05, 1.11), (1400000, 3600000), 'positive'),
    ('{{company}} Enters Strategic JV with Tier-1 Charging Network', 'Joint venture guarantees charging access for all {{company}} owners at 12,000 locations nationwide.', (1.07, 1.14), (2000000, 5200000), 'positive'),
    ('Benchmark Analyst Upgrades {{company}} to Buy: Target Price Raised 35%', 'Major institutional upgrade triggers media coverage and accelerates fleet procurement decisions.', (1.06, 1.13), (1800000, 4800000), 'positive'),
    ('{{company}} Breaks Production Record: 25,000 Units Delivered in Single Quarter', 'Record delivery quarter demonstrates manufacturing maturity and builds consumer confidence.', (1.07, 1.14), (2000000, 5200000), 'positive'),
    ('Trade Tariff Exemption Granted for {{company}} Key Battery Components', 'Exemption from import tariffs reduces bill-of-materials cost by an estimated 8%.', (1.05, 1.11), (1600000, 4200000), 'positive'),
    ('{{company}} Launches Industry-First Vehicle-to-Grid (V2G) Programme', 'V2G capability makes {{company}} vehicles a home energy asset, unlocking a new value proposition.', (1.07, 1.14), (2000000, 5000000), 'positive'),
    ('Major Automaker Exits EV Segment: Market Share Available for Capture', 'Competitor strategic retreat creates a white-space opportunity for well-positioned rivals.', (1.09, 1.17), (2600000, 6600000), 'positive'),
    ('{{company}} Ranked #1 in EV Reliability by Which? Consumer Group', 'Consumer advocacy endorsement drives strong word-of-mouth referral activity.', (1.06, 1.12), (1500000, 3900000), 'positive'),
    ('EV Adoption Rate Hits Tipping Point: Mainstream Media Coverage Intensifies', 'Cultural inflection point reduces purchase hesitancy across previously resistant demographics.', (1.06, 1.13), (1800000, 4800000), 'positive'),
    ('{{company}} Secures $500M Green Bond Issuance at Favourable Rate', "Capital markets confidence in {{company}}'s trajectory unlocks low-cost growth financing.", (1.05, 1.11), (1400000, 3600000), 'positive'),
    ('Electricity Price Caps Reduce EV Running Costs by 20%', 'Government energy intervention materially improves total cost of ownership for EV buyers.', (1.06, 1.13), (1800000, 4800000), 'positive'),
    ('{{company}} Sponsorship of Major Sporting Event Drives 40% Brand Recall Uplift', 'High-profile sponsorship activation generates sustained above-the-line brand awareness.', (1.05, 1.11), (1400000, 3500000), 'positive'),
    ('Tech Giant Integrates Native Support for {{company}} Into Its OS Platform', 'Deep platform integration improves digital experience scores and attracts tech-segment buyers.', (1.07, 1.14), (2000000, 5100000), 'positive'),

    # 40 NEGATIVE
    ('{{company}} Hit by Battery Supply Disruption: Production Halted for 6 Weeks', 'Sole-source lithium supplier faces export restrictions; delivery delays anger customers.', (0.82, 0.92), (-10000000, -4000000), 'negative'),
    ('Software Recall Affects 45,000 {{company}} Vehicles: OTA Fix Delayed', 'Autopilot feature rollback required; regulatory scrutiny and customer trust damage expected.', (0.84, 0.93), (-8000000, -3000000), 'negative'),
    ('{{company}} Faces Class Action Over Advertised Range vs. Real-World Performance', 'Lawsuit alleges systematic overstating of EPA range; legal costs and churn projected.', (0.8, 0.91), (-9000000, -3600000), 'negative'),
    ('Key EV Subsidies Reduced by 40% in Policy Reversal', 'Removal of incentives raises effective purchase price, dampening demand among budget buyers.', (0.83, 0.92), (-7000000, -3000000), 'negative'),
    ('{{company}} Faces Leadership Vacuum as CEO Departs Abruptly', 'Market confidence shaken; investor and partner uncertainty stalls several key programs.', (0.88, 0.95), (-6000000, -2000000), 'negative'),
    ('Cobalt Supply Shock Drives Battery Costs Up 30%', 'Geopolitical instability in DRC restricts cobalt exports; manufacturers face surging input costs.', (0.85, 0.93), (-8000000, -4000000), 'negative'),
    ('{{company}} Factory Fire Forces 8-Week Partial Shutdown', 'Electrical fault destroys a sub-assembly line; capacity constrained and deliveries rescheduled.', (0.81, 0.9), (-9600000, -4400000), 'negative'),
    ('Cybersecurity Breach Exposes {{company}} Owner Data: Regulatory Fine Looms', 'Unauthorised access to 600,000 customer records triggers GDPR investigation and media storm.', (0.84, 0.93), (-8400000, -3400000), 'negative'),
    ('{{company}} Loses Flagship Fleet Contract to Lower-Cost Rival', 'Preferred supplier status revoked after competitor undercuts on total cost of ownership.', (0.86, 0.94), (-7200000, -2600000), 'negative'),
    ('Interest Rate Hike Dampens Auto Financing: EV Demand Softens', 'Central bank rise pushes monthly payments beyond affordability threshold for budget segment.', (0.85, 0.93), (-7600000, -3200000), 'negative'),
    ('{{company}} Faces Whistleblower Allegations Over Battery Safety Testing', 'Internal leak to media alleges shortcuts in thermal testing; NHTSA investigation opened.', (0.78, 0.9), (-10400000, -4800000), 'negative'),
    ('Nickel Price Spike Adds $3,200 to {{company}} Battery Cost Per Vehicle', 'Commodity market disruption forces margin compression or retail price increase.', (0.84, 0.92), (-8000000, -3600000), 'negative'),
    ('{{company}} Misses Quarterly Delivery Target by 22%', 'Supply chain delays and semiconductor shortages combine to miss guidance; credibility dented.', (0.85, 0.93), (-7000000, -2800000), 'negative'),
    ('{{company}} Faces Patent Infringement Ruling: Must License Key Motor Technology', 'Court ruling requires retroactive royalty payments and ongoing per-unit licensing fees.', (0.86, 0.93), (-7600000, -3200000), 'negative'),
    ('Consumer Watchdog Report Cites {{company}} for Poor After-Sales Service', 'Low service satisfaction scores go viral; social media amplification damages brand consideration.', (0.85, 0.93), (-6600000, -2600000), 'negative'),
    ('Electricity Price Surge Erodes EV Running Cost Advantage', 'Grid tariff increases narrow the operational cost gap between EVs and efficient ICE vehicles.', (0.86, 0.93), (-6400000, -2400000), 'negative'),
    ('{{company}} Recalls 30,000 Units Over Braking Software Defect', 'Safety recall issued after field reports of delayed brake response in wet conditions.', (0.82, 0.91), (-9200000, -3800000), 'negative'),
    ('Trade War Escalation Raises {{company}} Component Import Costs 15%', 'New tariff round covers key electronic modules sourced from Asian suppliers.', (0.85, 0.93), (-7400000, -3200000), 'negative'),
    ('{{company}} Loses Key Autonomous Driving Engineer to Rival', 'Departure of principal ADAS architect signals talent retention risk; project timeline slips.', (0.87, 0.94), (-6000000, -2200000), 'negative'),
    ('Viral Social Media Campaign Targets {{company}} on Environmental Hypocrisy Claims', 'NGO campaign challenges supply chain ethics; brand consideration drops among sustainability segment.', (0.85, 0.93), (-6800000, -2800000), 'negative'),
    ('Semiconductor Shortage Returns: {{company}} Cuts Production Guidance by 18%', 'Renewed chip supply constraints force output reduction and delivery timeline extension.', (0.83, 0.92), (-8400000, -3600000), 'negative'),
    ('{{company}} Credit Rating Downgraded: Borrowing Costs Rise', 'Rating agency cites cash burn and competitive pressure; debt refinancing becomes more expensive.', (0.87, 0.94), (-6200000, -2400000), 'negative'),
    ('New Emissions Accounting Rules Reduce {{company}} Carbon Credit Income', 'Regulatory methodology change slashes carbon credit valuation; $30M annual income at risk.', (0.86, 0.93), (-7000000, -3000000), 'negative'),
    ('{{company}} Faces Regulatory Block on New Model Launch in Key EU Market', 'Type approval delays push major launch back by two quarters, ceding ground to rivals.', (0.84, 0.92), (-8000000, -3400000), 'negative'),
    ('EV Market Softness: Consumer Survey Shows Purchase Intent Falls 14%', 'Macro uncertainty and media coverage of range limitations dampen near-term purchase intentions.', (0.85, 0.93), (-7200000, -3000000), 'negative'),
    ('{{company}} CFO Resignation Triggers Short Seller Attack', 'Opportunistic short report published day of CFO departure; share price falls sharply.', (0.86, 0.93), (-6600000, -2600000), 'negative'),
    ('Extreme Cold Snap Exposes EV Range Limitations: {{company}} Fielding Complaints', 'Media coverage of range degradation in cold weather triggers customer service surge.', (0.86, 0.94), (-6000000, -2200000), 'negative'),
    ('Port Workers Strike Delays {{company}} Component Shipments by 5 Weeks', 'Industrial action at major port backs up the inbound supply chain and halts assembly.', (0.85, 0.93), (-7000000, -2800000), 'negative'),
    ('{{company}} Loses Exclusive Charging Partnership to Rival', 'Competitor secures exclusivity at 3,000 premium charging locations, disadvantaging {{company}} owners.', (0.87, 0.94), (-5800000, -2200000), 'negative'),
    ('Flood Damage at {{company}} Battery Supplier Disrupts Production', 'Natural disaster at primary cell supplier triggers force majeure and emergency resourcing.', (0.83, 0.92), (-8600000, -3800000), 'negative'),
    ('{{company}} Product Liability Case Settled for $85M', 'Out-of-court settlement of personal injury claim sets a precedent for future litigation exposure.', (0.86, 0.93), (-6800000, -2800000), 'negative'),
    ('Viral Video Showing {{company}} Fire Incident Gets 50M Views', 'Isolated thermal event amplified by media generates disproportionate brand damage.', (0.81, 0.91), (-9400000, -4200000), 'negative'),
    ('New Import Tariff Targets EVs: {{company}} Export Markets Disrupted', 'Retaliatory trade measures close a key export market, removing planned volume contribution.', (0.84, 0.92), (-8000000, -3400000), 'negative'),
    ('{{company}} Fails Autonomous Feature Regulatory Audit in Three States', 'Audit failures require feature disablement via OTA update, removing a key selling point.', (0.85, 0.93), (-7000000, -2800000), 'negative'),
    ('Supply Chain Audit Finds Labour Violations at {{company}} Tier-2 Supplier', 'Human rights concerns force rapid supplier transition; cost and timeline impact significant.', (0.86, 0.93), (-6400000, -2600000), 'negative'),
    ('{{company}} Denied Planning Permission for Second Gigafactory Site', 'Capacity expansion blocked by local authority; production ceiling constrains growth plans.', (0.86, 0.93), (-6600000, -2600000), 'negative'),
    ('Customer Financing Arm Reports Rising Default Rates', 'Macro pressure on household budgets pushes vehicle loan defaults above underwriting assumptions.', (0.86, 0.93), (-6200000, -2400000), 'negative'),
    ('{{company}} Faces Union Dispute Over Shift Patterns: Production Slowdown', 'Industrial relations breakdown at main plant causes 30% output reduction over six weeks.', (0.84, 0.92), (-8000000, -3400000), 'negative'),
    ('Benchmark Consumer EV Test Ranks {{company}} Last on Charging Speed', 'Poor real-world DC charging performance widely reported; tech-segment conversion drops.', (0.86, 0.94), (-5800000, -2200000), 'negative'),
    ('{{company}} Investigated for Anti-Competitive Dealer Contract Clauses', 'Competition authority probe forces contract renegotiation and generates negative press coverage.', (0.87, 0.94), (-5600000, -2000000), 'negative'),

    # 20 NEUTRAL
    ('EV Market Grows 38% YoY, but Competition Intensifies Sharply', 'Total EV sales surge, but new entrants from Asia and legacy OEMs compress margins across the board.', (0.96, 1.06), (-2000000, 3000000), 'neutral'),
    ('{{company}} Restructures Dealer Network Ahead of Direct-Sales Push', 'Transition creates short-term friction with partners but should improve margins long-term.', (0.93, 1.03), (-3000000, 2000000), 'neutral'),
    ('New Safety Regulations Require Additional Testing on All EV Models', "Compliance costs increase for all manufacturers, but {{company}}'s existing safety scores put it ahead.", (0.95, 1.02), (-4000000, 1600000), 'neutral'),
    ('Industry Standardisation Body Proposes New EV Charging Protocol', 'Proposed standard would require minor hardware updates across the industry; timelines uncertain.', (0.96, 1.04), (-2400000, 1800000), 'neutral'),
    ('{{company}} Undertakes Leadership Team Restructure', 'C-suite reshuffle brings new operational talent but introduces short-term execution risk.', (0.94, 1.03), (-2800000, 2000000), 'neutral'),
    ('EV Battery Recycling Regulations Tighten: {{company}} Assessing Impact', 'New end-of-life battery obligations require process investment; magnitude still being quantified.', (0.95, 1.02), (-3600000, 1400000), 'neutral'),
    ('Consumer Survey Shows Rising EV Awareness But Unchanged Purchase Timelines', 'Brand salience improves but conversion remains constrained by affordability and infrastructure.', (0.96, 1.04), (-1600000, 2200000), 'neutral'),
    ('{{company}} Pilot Programme for Autonomous Valet Feature Launches in Two Cities', 'Limited market trial generates positive press but financial contribution is immaterial near-term.', (0.97, 1.04), (-1800000, 2200000), 'neutral'),
    ('Grid Operator Publishes EV Charging Load Study: Mixed Conclusions for Manufacturers', 'Study highlights infrastructure bottlenecks but also confirms scale of suppressed demand.', (0.96, 1.03), (-2000000, 1600000), 'neutral'),
    ('{{company}} Completes Mid-Cycle Refresh of Lead Model: Reception Mixed', 'Updated exterior and interior well received in press; range improvement smaller than expected.', (0.95, 1.04), (-2400000, 2600000), 'neutral'),
    ('New Data Protection Framework Affects {{company}} Connected Car Offering', 'Compliance adjustments needed to in-car data collection practices; feature set modestly reduced.', (0.95, 1.02), (-3000000, 1200000), 'neutral'),
    ('Industry Body Publishes EV Total Cost of Ownership Comparison: {{company}} Mid-Table', 'TCO comparison shows {{company}} competitive but not leading on running costs versus best-in-class.', (0.96, 1.03), (-1600000, 1600000), 'neutral'),
    ('{{company}} Annual Investor Day Held: Long-Term Targets Reaffirmed', 'Management confirms five-year roadmap; no material upgrades or downgrades to guidance.', (0.97, 1.03), (-1200000, 1800000), 'neutral'),
    ('Automotive Sector Talent War Intensifies: {{company}} Raises Engineering Salaries', 'Retention investment necessary to prevent talent loss; partially offset by reduced recruitment cost.', (0.96, 1.02), (-2600000, 1200000), 'neutral'),
    ('{{company}} Engages Third-Party Audit of Manufacturing Sustainability Credentials', 'Proactive audit likely to confirm compliance; outcome and timeline for publication uncertain.', (0.96, 1.03), (-1800000, 1600000), 'neutral'),
    ('{{company}} Announces Leadership Restructuring: Strategic Direction Unchanged', 'Board-level changes prompt media speculation, but operational guidance is reaffirmed.', (0.97, 1.03), (-1000000, 1500000), 'neutral'),
    ('Supply Chain Audit Reveals Mixed Results for {{company}}', 'Some component lines improved, others flagged for diversification. Net impact unclear.', (0.96, 1.04), (-1500000, 1500000), 'neutral'),
    ('{{company}} Files Patent Portfolio Expansion: Competitive Implications Debated', 'New IP filings signal future product direction. Analyst opinions split on near-term impact.', (0.97, 1.03), (-1000000, 2000000), 'neutral'),
    ('Industry Conference Highlights Shifting Consumer Preferences', 'Market research presentations suggest gradual demand evolution. No immediate disruption expected.', (0.96, 1.04), (-1500000, 1500000), 'neutral'),
    ('{{company}} Quarterly Earnings Meet Expectations: No Surprises', 'Inline results neither excite nor concern investors. Stock trades flat post-announcement.', (0.97, 1.03), (-1000000, 1000000), 'neutral'),
]


DEPT_NEWS_POOL = [
    # Operations negative
    ("Global Lithium Shortage Hits Battery Supply Chain",
     "Lithium prices spike 40%. Manufacturers without locked-in contracts face production delays and cost overruns.",
     "Operations", 1.40, 0.80, "negative"),
    ("Port Congestion Delays Component Shipments by 6 Weeks",
     "Global shipping backlog impacts parts delivery. Operations teams scramble to maintain production targets.",
     "Operations", 1.30, 0.85, "negative"),
    ("Factory Worker Strike Threatens Q3 Production Targets",
     "Labour dispute at key assembly plant. Without resolution, output could drop 25% this quarter.",
     "Operations", 1.35, 0.75, "negative"),
    ("Critical Assembly Robot Failure Halts Line for 2 Weeks",
     "Proprietary welding robot suffers catastrophic failure. Replacement parts on 14-day lead time from Japan.",
     "Operations", 1.35, 0.80, "negative"),
    ("Battery Cell Supplier Declares Force Majeure",
     "Key Tier-1 supplier cites fire damage at primary factory. Alternative sourcing at 30% cost premium.",
     "Operations", 1.40, 0.75, "negative"),
    ("EPA Tightens Factory Emissions Standards: Retrofit Required",
     "New air quality regulations require $12M scrubber installation. Production paused during fit-out.",
     "Operations", 1.25, 0.85, "negative"),
    ("Warehouse Flooding Destroys $8M in Finished Inventory",
     "Extreme weather event damages 400 completed vehicles awaiting shipment. Insurance claim filed.",
     "Operations", 1.20, 0.80, "negative"),
    ("Cobalt Price Spike Raises Battery Pack Costs by 22%",
     "Geopolitical instability in DRC disrupts cobalt supply. Cost pass-through reduces gross margins.",
     "Operations", 1.30, 0.85, "negative"),
    ("Quality Audit Reveals Defective Wiring Harness in 5,000 Units",
     "Internal QA flags issue before delivery. Rework required on all affected vehicles on the line.",
     "Operations", 1.25, 0.80, "negative"),
    ("Semiconductor Allocation Cut by 35% for Next Quarter",
     "Chip supplier redirects capacity to higher-margin consumer electronics. Production schedule at risk.",
     "Operations", 1.35, 0.80, "negative"),
    # Operations positive
    ("Government Awards $50M Advanced Manufacturing Grant",
     "Federal grant for domestic EV production accelerates factory upgrades and reduces Operations costs.",
     "Operations", 0.80, 1.20, "positive"),
    ("New Gigapress Installation Cuts Body Assembly Time by 40%",
     "Single-piece casting technology eliminates 70 weld points. Throughput and quality both improve.",
     "Operations", 0.75, 1.25, "positive"),
    ("Long-Term Nickel Contract Locks In Below-Market Pricing",
     "Five-year offtake agreement secures key battery input at 18% below spot. Margin tailwind for years.",
     "Operations", 0.80, 1.15, "positive"),
    ("Factory Achieves ISO 14001 Environmental Certification",
     "Certification unlocks green bond financing and reduces insurance premiums on facility.",
     "Operations", 0.85, 1.15, "positive"),
    ("Second Shift Ramp-Up Completes Ahead of Schedule",
     "Night shift fully staffed and trained two months early. Effective capacity doubles.",
     "Operations", 0.75, 1.25, "positive"),
    ("New Battery Recycling Line Opens: Closed-Loop Materials",
     "In-house recycling recovers 92% of cathode materials. Raw material costs drop meaningfully.",
     "Operations", 0.80, 1.20, "positive"),
    ("Logistics Partner Opens Dedicated EV Distribution Hub",
     "Purpose-built facility cuts average delivery time from factory to dealer by 4 days.",
     "Operations", 0.85, 1.15, "positive"),
    ("Automated Quality Vision System Cuts Defect Rate by 60%",
     "AI-powered inspection catches micro-defects invisible to human inspectors. Warranty claims fall.",
     "Operations", 0.80, 1.20, "positive"),
    ("Renewable Energy PPA Signed: Factory Runs on 100% Clean Power",
     "Power purchase agreement locks in low electricity rates and eliminates Scope 2 emissions.",
     "Operations", 0.85, 1.15, "positive"),
    ("Strategic Spare Parts Warehouse Opens in Central US",
     "Regional parts hub cuts service turnaround from 5 days to next-day for 60% of the country.",
     "Operations", 0.85, 1.15, "positive"),
    # Operations neutral
    ("Industry-Wide Shift to LFP Chemistry: Operations Retooling Required",
     "Lower cost but different manufacturing process. Retooling investment needed; long-term cost benefit unclear.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Union Contract Renewal Negotiations Begin",
     "Current labour agreement expires in 90 days. Talks expected to be constructive but outcome uncertain.",
     "Operations", 1.05, 0.98, "neutral"),
    ("New OSHA Safety Protocols Require Additional Training Hours",
     "Compliance is straightforward but reduces productive hours by 3% during transition period.",
     "Operations", 1.08, 0.97, "neutral"),
    ("Tier-2 Supplier Acquired by Competitor: Supply Terms Under Review",
     "No immediate disruption but exclusivity risk. Alternative qualification underway.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Factory Smart Grid Upgrade: Short-Term Disruption, Long-Term Savings",
     "Electrical infrastructure modernisation requires weekend shutdowns for 6 weeks.",
     "Operations", 1.05, 0.98, "neutral"),

    # R&D negative
    ("Rival Files Patent Blocking Key Battery Technology",
     "Competitor secures broad patent on solid-state cell architecture. R&D must pivot or license at high cost.",
     "R&D", 1.45, 0.80, "negative"),
    ("NHTSA Mandates New Crash Safety Standards for EVs",
     "Regulators require additional structural reinforcement. R&D must redesign chassis components to comply.",
     "R&D", 1.35, 0.85, "negative"),
    ("Software Vulnerability Discovered in ADAS Module",
     "Critical security flaw requires emergency R&D response. Engineering resources diverted from roadmap features.",
     "R&D", 1.30, 0.90, "negative"),
    ("Key Chief Engineer Departs for Rival Startup",
     "Lead powertrain architect leaves with institutional knowledge. Successor will need 6 months to ramp.",
     "R&D", 1.35, 0.85, "negative"),
    ("Battery Thermal Runaway Incident During Testing",
     "Prototype pack fails thermal abuse test. Full root-cause investigation required before production sign-off.",
     "R&D", 1.40, 0.80, "negative"),
    ("EU Type Approval Delayed Over Software Documentation Gaps",
     "Regulatory reviewer requests additional evidence packages. Launch timeline at risk in key market.",
     "R&D", 1.25, 0.85, "negative"),
    ("Open-Source Library Licence Violation Found in Infotainment Stack",
     "Legal review requires code audit and partial rewrite of connected services platform.",
     "R&D", 1.20, 0.90, "negative"),
    ("Simulation Model Discrepancy Discovered: Range Estimates Overstated",
     "Internal audit reveals optimistic aerodynamic assumptions. EPA range re-certification needed.",
     "R&D", 1.30, 0.85, "negative"),
    ("Supplier Discontinues Key Sensor Component",
     "Lidar module end-of-life forces redesign of perception hardware stack. 4-month re-qualification cycle.",
     "R&D", 1.35, 0.80, "negative"),
    ("University Research Partner Loses Federal Funding",
     "Joint battery chemistry programme suspended. R&D must absorb costs internally or abandon workstream.",
     "R&D", 1.25, 0.85, "negative"),
    # R&D positive
    ("Breakthrough in Solid-State Battery Technology",
     "Internal R&D team achieves energy density milestone ahead of schedule. Patent filing underway.",
     "R&D", 0.85, 1.25, "positive"),
    ("New Motor Design Achieves 97% Efficiency: Industry Best",
     "Proprietary reluctance motor topology delivers class-leading efficiency. Range gains at no cost.",
     "R&D", 0.80, 1.20, "positive"),
    ("ADAS System Passes Level 3 Validation on First Attempt",
     "Autonomous driving stack clears regulatory hurdle ahead of schedule. Premium trim unlocked.",
     "R&D", 0.75, 1.25, "positive"),
    ("R&D Team Wins DOE Innovation Award: $15M Grant Attached",
     "Department of Energy recognises battery innovation. Grant fully funds next-gen prototype phase.",
     "R&D", 0.80, 1.20, "positive"),
    ("New AI Simulation Platform Cuts Vehicle Testing Time by 50%",
     "Digital twin technology allows thousands of virtual crash and durability tests per week.",
     "R&D", 0.85, 1.15, "positive"),
    ("Patent Portfolio Reaches 500 Filings: Strongest in Segment",
     "Intellectual property moat discourages fast-follower competitors and enables licensing revenue.",
     "R&D", 0.85, 1.20, "positive"),
    ("Strategic Hire: Former NASA Engineer Joins as VP of Engineering",
     "High-profile appointment brings deep thermal management expertise and attracts junior talent.",
     "R&D", 0.80, 1.20, "positive"),
    ("Next-Gen Platform Passes All Safety Milestones 3 Months Early",
     "Accelerated development timeline frees engineering resources for future model derivatives.",
     "R&D", 0.80, 1.25, "positive"),
    ("Collaborative R&D Agreement with Top University Signed",
     "Three-year partnership gives access to cutting-edge materials science research and PhD talent pipeline.",
     "R&D", 0.85, 1.15, "positive"),
    ("Over-the-Air Update Architecture Praised by Security Auditors",
     "Independent security firm rates OTA system as best-in-class. Unlocks faster feature release cadence.",
     "R&D", 0.85, 1.15, "positive"),
    # R&D neutral
    ("New ISO 26262 Functional Safety Standard Published",
     "Updated standard requires additional documentation but aligns with existing internal processes.",
     "R&D", 1.08, 0.97, "neutral"),
    ("Industry Consortium Proposes Shared EV Platform Standard",
     "If adopted, could reduce R&D costs but limit differentiation. Internal debate on whether to join.",
     "R&D", 1.05, 0.98, "neutral"),
    ("Chief Technology Officer Announces Planned Retirement",
     "Orderly succession underway. New CTO expected to bring fresh perspective but some continuity risk.",
     "R&D", 1.08, 0.96, "neutral"),
    ("Academic Paper Questions Long-Term Viability of Current Cell Chemistry",
     "Peer-reviewed study creates media attention. Internal assessment shows limited near-term relevance.",
     "R&D", 1.05, 0.98, "neutral"),
    ("R&D Budget Audit Recommends Reallocation Between Programmes",
     "Internal review suggests shifting resources from mature to emerging technology streams.",
     "R&D", 1.05, 0.98, "neutral"),

    # Sales negative
    ("Competitor Launches Aggressive 0% Financing Campaign",
     "Major rival undercuts market with zero-interest financing. Sales teams report increased price objections.",
     "Sales", 1.40, 0.80, "negative"),
    ("Consumer Confidence Index Drops to 18-Month Low",
     "Economic uncertainty causes buyers to delay large purchases. Conversion rates fall across all channels.",
     "Sales", 1.30, 0.85, "negative"),
    ("Dealership Partner Files for Bankruptcy",
     "Key regional dealer network collapses. Sales coverage gaps emerge in three major metros.",
     "Sales", 1.25, 0.80, "negative"),
    ("Interest Rate Hike Makes Auto Loans 15% More Expensive",
     "Central bank tightening pushes monthly payments beyond threshold for budget-conscious buyers.",
     "Sales", 1.35, 0.85, "negative"),
    ("Major Fleet Customer Cancels 2,000-Unit Order",
     "Corporate restructuring at key account leads to fleet purchase freeze. Pipeline hit is material.",
     "Sales", 1.30, 0.80, "negative"),
    ("Negative Viral Review by Influential Auto YouTuber",
     "Video with 5M views highlights minor UX complaints. Inbound lead volume drops 20% in two weeks.",
     "Sales", 1.25, 0.85, "negative"),
    ("Competitor Launches Direct Price Match Guarantee",
     "Rival promises to beat any competitor quote by $500. Sales team loses pricing leverage in negotiations.",
     "Sales", 1.30, 0.85, "negative"),
    ("Regional Sales Manager Exodus: 4 of 8 Territories Vacant",
     "Compensation dispute triggers simultaneous departures. Coverage gaps will take months to fill.",
     "Sales", 1.35, 0.80, "negative"),
    ("Government Suspends EV Purchase Subsidy Pending Budget Review",
     "Temporary freeze on buyer incentives creates wait-and-see behaviour. Orders pause across the market.",
     "Sales", 1.30, 0.85, "negative"),
    ("CRM System Migration Causes 3-Week Pipeline Visibility Blackout",
     "Technology transition loses historical lead scoring data. Sales prioritisation disrupted.",
     "Sales", 1.20, 0.90, "negative"),
    # Sales positive
    ("Celebrity Endorsement Goes Viral: Orders Surge",
     "A-list celebrity spotted driving Voltex Xeno generates massive organic buzz. Sales pipeline swells.",
     "Sales", 0.80, 1.20, "positive"),
    ("Corporate Tax Credit for EV Fleet Purchases Doubled",
     "New legislation makes fleet electrification dramatically more attractive. B2B pipeline surges.",
     "Sales", 0.75, 1.25, "positive"),
    ("Competitor Announces 6-Month Delivery Delay on Key Model",
     "Supply chain issues at major rival push impatient buyers into the market for alternatives.",
     "Sales", 0.80, 1.20, "positive"),
    ("Auto Show Launch Event Generates Record Test Drive Bookings",
     "Standing-room-only reveal creates 15,000 test drive bookings in 48 hours. Conversion pipeline swells.",
     "Sales", 0.80, 1.25, "positive"),
    ("New Online Configurator Increases Average Order Value by 12%",
     "Redesigned digital purchase experience drives higher trim and option attach rates.",
     "Sales", 0.85, 1.15, "positive"),
    ("Employer Salary Sacrifice Scheme Launches: 50 Companies Enrolled",
     "Pre-tax employee benefit programme creates a captive buyer channel with minimal acquisition cost.",
     "Sales", 0.80, 1.20, "positive"),
    ("Referral Programme Generates 30% of Q2 Orders",
     "Owner advocacy reaches critical mass. Word-of-mouth becomes the single largest lead source.",
     "Sales", 0.85, 1.20, "positive"),
    ("Government Announces Scrappage Scheme: $5,000 ICE Trade-In Bonus",
     "Trade-in incentive programme targets exactly the budget-conscious segment. Showroom traffic spikes.",
     "Sales", 0.80, 1.20, "positive"),
    ("Fleet Management Partnership with Major Leasing Company Signed",
     "Preferred vehicle status on 3 major leasing platforms. Fleet orders accelerate without direct sales cost.",
     "Sales", 0.80, 1.25, "positive"),
    ("Record Monthly Order Intake: Waitlist Extends to 4 Months",
     "Demand exceeds supply for the first time. Pricing power improves and discounting drops to zero.",
     "Sales", 0.85, 1.20, "positive"),
    # Sales neutral
    ("New Vehicle Registration Tax Structure Takes Effect",
     "EV advantage preserved but calculation methodology changes. Impact on buyer behaviour unclear short-term.",
     "Sales", 1.05, 0.98, "neutral"),
    ("Industry Report Shows Flat EV Consideration Scores YoY",
     "Market awareness high but conversion not accelerating. Status quo likely to persist this quarter.",
     "Sales", 1.05, 0.97, "neutral"),
    ("Regional Dealer Contract Terms Up for Renegotiation",
     "Opportunity to improve margins but risk of coverage disruption during transition.",
     "Sales", 1.08, 0.96, "neutral"),
    ("Competitor Pivots to Subscription Model: Market Watches Closely",
     "Novel ownership model creates uncertainty. Buyers may delay decisions to compare options.",
     "Sales", 1.05, 0.98, "neutral"),
    ("Online Sales Channel Audit Reveals UX Friction Points",
     "Drop-off analysis identifies improvement areas. Fix in progress but won't ship this quarter.",
     "Sales", 1.05, 0.97, "neutral"),

    # Marketing negative
    ("Viral Social Media Backlash Over Quality Complaint",
     "A single customer's viral video of a defect generates millions of views. Brand sentiment drops sharply.",
     "Marketing", 1.45, 0.75, "negative"),
    ("Competitor's Super Bowl Ad Dominates Mindshare",
     "Rival's high-budget campaign captures public attention. Marketing must invest heavily to reclaim awareness.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Influencer Partnership Scandal Damages Brand Trust",
     "Key brand ambassador involved in controversy. Marketing team must pivot messaging and rebuild credibility.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Greenwashing Accusation Goes Viral on Social Media",
     "Environmental claims challenged by activist group. Brand trust metrics decline across all segments.",
     "Marketing", 1.40, 0.80, "negative"),
    ("Ad Platform Algorithm Change Doubles Cost Per Lead",
     "Major digital platform overhauls targeting. Customer acquisition cost spikes 95% overnight.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Brand Safety Incident: Ad Appears Next to Controversial Content",
     "Programmatic placement puts brand in damaging context. Emergency media pull required.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Market Research Firm Downgrades Brand Health Score",
     "Annual brand tracker shows declining unaided recall and shrinking consideration set inclusion.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Product Placement Deal Collapses After Film Studio Dispute",
     "High-profile movie integration cancelled. Paid media must replace earned exposure at 5x the cost.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Competitor Launches Aggressive Comparison Campaign",
     "Head-to-head advertising directly targets key model. Defensive response required across all channels.",
     "Marketing", 1.35, 0.80, "negative"),
    ("Data Breach at Marketing Agency Exposes Customer Records",
     "Third-party breach requires customer notification and accelerated privacy programme investment.",
     "Marketing", 1.30, 0.80, "negative"),
    # Marketing positive
    ("Brand Wins 'Most Trusted EV' Consumer Award",
     "Industry award boosts brand credibility. Marketing campaigns gain natural amplification.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Viral Unboxing Video Generates 20M Organic Views",
     "Customer delivery experience video breaks platform records. Zero-cost brand awareness surge.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Super Bowl Ad Slot Secured at Below-Market Rate",
     "Late cancellation by another brand creates rare opportunity. Projected 120M+ household reach.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Brand Ambassador Signs 3-Year Exclusive Deal",
     "Global celebrity partnership creates instant credibility across all target demographics.",
     "Marketing", 0.80, 1.20, "positive"),
    ("Documentary Feature on Company Sustainability Mission Airs on Netflix",
     "Organic editorial coverage in premium format. Brand search volume triples during release week.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Social Media Campaign Wins Cannes Lions Award",
     "Creative excellence recognition generates industry press and attracts top agency talent.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Owner Community Passes 100,000 Members: Organic Advocacy Engine",
     "Self-sustaining fan community creates authentic content at scale. UGC outperforms paid creative.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Brand Partnerships Announced with Three Premium Lifestyle Brands",
     "Co-branding with luxury fashion, hospitality, and tech brands elevates perceived positioning.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Customer NPS Reaches 78: Highest in EV Segment",
     "Net promoter score drives word-of-mouth growth rate 3x above industry average.",
     "Marketing", 0.80, 1.20, "positive"),
    ("First-Party Data Platform Launch Cuts Targeting Cost by 40%",
     "In-house data infrastructure reduces reliance on third-party cookies and improves ad efficiency.",
     "Marketing", 0.85, 1.15, "positive"),
    # Marketing neutral
    ("New Digital Privacy Regulation Restricts Ad Targeting Options",
     "Cookie deprecation limits behavioural targeting. First-party data strategy partially compensates.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Annual Brand Tracker Shows Flat Awareness Scores",
     "Awareness stable but not growing. Current marketing mix sustaining but not expanding reach.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Marketing Agency Contract Up for Competitive Review",
     "Mandatory rebid process creates transition risk but opportunity to improve creative quality.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Social Media Platform Overhauls Content Algorithm",
     "Organic reach formula changes. Content strategy needs adjustment; paid reach unaffected.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Competitor Exits Key Sponsorship: Opportunity Emerges",
     "Premium sports sponsorship available at short notice. High cost but significant visibility upside.",
     "Marketing", 1.05, 0.97, "neutral"),
]


GENERAL_NEWS_POOL = [
    # 40 POSITIVE
    ("Government Expands EV Tax Credits: Voltex Motors Positioned to Benefit",
     "New federal policy extends $7,500 EV credits to higher income brackets, widening the addressable buyer pool.",
     (1.06, 1.14), (2_000_000, 6_000_000), "positive"),
    ("Charging Infrastructure Bill Passes: Nationwide Network Expansion",
     "50,000 new fast-chargers to be deployed over 3 years, reducing range anxiety for all EV buyers.",
     (1.04, 1.10), (1_500_000, 4_000_000), "positive"),
    ("Raw Material Costs Fall as Lithium Supply Stabilises",
     "Battery commodity prices drop 22% YoY, materially improving EV gross margins across all players.",
     (1.03, 1.08), (2_000_000, 5_000_000), "positive"),
    ("Record EV Sales Quarter: Market Demand Exceeds All Forecasts",
     "Pent-up consumer demand and falling battery costs drive industry-wide volume surge.",
     (1.05, 1.12), (2_000_000, 5_500_000), "positive"),
    ("EV Insurance Costs Fall 15% as Safety Data Matures",
     "Lower insurance premiums reduce total cost of ownership, expanding the addressable market.",
     (1.03, 1.08), (1_000_000, 3_000_000), "positive"),
    ("National Grid Upgrade Programme Unlocks Rural EV Adoption",
     "Infrastructure investment expands the addressable market into previously underserved regions.",
     (1.04, 1.09), (1_200_000, 3_500_000), "positive"),
    ("New State Mandate Bans ICE Vehicle Sales from 2030: EV Demand Pulled Forward",
     "Legislative certainty accelerates consumer switching timelines across multiple regions.",
     (1.05, 1.12), (2_000_000, 5_000_000), "positive"),
    ("Employer EV Salary-Sacrifice Schemes Expand Nationwide",
     "Tax-efficient employee benefit scheme adoption drives strong commercial pipeline growth.",
     (1.04, 1.10), (1_500_000, 4_000_000), "positive"),
    ("Federal Fleet Electrification Mandate: Voltex Motors On Approved Vendor List",
     "Government procurement rules require 50% EV fleet by 2027; approved vendors gain first-mover volume.",
     (1.06, 1.14), (2_500_000, 6_000_000), "positive"),
    ("Carbon Credit Revenue Exceeds Forecast: Windfall Income",
     "Strong credit demand from legacy OEMs generates unexpected non-operating income.",
     (1.02, 1.06), (3_000_000, 7_000_000), "positive"),
    ("Major Ride-Share Platform Selects Voltex Motors as Preferred EV Supplier",
     "Preferred supplier status delivers guaranteed volume and prominent in-app brand placement.",
     (1.05, 1.12), (2_500_000, 6_000_000), "positive"),
    ("Trade Tariff Exemption Granted for Key Battery Components",
     "Exemption from import tariffs reduces bill-of-materials cost by an estimated 8%.",
     (1.03, 1.08), (1_500_000, 4_000_000), "positive"),
    ("Major Automaker Exits EV Segment: Market Share Available",
     "Competitor strategic retreat creates a white-space opportunity for well-positioned rivals.",
     (1.05, 1.12), (2_000_000, 5_500_000), "positive"),
    ("Consumer Reports Names Voltex Motors Top EV Pick",
     "Reliability and software scores drive record inbound leads from early adopter segment.",
     (1.04, 1.09), (1_500_000, 4_000_000), "positive"),
    ("Benchmark Analyst Upgrades Voltex Motors to Buy: Price Target Raised 35%",
     "Major institutional upgrade triggers media coverage and accelerates fleet procurement decisions.",
     (1.04, 1.10), (1_500_000, 4_500_000), "positive"),
    ("Voltex Motors Named EV Manufacturer of the Year at Global Auto Awards",
     "Prestigious award reinforces brand credibility and generates significant PR uplift.",
     (1.03, 1.08), (1_200_000, 3_500_000), "positive"),
    ("Voltex Motors Wins UN Sustainability Leadership Award",
     "Recognition amplifies ESG credentials and attracts institutional investor interest.",
     (1.03, 1.08), (1_000_000, 3_000_000), "positive"),
    ("Oil Prices Surge Past $120: EV Value Proposition Strengthens",
     "High fuel costs accelerate consumer switching from ICE to electric vehicles across all segments.",
     (1.06, 1.14), (2_500_000, 6_000_000), "positive"),
    ("University Study Confirms EVs Have 40% Lower Lifetime Emissions",
     "Peer-reviewed research neutralises anti-EV talking points and boosts purchase intent.",
     (1.03, 1.08), (1_000_000, 3_000_000), "positive"),
    ("Global EV Market Crosses 20% Penetration: Tipping Point Reached",
     "Adoption curve enters mainstream phase. Laggard buyer segments begin considering EVs for the first time.",
     (1.05, 1.12), (2_000_000, 5_000_000), "positive"),
    ("Tax Incentive for Home Charger Installation Extended 3 Years",
     "Removal of charging infrastructure barrier accelerates suburban and rural EV adoption.",
     (1.03, 1.08), (1_200_000, 3_500_000), "positive"),
    ("Voltex Motors J.D. Power Satisfaction Score Hits All-Time High",
     "Highest-ever ownership satisfaction drives repeat purchase intent and referral rates up.",
     (1.04, 1.09), (1_500_000, 4_000_000), "positive"),
    ("Electricity Prices Fall 8%: EV Running Cost Advantage Widens",
     "Utility rate reduction makes EV ownership savings even more compelling versus ICE alternatives.",
     (1.03, 1.07), (1_000_000, 3_000_000), "positive"),
    ("Voltex Motors Production Record: 25,000 Units in Single Quarter",
     "Record delivery quarter demonstrates manufacturing maturity and builds consumer confidence.",
     (1.04, 1.10), (1_500_000, 4_500_000), "positive"),
    ("Autonomous Vehicle Legislation Passes: Voltex Motors ADAS Approved",
     "Regulatory framework for Level 3 autonomy established. Voltex Motors among first to qualify.",
     (1.05, 1.12), (2_000_000, 5_000_000), "positive"),
    ("Major Insurance Group Offers EV-Specific Low-Rate Policy",
     "New insurance product reduces total cost of ownership and removes purchase barrier.",
     (1.03, 1.07), (1_000_000, 3_000_000), "positive"),
    ("Government Announces $2B National EV Charging Corridor Project",
     "Coast-to-coast fast charging network will eliminate range anxiety on major highways.",
     (1.04, 1.10), (1_500_000, 4_000_000), "positive"),
    ("Competitor Recall Diverts 80,000 Buyers: Switching Opportunity",
     "High-profile rival recall creates a conversion window. Conquest marketing activated.",
     (1.06, 1.14), (2_500_000, 6_500_000), "positive"),
    ("Global Climate Summit Strengthens EV Commitments: 30 Nations Sign",
     "International policy alignment provides long-term demand certainty for EV manufacturers.",
     (1.04, 1.09), (1_500_000, 4_000_000), "positive"),
    ("Voltex Motors App Store Launch Unlocks Ecosystem Revenue",
     "In-vehicle app marketplace opens recurring software income stream and tech-segment appeal.",
     (1.03, 1.08), (1_500_000, 4_000_000), "positive"),
    ("Vehicle-to-Grid Revenue Sharing Model Approved by Utilities",
     "V2G capability makes Voltex Motors vehicles a home energy asset, adding new value proposition.",
     (1.04, 1.09), (1_500_000, 4_000_000), "positive"),
    ("New Battery Warranty Standard Proposed: Voltex Motors Already Compliant",
     "Proposed 10-year industry warranty standard positions Voltex Motors as a safe choice.",
     (1.03, 1.07), (1_000_000, 3_000_000), "positive"),
    ("Tech Giants Invest Heavily in EV Infrastructure: Ecosystem Grows",
     "Silicon Valley investment in charging and software ecosystems raises all EV boats.",
     (1.04, 1.10), (1_500_000, 4_500_000), "positive"),
    ("Used EV Resale Values Surge 25%: New Purchase Confidence Rises",
     "Strong residual values reduce effective cost of ownership and improve financing terms.",
     (1.04, 1.10), (1_500_000, 4_000_000), "positive"),
    ("Voltex Motors Software Update Delivers 12% Range Improvement Overnight",
     "Over-the-air update delights existing owners and generates viral social media coverage.",
     (1.04, 1.09), (1_200_000, 3_800_000), "positive"),
    ("National EV Awareness Week Drives Record Showroom Traffic",
     "Government-sponsored campaign generates industry-wide foot traffic boost.",
     (1.04, 1.09), (1_200_000, 3_500_000), "positive"),
    ("Voltex Motors Battery Rated Safest in Independent University Study",
     "Thermal-runaway research generates positive media and reduces buyer risk perception.",
     (1.03, 1.08), (1_200_000, 3_500_000), "positive"),
    ("Scrappage Scheme Announced: $5,000 ICE Trade-In Bonus for EV Purchase",
     "Government incentive programme directly targets ICE-to-EV switching. Market demand spikes.",
     (1.06, 1.14), (2_500_000, 6_000_000), "positive"),
    ("Voltex Motors Breaks Into Fortune 500: Institutional Credibility Boost",
     "First appearance on the list generates extensive business media coverage and analyst interest.",
     (1.03, 1.08), (1_200_000, 3_500_000), "positive"),
    ("Industry Report Projects 45% EV Market Share by 2030",
     "Bullish analyst consensus creates positive sentiment and encourages consumer commitment.",
     (1.04, 1.10), (1_500_000, 4_000_000), "positive"),

    # 40 NEGATIVE
    ("Global Recession Fears Intensify: Consumer Spending Contracts",
     "Macroeconomic downturn reduces discretionary purchases. Big-ticket items like EVs hit hardest.",
     (0.86, 0.94), (-6_000_000, -2_500_000), "negative"),
    ("Interest Rates Rise to 15-Year High: Auto Loan Demand Drops",
     "Central bank tightening makes vehicle financing significantly more expensive for all buyers.",
     (0.88, 0.95), (-5_000_000, -2_000_000), "negative"),
    ("New Import Tariff Targets EVs: Export Markets Disrupted",
     "Retaliatory trade measures close a key export market, removing planned volume contribution.",
     (0.86, 0.93), (-6_000_000, -2_500_000), "negative"),
    ("Government Suspends EV Purchase Subsidies Pending Budget Review",
     "Temporary freeze on buyer incentives creates wait-and-see behaviour across the market.",
     (0.88, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Chinese EV Manufacturer Enters Market with 30% Price Undercut",
     "Low-cost competitor launch compresses pricing across all segments. Margin pressure intensifies.",
     (0.85, 0.93), (-5_500_000, -2_200_000), "negative"),
    ("Electricity Prices Surge 25%: EV Running Cost Advantage Narrows",
     "Energy market volatility weakens the total-cost-of-ownership case for switching from ICE.",
     (0.88, 0.95), (-4_000_000, -1_500_000), "negative"),
    ("Grid Reliability Concerns Trigger Anti-EV Legislative Push",
     "Utility strain narrative fuels political opposition. Three states propose EV registration surcharges.",
     (0.87, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Analyst Downgrades Entire EV Sector: Overcapacity Concerns",
     "Sector-wide note citing overcapacity and margin compression triggers institutional selling.",
     (0.86, 0.93), (-5_500_000, -2_200_000), "negative"),
    ("Voltex Motors Investigated for Anti-Competitive Contract Clauses",
     "Competition authority probe forces contract renegotiation and generates negative press.",
     (0.88, 0.95), (-4_000_000, -1_600_000), "negative"),
    ("Voltex Motors Misses Sustainability Targets: ESG Fund Exclusion Risk",
     "Carbon intensity metrics miss published roadmap; ESG index exclusion letter received.",
     (0.88, 0.95), (-4_500_000, -1_800_000), "negative"),
    ("Insurance Industry Raises EV Model Repair Cost Classification",
     "Reclassification as high-repair-cost vehicle increases insurance premiums and dampens demand.",
     (0.88, 0.95), (-4_000_000, -1_600_000), "negative"),
    ("Adverse Media Piece on Executive Pay Damages Public Relations",
     "Front-page story on executive compensation triggers talent retention risk and PR spend.",
     (0.90, 0.96), (-3_500_000, -1_400_000), "negative"),
    ("EV Demand Slowdown in Key Market: Inventory Builds",
     "Slowing retail pace in Europe forces build-to-inventory, tying up working capital.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Supply Chain Audit Finds Labour Violations at Tier-2 Supplier",
     "Human rights concerns force rapid supplier transition; cost and timeline impact significant.",
     (0.88, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Customer Financing Arm Reports Rising Default Rates",
     "Macro pressure on household budgets pushes vehicle loan defaults above underwriting assumptions.",
     (0.88, 0.95), (-4_500_000, -1_800_000), "negative"),
    ("Used EV Resale Values Drop 20%: Consumer Confidence Weakens",
     "Declining residual values raise effective cost of ownership and weaken financing terms.",
     (0.87, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Competitor Launches Superior Product at Lower Price Point",
     "Rival's new model undercuts Voltex Motors on range, features, and price simultaneously.",
     (0.85, 0.93), (-5_500_000, -2_200_000), "negative"),
    ("Cybersecurity Breach Exposes Connected Vehicle Data",
     "Customer driving data exposed in hack. Trust damage and compliance costs are significant.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Major Market Bans Autonomous Driving Features Pending Review",
     "Regulatory freeze removes a key differentiator in the tech-savvy segment.",
     (0.88, 0.95), (-4_000_000, -1_600_000), "negative"),
    ("Voltex Motors Denied Planning Permission for Second Factory Site",
     "Capacity expansion blocked. Production ceiling constrains growth plans for next 2 years.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Oil Prices Crash Below $40: EV Cost Advantage Disappears Temporarily",
     "Cheap petrol weakens the economic case for EVs. Fence-sitters delay purchase decisions.",
     (0.86, 0.93), (-5_500_000, -2_200_000), "negative"),
    ("National Power Grid Failure Creates Anti-EV Media Narrative",
     "Multi-day blackout generates widespread concern about EV charging reliability.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Class Action Lawsuit Filed Over Battery Degradation Claims",
     "Consumer group alleges range loss exceeds warranty parameters. Legal costs and PR damage accrue.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Rare Earth Export Ban Threatens Motor Manufacturing Supply",
     "Geopolitical dispute restricts access to critical permanent magnet materials.",
     (0.86, 0.93), (-5_500_000, -2_200_000), "negative"),
    ("Benchmark Consumer Test Ranks Voltex Motors Last on Charging Speed",
     "Poor real-world DC charging performance widely reported. Tech-segment conversion drops.",
     (0.88, 0.95), (-4_000_000, -1_600_000), "negative"),
    ("Voltex Motors Over-the-Air Update Bricks 12,000 Vehicles",
     "Failed software deployment requires physical dealer visit. Customer satisfaction collapses.",
     (0.85, 0.92), (-6_500_000, -2_800_000), "negative"),
    ("Counterfeit Charger Causes House Fire: Liability Questions Raised",
     "Third-party accessory incident creates brand halo risk despite lack of direct fault.",
     (0.88, 0.95), (-4_500_000, -1_800_000), "negative"),
    ("Rising Steel Costs Add $800 Per Vehicle to Bill-of-Materials",
     "Commodity inflation flow-through forces pricing review or margin acceptance.",
     (0.88, 0.95), (-4_500_000, -1_800_000), "negative"),
    ("Voltex Motors Faces Forced Recall Over Charging Port Defect",
     "Safety issue with charging port seal requires recall of 28,000 vehicles.",
     (0.86, 0.93), (-6_000_000, -2_500_000), "negative"),
    ("Competitor Patent Victory Blocks Key Feature Expansion",
     "Court ruling restricts use of a popular driver assistance feature. Workaround in development.",
     (0.88, 0.95), (-4_000_000, -1_600_000), "negative"),
    ("Automotive Industry Labour Shortage Drives Wage Inflation 12%",
     "Across-the-board compensation increases compress operating margins industry-wide.",
     (0.88, 0.95), (-4_500_000, -1_800_000), "negative"),
    ("Negative Documentary on EV Mining Practices Airs Nationally",
     "Exposé on cobalt and lithium mining conditions creates consumer guilt and purchase hesitation.",
     (0.87, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Key Battery Patent Invalidated: Competitors Gain Freedom to Operate",
     "Court defeat removes a competitive moat and increases technology commoditisation risk.",
     (0.88, 0.94), (-4_500_000, -1_800_000), "negative"),
    ("Federal Investigation into EV Safety Data Reporting Practices",
     "Regulatory scrutiny creates uncertainty. No wrongdoing alleged but media coverage is damaging.",
     (0.88, 0.95), (-4_000_000, -1_600_000), "negative"),
    ("Voltex Motors Union Dispute Over Shift Patterns: Production Slowdown",
     "Industrial relations breakdown at main plant causes output reduction for six weeks.",
     (0.86, 0.93), (-5_500_000, -2_200_000), "negative"),
    ("Autonomous Vehicle Crash Investigation Triggers Regulatory Review",
     "Incident involving ADAS feature creates media firestorm and potential feature restrictions.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("Global Shipping Crisis Disrupts Vehicle Export Logistics",
     "Container shortage and port congestion delays international deliveries by 8+ weeks.",
     (0.87, 0.94), (-5_000_000, -2_000_000), "negative"),
    ("EV Market Price War Erupts: Margins Compressed Across Sector",
     "Multiple competitors cut prices simultaneously. Race to the bottom compresses industry margins.",
     (0.85, 0.93), (-5_500_000, -2_200_000), "negative"),
    ("Central Bank Warns of Asset Bubble in EV Sector",
     "Financial stability report highlights overvaluation risk. Investor sentiment and stock price retreat.",
     (0.88, 0.95), (-4_000_000, -1_600_000), "negative"),
    ("Voltex Motors Loses Key Battery Patent Challenge",
     "IPO defeat removes a competitive moat and increases technology commoditisation risk.",
     (0.87, 0.94), (-4_500_000, -1_800_000), "negative"),

    # 20 NEUTRAL
    ("EV Market Grows 38% YoY, but Competition Intensifies Sharply",
     "Total EV sales surge, but new entrants compress margins across the board.",
     (0.96, 1.06), (-2_000_000, 3_000_000), "neutral"),
    ("New Safety Regulations Require Additional Testing on All EV Models",
     "Compliance costs increase for all manufacturers. Voltex Motors existing safety scores provide a head start.",
     (0.96, 1.03), (-3_000_000, 1_500_000), "neutral"),
    ("Industry Standardisation Body Proposes New EV Charging Protocol",
     "Proposed standard would require minor hardware updates across the industry; timelines uncertain.",
     (0.96, 1.04), (-2_000_000, 1_500_000), "neutral"),
    ("EV Battery Recycling Regulations Tighten Across Multiple Markets",
     "New end-of-life battery obligations require process investment; magnitude being quantified.",
     (0.96, 1.03), (-2_500_000, 1_200_000), "neutral"),
    ("Consumer Survey Shows Rising EV Awareness But Unchanged Purchase Timelines",
     "Brand salience improves but conversion remains constrained by affordability and infrastructure.",
     (0.97, 1.04), (-1_500_000, 2_000_000), "neutral"),
    ("Grid Operator Publishes EV Charging Load Study: Mixed Conclusions",
     "Study highlights infrastructure bottlenecks but also confirms scale of suppressed demand.",
     (0.96, 1.03), (-1_500_000, 1_500_000), "neutral"),
    ("Industry Body Publishes EV Total Cost of Ownership Comparison",
     "TCO comparison shows Voltex Motors competitive but not leading versus best-in-class on running costs.",
     (0.97, 1.03), (-1_500_000, 1_500_000), "neutral"),
    ("Automotive Sector Talent War Intensifies: Salaries Rise 8%",
     "Retention investment necessary to prevent talent loss; partially offset by reduced recruitment cost.",
     (0.96, 1.03), (-2_000_000, 1_200_000), "neutral"),
    ("New Data Protection Framework Affects Connected Car Offerings",
     "Compliance adjustments needed to in-car data collection practices; feature set modestly reduced.",
     (0.96, 1.03), (-2_000_000, 1_000_000), "neutral"),
    ("Voltex Motors Completes Mid-Cycle Refresh: Reception Mixed",
     "Updated exterior well received; range improvement smaller than expected.",
     (0.96, 1.04), (-2_000_000, 2_000_000), "neutral"),
    ("Annual Investor Day Held: Long-Term Targets Reaffirmed",
     "Management confirms five-year roadmap; no material upgrades or downgrades to guidance.",
     (0.97, 1.03), (-1_000_000, 1_500_000), "neutral"),
    ("EV Ownership Demographics Shift: Older Buyers Entering Market",
     "Traditional late-adopter demographics begin purchasing. Different marketing approach may be needed.",
     (0.97, 1.04), (-1_000_000, 2_000_000), "neutral"),
    ("Hydrogen Fuel Cell Vehicle Launches: Limited EV Segment Impact Expected",
     "Alternative powertrain creates media debate but volumes remain negligible versus battery EVs.",
     (0.96, 1.03), (-1_500_000, 1_500_000), "neutral"),
    ("Global EV Standards Harmonisation Talks Begin",
     "Multi-nation discussions on unified charging and safety standards. Outcome uncertain but promising.",
     (0.97, 1.04), (-1_000_000, 2_000_000), "neutral"),
    ("EV Subscription Model Gains Traction: Ownership Patterns Evolving",
     "New business model creates uncertainty for traditional purchase funnel but opens new channels.",
     (0.96, 1.04), (-1_500_000, 2_000_000), "neutral"),
    ("National Infrastructure Report Highlights EV Charging Gaps",
     "Government acknowledges coverage shortfall. Funding commitment expected but timeline unclear.",
     (0.96, 1.03), (-1_500_000, 1_500_000), "neutral"),
    ("Autonomous Vehicle Insurance Framework Proposed",
     "New liability structure could accelerate ADAS adoption but also introduces compliance complexity.",
     (0.97, 1.03), (-1_000_000, 1_500_000), "neutral"),
    ("Second-Hand EV Market Grows 60%: Creates Both Opportunity and Cannibalisation Risk",
     "Strong used market validates ownership proposition but may divert some new-car demand.",
     (0.96, 1.04), (-1_500_000, 2_000_000), "neutral"),
    ("Major Tech Company Enters EV Market: Industry Watches Closely",
     "New entrant brings deep pockets and software expertise. Impact on Voltex Motors unclear near-term.",
     (0.95, 1.04), (-2_000_000, 2_000_000), "neutral"),
    ("Voltex Motors Annual Sustainability Report Published",
     "Third-party audit confirms progress on ESG goals. No material surprises in either direction.",
     (0.97, 1.03), (-1_000_000, 1_500_000), "neutral"),
]


