"""News event pools for the US / PHARMA scenario.

  COMPETITOR_NEWS_POOL: (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
  DEPT_NEWS_POOL:       (headline, detail, dept_name, k_mult, smax_mult, sentiment)
  GENERAL_NEWS_POOL:    (headline, detail, (rev_mult_min, rev_mult_max), (profit_min, profit_max), sentiment)
"""

COMPETITOR_NEWS_POOL = [
    # 40 POSITIVE
    ('FDA Grants {{company}} Expanded Label for Pediatric Use', 'New age-group approval widens addressable patient population by an estimated 18%.', (1.10, 1.20), (1_800_000, 4_800_000), 'positive'),
    ('{{company}} Smart Pen Wins CES Best Health Innovation Award', 'Consumer tech recognition drives physician curiosity and patient demand for connected insulin delivery.', (1.06, 1.14), (900_000, 2_700_000), 'positive'),
    ('Major PBM Adds {{company}} to Preferred Formulary — 40M Lives Covered', 'Express Scripts listing unlocks the largest managed care channel in the US.', (1.12, 1.22), (2_400_000, 6_000_000), 'positive'),
    ('{{company}} Real-World Evidence Study Shows 22% Better Time-in-Range', 'Published outcomes data strengthens clinical positioning versus legacy insulin pens.', (1.08, 1.18), (1_200_000, 3_600_000), 'positive'),
    ('CMS Adds Connected Insulin Delivery to Medicare Part B Coverage', 'Federal reimbursement decision unlocks the 65+ diabetic population — the largest insulin segment.', (1.10, 1.20), (2_000_000, 5_400_000), 'positive'),
    ('{{company}} Partners with Dexcom for Integrated Glucose Monitoring', 'CGM integration makes the smart pen a closed-loop ecosystem. Endocrinologists take notice.', (1.08, 1.16), (1_400_000, 3_800_000), 'positive'),
    ('Inflation Reduction Act Caps Insulin Copays at $35 — Demand Surges', 'Federal price cap removes patient affordability barrier. New patient starts accelerate nationwide.', (1.08, 1.16), (1_800_000, 4_500_000), 'positive'),
    ('{{company}} Secures Exclusive Partnership with CVS Health', 'Preferred pharmacy status at 9,000+ CVS locations drives patient access and refill convenience.', (1.09, 1.17), (1_600_000, 4_200_000), 'positive'),
    ('ADA Annual Conference Highlights {{company}} Clinical Data', 'American Diabetes Association presentation generates physician buzz and media coverage.', (1.06, 1.13), (900_000, 2_700_000), 'positive'),
    ('{{company}} App Reaches 500K Downloads — Engagement Metrics Strong', 'Connected pen ecosystem shows patient stickiness. Refill rates 30% higher than competitors.', (1.07, 1.15), (1_200_000, 3_400_000), 'positive'),
    ('Hospital GPO Awards {{company}} Preferred Vendor Status', 'Group purchasing organization contract covers 2,000+ US hospitals.', (1.10, 1.19), (2_000_000, 5_200_000), 'positive'),
    ('{{company}} Patent Portfolio Strengthened — 15 New Filings Granted', 'IP moat around smart pen technology discourages generic device copycats.', (1.06, 1.12), (800_000, 2_400_000), 'positive'),
    ('Competitor Recalls Insulin Pen Over Dosing Defect — Patients Switch', 'Major rival recall creates 60-day switching window. {{company}} captures displaced patients.', (1.11, 1.20), (2_200_000, 5_800_000), 'positive'),
    ('{{company}} Secures 340B Contract with Safety-Net Hospital Network', 'Federally qualified health centers adopt {{company}} for underserved diabetic populations.', (1.07, 1.15), (1_200_000, 3_400_000), 'positive'),
    ('FDA Fast-Tracks {{company}} Next-Gen Smart Pen Application', 'Breakthrough device designation accelerates regulatory timeline by 6+ months.', (1.08, 1.16), (1_400_000, 3_800_000), 'positive'),
    ('{{company}} Named Top Digital Health Innovator by HIMSS', 'Healthcare IT recognition drives interest from large integrated health systems.', (1.05, 1.12), (700_000, 2_200_000), 'positive'),
    ('Major Employer Self-Insured Plan Selects {{company}} for 200K Employees', 'Fortune 100 corporate health plan adoption creates high-volume, high-margin channel.', (1.09, 1.17), (1_800_000, 4_500_000), 'positive'),
    ('{{company}} Publishes Head-to-Head Trial Beating Market Leader on HbA1c', 'Superiority data in peer-reviewed journal transforms physician perception.', (1.10, 1.19), (2_000_000, 5_400_000), 'positive'),
    ('Endocrinology Society Endorses Connected Insulin Delivery in Guidelines', 'Professional society recommendation creates a tailwind for all smart pen makers.', (1.06, 1.14), (1_000_000, 3_000_000), 'positive'),
    ('{{company}} Manufacturing Achieves Zero Defect Quarter — Quality Award', 'Flawless production record builds payer and physician confidence.', (1.05, 1.12), (700_000, 2_200_000), 'positive'),
    ('Walgreens Expands {{company}} Shelf Placement Nationwide', 'Increased pharmacy visibility drives walk-in prescription conversions.', (1.07, 1.14), (1_100_000, 3_200_000), 'positive'),
    ('{{company}} Smart Pen Data Cited in New ADA Treatment Algorithm', 'Incorporation into treatment guidelines drives protocol-based prescribing.', (1.08, 1.16), (1_400_000, 3_800_000), 'positive'),
    ('VA Health System Adopts {{company}} for 500K Veteran Patients', 'Veterans Affairs contract is largest single-payer win in company history.', (1.11, 1.20), (2_200_000, 5_800_000), 'positive'),
    ('{{company}} Raises $120M Series D — Analyst Upgrades Follow', 'Capital raise signals confidence. Three Wall Street firms upgrade to Buy.', (1.06, 1.13), (1_000_000, 3_000_000), 'positive'),
    ('Patient Advocacy Group Endorses {{company}} Smart Pen Platform', 'JDRF endorsement drives awareness among Type 1 diabetes community.', (1.05, 1.12), (700_000, 2_200_000), 'positive'),
    ('{{company}} OTA Update Adds Meal Tracking — Patient Satisfaction Surges', 'Software feature update increases daily engagement by 40%.', (1.06, 1.13), (900_000, 2_700_000), 'positive'),
    ('Insulin Shortage at Competitor Creates 90-Day Supply Gap', 'Manufacturing disruption at major rival forces pharmacy chains to seek alternatives.', (1.10, 1.19), (2_000_000, 5_200_000), 'positive'),
    ('{{company}} Wins J.D. Power Patient Satisfaction Award', 'Highest-rated insulin delivery device in annual patient survey.', (1.05, 1.12), (700_000, 2_200_000), 'positive'),
    ('State Medicaid Programs in 12 States Add {{company}} to Formulary', 'Medicaid expansion provides access for lowest-income diabetic patients.', (1.09, 1.17), (1_600_000, 4_200_000), 'positive'),
    ('{{company}} Cold Chain Innovation Eliminates Refrigeration Need for 30 Days', 'Room-temperature stability breakthrough simplifies distribution and patient convenience.', (1.07, 1.15), (1_200_000, 3_400_000), 'positive'),
    ('Digital Health Reimbursement Code Approved for Smart Pen Monitoring', 'New CPT code allows physicians to bill for reviewing connected pen data.', (1.08, 1.16), (1_400_000, 3_800_000), 'positive'),
    ('{{company}} Selected for CDC Diabetes Prevention Integration Pilot', 'Federal public health partnership creates visibility and credibility.', (1.06, 1.13), (900_000, 2_700_000), 'positive'),
    ('Record Quarter — {{company}} Enrolls 12,000 New Patients in Q3', 'Accelerating patient acquisition demonstrates commercial traction.', (1.08, 1.16), (1_400_000, 3_800_000), 'positive'),
    ('{{company}} Smart Pen Reduces ER Visits by 35% in Health System Study', 'Real-world cost savings data makes the economic case for payers.', (1.09, 1.17), (1_600_000, 4_500_000), 'positive'),
    ('Pharmacy Benefit Manager Waives Prior Authorization for {{company}}', 'Removal of prescription hurdle accelerates time-to-patient by 2 weeks.', (1.07, 1.14), (1_100_000, 3_200_000), 'positive'),
    ('{{company}} Pen Awarded IP Protection in Trade Dress Ruling', 'Court ruling prevents copycat device designs. Competitive moat strengthened.', (1.05, 1.11), (600_000, 2_000_000), 'positive'),
    ('Telehealth Integration Allows Remote Smart Pen Prescribing', 'Virtual care compatibility expands addressable prescriber base.', (1.06, 1.13), (900_000, 2_700_000), 'positive'),
    ('{{company}} Named to Forbes Most Innovative Healthcare Companies', 'Media recognition drives investor interest and talent acquisition.', (1.04, 1.10), (500_000, 1_800_000), 'positive'),
    ('Health Insurer Offers Premium Discount for {{company}} Smart Pen Users', 'Outcome-based insurance incentive drives patient enrollment.', (1.08, 1.16), (1_400_000, 3_800_000), 'positive'),
    ('{{company}} Announces Zero-Cost Patient Assistance Program', 'Copay assistance program removes financial barrier for 100K uninsured patients.', (1.07, 1.14), (1_100_000, 3_200_000), 'positive'),

    # 40 NEGATIVE
    ('FDA Issues Complete Response Letter — Label Expansion Delayed', 'Regulatory setback requires additional clinical data. Pediatric indication pushed back 18 months.', (0.84, 0.92), (-5_400_000, -2_400_000), 'negative'),
    ('Major PBM Drops {{company}} from Preferred Formulary', 'Express Scripts exclusion cuts access to 35M covered lives overnight.', (0.82, 0.91), (-6_000_000, -2_800_000), 'negative'),
    ('{{company}} Faces Patent Infringement Lawsuit from Market Leader', 'Injunction threat could force smart pen redesign or licensing payments.', (0.85, 0.93), (-4_500_000, -1_800_000), 'negative'),
    ('FDA Warning Letter Over Manufacturing Deficiency at Boston Facility', 'GMP violation requires remediation. Production capacity reduced during fix.', (0.83, 0.92), (-5_200_000, -2_200_000), 'negative'),
    ('Congressional Hearing Targets Insulin Pricing — {{company}} Called to Testify', 'Political scrutiny creates negative media coverage and pricing pressure.', (0.86, 0.93), (-3_800_000, -1_500_000), 'negative'),
    ('Competitor Launches Biosimilar Smart Pen at 40% Lower Price', 'New entrant undercuts {{company}} with aggressive pricing. Market share at risk.', (0.83, 0.91), (-5_500_000, -2_400_000), 'negative'),
    ('{{company}} Smart Pen App Suffers Data Breach — 80K Patient Records Exposed', 'HIPAA violation triggers investigation and erodes patient trust in connected features.', (0.84, 0.92), (-5_000_000, -2_000_000), 'negative'),
    ('Cold Chain Failure Destroys $8M in Insulin Inventory During Transit', 'Temperature excursion during summer shipping renders entire batch unusable.', (0.85, 0.93), (-4_200_000, -1_600_000), 'negative'),
    ('Key Opinion Leader Publicly Criticizes {{company}} Clinical Data', 'Prominent endocrinologist questions methodology on social media. Physician confidence shaken.', (0.86, 0.94), (-3_500_000, -1_400_000), 'negative'),
    ('Insulin Price Cap Legislation Compresses {{company}} Margins by 20%', 'New state-level pricing regulations limit revenue per patient.', (0.84, 0.92), (-5_000_000, -2_200_000), 'negative'),
    ('{{company}} VP of Commercial Departs for Competitor', 'Senior sales leader takes institutional knowledge and key account relationships.', (0.87, 0.94), (-3_200_000, -1_200_000), 'negative'),
    ('Pharmacy Chain Threatens Delisting Over Supply Inconsistency', 'CVS warns of removal from preferred list if fill rates don\'t improve.', (0.85, 0.93), (-4_200_000, -1_600_000), 'negative'),
    ('FDA Adverse Event Report Links {{company}} Pen to Dosing Errors', 'Safety signal triggers voluntary investigation. Media amplifies concern.', (0.83, 0.92), (-5_200_000, -2_200_000), 'negative'),
    ('Health System Switches to Competitor After Contract Renegotiation Fails', 'Major hospital network defects over pricing dispute. 50K patients affected.', (0.84, 0.92), (-5_000_000, -2_000_000), 'negative'),
    ('API Supplier Raises Prices 30% — Insulin Production Costs Spike', 'Active pharmaceutical ingredient cost increase squeezes gross margins.', (0.86, 0.93), (-3_800_000, -1_500_000), 'negative'),
    ('{{company}} Clinical Trial Fails to Meet Primary Endpoint', 'Phase IV real-world study shows no significant advantage over standard pens.', (0.83, 0.91), (-5_500_000, -2_400_000), 'negative'),
    ('Insurance Prior Authorization Requirements Tighten for Smart Pens', 'New step therapy rules force patients to fail on cheaper options first.', (0.85, 0.93), (-4_500_000, -1_800_000), 'negative'),
    ('FTC Investigation into {{company}} Rebate Practices', 'Federal Trade Commission scrutiny creates uncertainty and legal costs.', (0.86, 0.94), (-3_500_000, -1_400_000), 'negative'),
    ('Counterfeit {{company}} Cartridges Discovered in US Supply Chain', 'Fake insulin cartridges endanger patients and damage brand trust.', (0.83, 0.91), (-5_500_000, -2_400_000), 'negative'),
    ('{{company}} Forced to Issue Voluntary Recall on 200K Pen Devices', 'Mechanical defect in injection mechanism requires device replacement.', (0.82, 0.91), (-6_000_000, -2_800_000), 'negative'),
    ('Medicare Reimbursement Rate Cut for Insulin Delivery Devices', 'CMS rate reduction compresses the highest-margin payer channel.', (0.85, 0.93), (-4_200_000, -1_600_000), 'negative'),
    ('Competitor Publishes Superior Head-to-Head Clinical Results', 'Rival\'s trial data shifts physician preference. Formulary committees take notice.', (0.84, 0.92), (-5_000_000, -2_000_000), 'negative'),
    ('{{company}} Loses Key Patent Challenge in Federal Court', 'Patent invalidation opens door for generic smart pen competitors.', (0.84, 0.92), (-5_000_000, -2_200_000), 'negative'),
    ('Cybersecurity Vulnerability Found in Smart Pen Bluetooth Protocol', 'Security flaw requires emergency firmware update and FDA notification.', (0.86, 0.93), (-3_800_000, -1_500_000), 'negative'),
    ('Rival Launches Direct-to-Consumer Insulin Campaign — Market Share Shifts', 'Competitor\'s aggressive DTC advertising captures patient awareness.', (0.85, 0.93), (-4_200_000, -1_600_000), 'negative'),
    ('{{company}} Warehouse Fire Destroys 3 Months of Safety Stock', 'Distribution center incident creates nationwide supply gap.', (0.83, 0.91), (-5_500_000, -2_400_000), 'negative'),
    ('Negative 60 Minutes Segment on Smart Pen Data Privacy Concerns', 'National TV investigation erodes consumer trust in connected health devices.', (0.85, 0.93), (-4_200_000, -1_800_000), 'negative'),
    ('State Attorney General Sues {{company}} Over Insulin Pricing Practices', 'Legal action in California creates precedent risk and negative press.', (0.86, 0.93), (-3_800_000, -1_500_000), 'negative'),
    ('Key Clinical Advisory Board Member Resigns Over Conflict of Interest', 'Public departure damages scientific credibility.', (0.87, 0.94), (-3_000_000, -1_200_000), 'negative'),
    ('{{company}} Faces Class-Action from Patients Over Pen Malfunction', 'Lawsuit alleges insulin under-delivery caused hypoglycemic episodes.', (0.84, 0.92), (-5_000_000, -2_200_000), 'negative'),
    ('Pharmacy Benefit Redesign Shifts Insulin to Higher Copay Tier', 'Payer restructuring moves {{company}} from Tier 2 to Tier 3. Patient attrition expected.', (0.85, 0.93), (-4_500_000, -1_800_000), 'negative'),
    ('Hurricane Disrupts {{company}} Distribution Hub in Southeast US', 'Natural disaster halts shipments to 8 states for 3 weeks.', (0.85, 0.93), (-4_200_000, -1_600_000), 'negative'),
    ('Competitor Offers Free Smart Pen Upgrade to {{company}} Patients', 'Aggressive switching campaign targets existing {{company}} patient base.', (0.84, 0.92), (-5_000_000, -2_000_000), 'negative'),
    ('{{company}} CFO Resignation Triggers Wall Street Downgrade', 'Executive departure signals internal disagreement on pricing strategy.', (0.86, 0.94), (-3_500_000, -1_400_000), 'negative'),
    ('Insulin Pen Needle Shortage Affects All Smart Pen Manufacturers', 'Global needle supply constraint limits patient starts industry-wide.', (0.86, 0.93), (-3_800_000, -1_500_000), 'negative'),
    ('{{company}} Loses Exclusive Distribution Agreement with Major Wholesaler', 'McKesson ends exclusivity. Competitors gain equal shelf access.', (0.85, 0.93), (-4_200_000, -1_600_000), 'negative'),
    ('Negative JAMA Editorial Questions Smart Pen Cost-Effectiveness', 'Influential medical journal piece dampens physician enthusiasm.', (0.86, 0.94), (-3_500_000, -1_400_000), 'negative'),
    ('Generic Insulin Cartridge Approved — Price Erosion Begins', 'FDA approves interchangeable biosimilar cartridge compatible with {{company}} pen.', (0.83, 0.91), (-5_500_000, -2_400_000), 'negative'),
    ('{{company}} IT Outage Takes Smart Pen Cloud Platform Offline for 48 Hours', 'Service disruption prevents patients from syncing data. Media coverage amplifies.', (0.86, 0.93), (-3_800_000, -1_500_000), 'negative'),
    ('Unexpected Side Effect Reported in Post-Market Surveillance', 'Injection site reactions reported at higher rate than clinical trials showed.', (0.85, 0.93), (-4_500_000, -1_800_000), 'negative'),

    # 20 NEUTRAL
    ('US Insulin Market Grows 12% — But New Entrants Intensify Competition', 'Market expansion offset by biosimilar proliferation and pricing pressure.', (0.96, 1.06), (-1_200_000, 1_800_000), 'neutral'),
    ('{{company}} Undertakes Organizational Restructuring', 'Leadership changes bring commercial focus but introduce execution risk.', (0.94, 1.03), (-1_800_000, 1_200_000), 'neutral'),
    ('FDA Proposes Updated Guidance for Connected Drug Delivery Devices', 'New regulatory framework may benefit or constrain smart pen features.', (0.96, 1.04), (-1_500_000, 1_200_000), 'neutral'),
    ('Industry Conference Debates Smart Pen Interoperability Standards', 'Standardization could reduce costs but limit differentiation.', (0.96, 1.03), (-1_200_000, 1_000_000), 'neutral'),
    ('{{company}} Annual Investor Day — Guidance Maintained', 'No material changes to outlook. Analyst consensus unchanged.', (0.97, 1.03), (-600_000, 900_000), 'neutral'),
    ('Medicare Open Enrollment Period — Patient Switching Expected', 'Annual enrollment creates both opportunity and attrition risk.', (0.96, 1.04), (-1_200_000, 1_200_000), 'neutral'),
    ('Pharmacy Industry Consolidation Continues — Impact Uncertain', 'CVS-Aetna integration changes payer-pharmacy dynamics.', (0.96, 1.03), (-1_000_000, 800_000), 'neutral'),
    ('{{company}} Engages FDA in Pre-Submission Meeting for Next-Gen Device', 'Regulatory engagement signals progress but outcome uncertain.', (0.97, 1.04), (-800_000, 1_200_000), 'neutral'),
    ('Diabetes Patient Population Grows 4% — Demand Steady', 'Prevalence increase creates opportunity but healthcare system strain.', (0.97, 1.04), (-600_000, 1_200_000), 'neutral'),
    ('{{company}} Files 8 New Patents Around Smart Pen Platform', 'IP expansion signals R&D progress. Commercial impact uncertain.', (0.97, 1.03), (-500_000, 1_000_000), 'neutral'),
    ('Competitor Announces Partnership — Market Watches Closely', 'Strategic alliance between two rivals could reshape competitive dynamics.', (0.95, 1.04), (-1_500_000, 1_200_000), 'neutral'),
    ('ADA Updates Diabetes Treatment Guidelines', 'Revised recommendations neither favor nor disadvantage smart pen delivery.', (0.96, 1.04), (-1_000_000, 1_200_000), 'neutral'),
    ('{{company}} Mid-Year Review Shows Mixed Performance Across Regions', 'Strong Northeast uptake offset by slower Southern market penetration.', (0.96, 1.03), (-1_200_000, 1_000_000), 'neutral'),
    ('Health System EHR Integration Pilot Launches — Results Pending', 'Epic/Cerner smart pen data integration could drive or complicate adoption.', (0.97, 1.04), (-800_000, 1_200_000), 'neutral'),
    ('Insulin Pen Market Report Published — {{company}} Rated Mid-Tier', 'Analyst report positions {{company}} as promising but unproven at scale.', (0.96, 1.03), (-1_000_000, 800_000), 'neutral'),
    ('Federal Budget Proposal Includes Insulin Affordability Provisions', 'Bipartisan support for affordability but implementation details unclear.', (0.96, 1.04), (-1_000_000, 1_200_000), 'neutral'),
    ('{{company}} Supply Chain Audit Reveals Mixed Results', 'Some suppliers upgraded, others flagged for redundancy planning.', (0.96, 1.03), (-1_200_000, 800_000), 'neutral'),
    ('Smart Pen Category Awareness Grows — But Adoption Lags Awareness', 'Patients know about connected pens but switching behavior is slow.', (0.97, 1.03), (-600_000, 1_000_000), 'neutral'),
    ('{{company}} Quarterly Earnings Meet Expectations', 'Inline results. No surprises in either direction.', (0.97, 1.03), (-500_000, 600_000), 'neutral'),
    ('Diabetes Technology Society Publishes Smart Pen Best Practices', 'Industry standards document neither benefits nor hinders {{company}} specifically.', (0.97, 1.03), (-600_000, 800_000), 'neutral'),
]


DEPT_NEWS_POOL = [
    ("Global Insulin API Shortage Hits US Manufacturers",
     "Active ingredient supply constrained worldwide. Manufacturers without long-term contracts face 8-week delays.",
     "Operations", 1.40, 0.80, "negative"),
    ("FDA Inspection Finds GMP Deficiencies at Boston Facility",
     "Warning letter requires remediation within 90 days. Production line partially shut down.",
     "Operations", 1.35, 0.75, "negative"),
    ("Cold Chain Equipment Failure at Distribution Center",
     "Refrigeration breakdown destroys $4M in temperature-sensitive inventory.",
     "Operations", 1.30, 0.85, "negative"),
    ("Key Pen Component Supplier Declares Bankruptcy",
     "Injection mechanism supplier fails. Alternative sourcing at 25% cost premium.",
     "Operations", 1.35, 0.80, "negative"),
    ("Cleanroom Contamination Event Halts Production for 3 Weeks",
     "Particulate contamination detected during batch testing. Full decontamination required.",
     "Operations", 1.40, 0.75, "negative"),
    ("Glass Cartridge Supplier Quality Issue — 500K Units Rejected",
     "Incoming QC detects micro-fractures. Entire shipment scrapped.",
     "Operations", 1.25, 0.85, "negative"),
    ("Hurricane Forces 2-Week Shutdown of Distribution Hub",
     "Southeast distribution center evacuated. Shipments to 12 states halted.",
     "Operations", 1.20, 0.80, "negative"),
    ("Needle Supplier Price Increase of 35%",
     "Single-source dependency on pen needle supplier exploited. Margins compressed.",
     "Operations", 1.30, 0.85, "negative"),
    ("Quality Audit Reveals Dosing Calibration Drift in 10K Devices",
     "Internal QA catches issue before patient impact. Rework and recalibration required.",
     "Operations", 1.25, 0.80, "negative"),
    ("Semiconductor Shortage Affects Smart Pen Electronics",
     "Bluetooth chip allocation cut by 40%. Device production constrained.",
     "Operations", 1.35, 0.80, "negative"),
    # Operations positive
    ("New Automated Fill-Finish Line Doubles Cartridge Capacity",
     "State-of-the-art aseptic filling technology at Boston facility fully operational.",
     "Operations", 0.80, 1.20, "positive"),
    ("Long-Term API Supply Contract Locks in Below-Market Pricing",
     "Five-year insulin API agreement hedges against commodity volatility.",
     "Operations", 0.80, 1.15, "positive"),
    ("FDA Grants {{company}} Facility Exemplary Compliance Status",
     "Perfect inspection record unlocks expedited batch release.",
     "Operations", 0.85, 1.15, "positive"),
    ("Smart Pen Assembly Line Achieves Six Sigma Quality",
     "Defect rate drops to 3.4 per million. Warranty claims fall 60%.",
     "Operations", 0.75, 1.25, "positive"),
    ("Cold Chain Innovation Extends Insulin Shelf Life by 40%",
     "New stabilization technology reduces waste and simplifies distribution.",
     "Operations", 0.80, 1.20, "positive"),
    ("Second Manufacturing Site Opens — Supply Redundancy Achieved",
     "New facility in Research Triangle Park eliminates single-site risk.",
     "Operations", 0.75, 1.25, "positive"),
    ("Vertical Integration: In-House Pen Needle Manufacturing Launches",
     "Bringing needle production in-house reduces cost by 30% and eliminates supplier dependency.",
     "Operations", 0.80, 1.20, "positive"),
    ("AI-Powered Predictive Maintenance Cuts Downtime by 50%",
     "Machine learning system anticipates equipment failures before they occur.",
     "Operations", 0.85, 1.15, "positive"),
    ("Strategic Safety Stock Program Fully Funded",
     "6-month inventory buffer protects against supply chain disruptions.",
     "Operations", 0.85, 1.15, "positive"),
    ("Packaging Redesign Reduces Material Cost 20% and Improves Recyclability",
     "Sustainable packaging initiative delivers both cost savings and ESG benefits.",
     "Operations", 0.85, 1.15, "positive"),
    # Operations neutral
    ("Industry-Wide Shift to Pre-Filled Cartridges — Retooling Required",
     "Market trend toward pre-filled format requires line modification investment.",
     "Operations", 1.10, 0.95, "neutral"),
    ("Annual GMP Inspection Scheduled — Preparation Underway",
     "Routine FDA inspection expected. No concerns but resources diverted to preparation.",
     "Operations", 1.05, 0.98, "neutral"),
    ("Pen Component Supplier Acquired by Competitor",
     "No immediate disruption but long-term supply terms under review.",
     "Operations", 1.10, 0.95, "neutral"),
    ("New EPA Regulations on Pharmaceutical Waste Disposal",
     "Compliance straightforward but adds $200K annually to operating costs.",
     "Operations", 1.08, 0.97, "neutral"),
    ("Facility Smart Grid Upgrade Requires Weekend Shutdowns",
     "Electrical modernization program runs 6 weekends. Minimal production impact.",
     "Operations", 1.05, 0.98, "neutral"),

    ("Rival Files Patent Blocking Key Smart Pen Feature",
     "Competitor secures broad patent on dose-tracking algorithm. Redesign or license required.",
     "R&D", 1.45, 0.80, "negative"),
    ("Phase IV Trial Fails to Demonstrate Real-World Superiority",
     "Post-market study shows no significant HbA1c improvement over standard pens.",
     "R&D", 1.35, 0.85, "negative"),
    ("Software Vulnerability in Smart Pen Firmware Requires Emergency Patch",
     "Security flaw diverts engineering resources from feature roadmap.",
     "R&D", 1.30, 0.90, "negative"),
    ("Chief Scientific Officer Departs for Competitor",
     "Lead clinical researcher joins rival with institutional knowledge.",
     "R&D", 1.35, 0.85, "negative"),
    ("CGM Integration Partner Pulls Out of Joint Development",
     "Glucose monitor company pivots strategy. Smart pen ecosystem plan disrupted.",
     "R&D", 1.40, 0.80, "negative"),
    ("FDA Requests Additional Clinical Data for Label Expansion",
     "Regulatory feedback requires 12-month extension of ongoing trial.",
     "R&D", 1.25, 0.85, "negative"),
    ("Insulin Stability Issue Discovered in New Cartridge Formulation",
     "Accelerated aging study shows degradation. Reformulation required.",
     "R&D", 1.30, 0.85, "negative"),
    ("Academic Collaborator Retracts Published Study Supporting {{company}} Claims",
     "Data integrity questions force retraction of supportive clinical evidence.",
     "R&D", 1.35, 0.80, "negative"),
    ("Smart Pen Bluetooth Protocol Incompatible with New iPhone OS",
     "Apple iOS update breaks connectivity. 60% of users affected until fix deployed.",
     "R&D", 1.25, 0.85, "negative"),
    ("Key R&D Engineer Recruited Away by Big Tech Health Division",
     "Google Health offer lures top firmware engineer. 6-month knowledge gap.",
     "R&D", 1.30, 0.85, "negative"),
    # R&D positive
    ("Breakthrough: Next-Gen Smart Pen Achieves 99.8% Dose Accuracy",
     "Internal testing shows class-leading precision. FDA filing accelerated.",
     "R&D", 0.85, 1.25, "positive"),
    ("CGM Integration Prototype Passes Validation — Closed-Loop Ready",
     "Glucose monitor data now drives automated dose suggestions on pen display.",
     "R&D", 0.80, 1.20, "positive"),
    ("Published Trial Shows 28% Reduction in Hypoglycemic Events",
     "Peer-reviewed safety data transforms physician prescribing confidence.",
     "R&D", 0.75, 1.25, "positive"),
    ("NIH Awards $8M Research Grant for Connected Insulin Delivery",
     "Federal funding accelerates next-generation pen platform development.",
     "R&D", 0.80, 1.20, "positive"),
    ("AI Dose Optimization Algorithm Passes FDA Software Validation",
     "Machine learning feature cleared for clinical use. Industry first.",
     "R&D", 0.80, 1.25, "positive"),
    ("Patent Portfolio Reaches 80 Granted Claims — Strongest in Category",
     "IP moat prevents fast-follower imitation of key smart pen features.",
     "R&D", 0.85, 1.20, "positive"),
    ("Strategic Hire: Former Medtronic VP Joins as Head of Device Engineering",
     "Medical device veteran brings insulin pump expertise to pen platform.",
     "R&D", 0.80, 1.20, "positive"),
    ("Room-Temperature Stable Insulin Formulation Achieves 30-Day Stability",
     "Eliminates cold chain requirement for patients. Transformative convenience.",
     "R&D", 0.80, 1.25, "positive"),
    ("Partnership with MIT Signed for Next-Gen Microneedle Research",
     "Academic collaboration targets painless injection technology.",
     "R&D", 0.85, 1.15, "positive"),
    ("OTA Firmware Update Adds 5 New Languages — Global Readiness Improved",
     "Multilingual pen interface expands addressable patient population.",
     "R&D", 0.85, 1.15, "positive"),
    # R&D neutral
    ("FDA Issues Updated Guidance for AI-Enabled Medical Devices",
     "New regulatory framework clarifies pathway but adds documentation burden.",
     "R&D", 1.08, 0.97, "neutral"),
    ("Industry Consortium Proposes Smart Pen Data Interoperability Standard",
     "Standardization could reduce development costs but limit proprietary features.",
     "R&D", 1.05, 0.98, "neutral"),
    ("Chief Technology Officer Announces Planned Retirement",
     "Orderly succession. New CTO brings fresh perspective with some transition risk.",
     "R&D", 1.08, 0.96, "neutral"),
    ("Academic Paper Questions Long-Term Accuracy of Connected Pen Sensors",
     "Peer-reviewed study creates discussion but limited near-term commercial impact.",
     "R&D", 1.05, 0.98, "neutral"),
    ("R&D Budget Reallocation Between Device and Software Programs",
     "Internal review shifts resources from hardware to digital health features.",
     "R&D", 1.05, 0.98, "neutral"),

    ("Competitor Launches Aggressive Rebate Campaign to PBMs",
     "Major rival offers 60% rebates to pharmacy benefit managers. Formulary positions at risk.",
     "Sales", 1.40, 0.80, "negative"),
    ("Key Hospital System Switches to Competitor After Formulary Review",
     "Annual P&T committee selects lower-cost alternative. 30K patients affected.",
     "Sales", 1.30, 0.85, "negative"),
    ("Regional Sales Director Exodus — 4 Territories Uncovered",
     "Compensation dispute triggers departures. Southeast and Midwest coverage gaps.",
     "Sales", 1.35, 0.80, "negative"),
    ("Insurance Prior Authorization Burden Increases for Smart Pens",
     "New step therapy requirements add 3-week delay to patient access.",
     "Sales", 1.30, 0.85, "negative"),
    ("Major Employer Health Plan Drops {{company}} Coverage",
     "Fortune 500 company switches to competitor for 150K covered employees.",
     "Sales", 1.25, 0.80, "negative"),
    ("Endocrinologist Survey Shows Declining Interest in Connected Pens",
     "Physician fatigue with digital health tools dampens prescribing enthusiasm.",
     "Sales", 1.25, 0.85, "negative"),
    ("Competitor Offers Free 90-Day Trial to {{company}} Patients",
     "Aggressive switching campaign targets existing patient base.",
     "Sales", 1.30, 0.85, "negative"),
    ("Pharmacy Chain Reduces {{company}} Shelf Placement",
     "Walgreens demotes {{company}} to secondary position behind competitor.",
     "Sales", 1.25, 0.80, "negative"),
    ("State Medicaid Program Removes {{company}} from Preferred List",
     "California Medi-Cal formulary decision cuts access to 4M patients.",
     "Sales", 1.30, 0.85, "negative"),
    ("Competitor Publishes Cost-Effectiveness Study Favoring Their Product",
     "Health economics data shifts payer and physician preference.",
     "Sales", 1.35, 0.80, "negative"),
    # Sales positive
    ("Three Major PBMs Add {{company}} to Preferred Tier Simultaneously",
     "Coordinated formulary wins unlock access to 80M+ covered lives.",
     "Sales", 0.80, 1.25, "positive"),
    ("{{company}} Endocrinology Sales Team Wins Industry Excellence Award",
     "Top-performing sales organization recognized by Medical Marketing Association.",
     "Sales", 0.85, 1.15, "positive"),
    ("Integrated Health System Contract Signed — 200K Patient Lives",
     "Kaiser Permanente-scale deal locks in 3-year volume commitment.",
     "Sales", 0.80, 1.25, "positive"),
    ("Patient Hub Program Drives 85% Refill Rate — Industry Best",
     "Patient support services create exceptional retention and lifetime value.",
     "Sales", 0.85, 1.20, "positive"),
    ("Specialty Pharmacy Partnership Expands to All 50 States",
     "National distribution through specialty channel ensures patient access anywhere.",
     "Sales", 0.80, 1.20, "positive"),
    ("Federal Employee Health Benefit Program Adds {{company}}",
     "FEHBP listing covers 8M federal workers and dependents.",
     "Sales", 0.80, 1.25, "positive"),
    ("{{company}} Field Medical Team Cited as Most Responsive by Physicians",
     "Physician satisfaction with medical science liaison team at all-time high.",
     "Sales", 0.85, 1.15, "positive"),
    ("Record Q3: 15,000 New Patients Enrolled in Single Quarter",
     "Commercial momentum accelerates beyond internal forecasts.",
     "Sales", 0.85, 1.20, "positive"),
    ("Pharmacy Benefit Redesign Moves {{company}} to Tier 1 at Major Payer",
     "Lowest copay tier drives patient preference and new starts.",
     "Sales", 0.80, 1.20, "positive"),
    ("Health System IDN Selects {{company}} for Standardized Insulin Protocol",
     "Integrated delivery network mandates {{company}} as default insulin pen.",
     "Sales", 0.80, 1.25, "positive"),
    # Sales neutral
    ("Annual Formulary Review Season Begins at Major PBMs",
     "Routine review cycle creates both opportunity and risk. Outcome uncertain.",
     "Sales", 1.05, 0.98, "neutral"),
    ("CMS Proposes Insulin Reimbursement Rate Adjustment",
     "Proposed rate change has unclear net impact on smart pen economics.",
     "Sales", 1.05, 0.97, "neutral"),
    ("Hospital Group Contract Coming Up for Renewal",
     "Competitive rebid process. Retention likely but not guaranteed.",
     "Sales", 1.08, 0.96, "neutral"),
    ("Competitor Launches Patient Loyalty Program",
     "New retention tactic creates uncertainty about switching behavior.",
     "Sales", 1.05, 0.98, "neutral"),
    ("Specialty Pharmacy Merger Creates New Distribution Dynamics",
     "Channel consolidation offers both efficiency gains and negotiation risk.",
     "Sales", 1.05, 0.97, "neutral"),

    ("Viral Social Media Backlash Over Insulin Pricing Perception",
     "Patient advocacy group targets {{company}} in viral pricing campaign despite fair pricing.",
     "Marketing", 1.45, 0.75, "negative"),
    ("Competitor's Super Bowl DTC Ad Captures National Attention",
     "Rival's direct-to-consumer campaign dominates patient awareness. Share of voice drops.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Key Opinion Leader Switches Endorsement to Competitor",
     "Prominent endocrinologist becomes public advocate for rival product.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Patient Community Backlash Over Data Privacy Concerns",
     "Connected pen data collection practices questioned by patient advocacy groups.",
     "Marketing", 1.40, 0.80, "negative"),
    ("Digital Ad Platform Algorithm Change Doubles Patient Acquisition Cost",
     "Meta targeting restrictions for health products spike cost per patient inquiry.",
     "Marketing", 1.35, 0.85, "negative"),
    ("Medical Conference Exhibit Receives Poor Traffic Due to Location",
     "ADA conference booth placement in low-traffic area. Lead generation disappoints.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Brand Perception Study Shows Declining Trust Among Physicians",
     "Annual brand tracker reveals erosion in physician confidence metrics.",
     "Marketing", 1.30, 0.80, "negative"),
    ("Patient Testimonial Campaign Backfires on Social Media",
     "Sponsored patient story perceived as inauthentic. Online backlash ensues.",
     "Marketing", 1.25, 0.85, "negative"),
    ("Competitor Launches Head-to-Head DTC Comparison Campaign",
     "Direct attack advertising challenges {{company}} claims publicly.",
     "Marketing", 1.35, 0.80, "negative"),
    ("HIPAA Violation in Marketing Materials Triggers Investigation",
     "Protected health information inadvertently used in case study. Regulatory review.",
     "Marketing", 1.30, 0.80, "negative"),
    # Marketing positive
    ("{{company}} Wins Best Patient Education Campaign — DTC Awards",
     "Creative excellence recognition generates industry press and patient awareness.",
     "Marketing", 0.85, 1.20, "positive"),
    ("Patient Ambassador Program Reaches 10,000 Active Advocates",
     "Peer-to-peer patient community creates authentic awareness at scale.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Prime-Time TV DTC Campaign Drives Record Website Traffic",
     "Direct-to-consumer advertising generates 500K patient inquiries in first month.",
     "Marketing", 0.80, 1.25, "positive"),
    ("Celebrity Diabetes Diagnosis Creates Awareness — {{company}} Benefits",
     "High-profile public figure's diagnosis creates national diabetes conversation.",
     "Marketing", 0.80, 1.20, "positive"),
    ("ADA Conference Booth Wins Best Exhibit — 5,000 Physician Visits",
     "Interactive smart pen demonstration creates buzz among endocrinologists.",
     "Marketing", 0.85, 1.20, "positive"),
    ("{{company}} Diabetes Management App Wins Apple Design Award",
     "Tech industry recognition drives consumer awareness beyond traditional pharma.",
     "Marketing", 0.85, 1.15, "positive"),
    ("Patient NPS Reaches 72 — Highest in Insulin Delivery Category",
     "Net promoter score drives physician referrals and word-of-mouth.",
     "Marketing", 0.80, 1.20, "positive"),
    ("Partnership with American Diabetes Association for National Campaign",
     "Co-branded awareness initiative reaches 20M Americans during Diabetes Awareness Month.",
     "Marketing", 0.85, 1.15, "positive"),
    ("{{company}} Named Most Trusted Diabetes Brand by Patient Survey",
     "Consumer trust award generates media coverage and physician confidence.",
     "Marketing", 0.85, 1.20, "positive"),
    ("First-Party Data Platform Reduces Patient Acquisition Cost by 35%",
     "In-house analytics improve targeting efficiency across all channels.",
     "Marketing", 0.85, 1.15, "positive"),
    # Marketing neutral
    ("FDA Updates DTC Advertising Guidelines for Digital Platforms",
     "New rules clarify social media requirements. Compliance adjustments needed.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Annual Brand Health Tracker Shows Stable Awareness",
     "Awareness holding but not growing. Current approach sustaining position.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Medical Conference Calendar Shift Affects Event Planning",
     "Major conferences rescheduled. Marketing program timing adjustments required.",
     "Marketing", 1.08, 0.96, "neutral"),
    ("Social Media Platform Algorithm Change Affects Health Content",
     "Organic reach for medical content reduced. Paid strategy adjustment needed.",
     "Marketing", 1.05, 0.98, "neutral"),
    ("Competitor Exits Key Physician Education Sponsorship",
     "Conference sponsorship available at short notice. High cost, high visibility.",
     "Marketing", 1.05, 0.97, "neutral"),
]


GENERAL_NEWS_POOL = [
    # 40 POSITIVE
    ("Inflation Reduction Act Caps Insulin Copays — Market Expands",
     "Federal $35 copay cap removes affordability barrier for millions of diabetic patients.",
     (1.06, 1.14), (1_200_000, 3_600_000), "positive"),
    ("CDC Reports Diabetes Prevalence Rising — Demand for Insulin Grows",
     "37M Americans with diabetes. New diagnoses accelerating demand for all insulin products.",
     (1.04, 1.10), (800_000, 2_400_000), "positive"),
    ("CMS Expands Medicare Coverage for Connected Health Devices",
     "Reimbursement pathway for smart insulin delivery widens addressable market.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Major Health System Mandates Connected Insulin Delivery as Standard of Care",
     "Cleveland Clinic protocol change creates precedent for other health systems.",
     (1.06, 1.14), (1_200_000, 3_600_000), "positive"),
    ("Insulin API Costs Fall 15% as Global Production Capacity Expands",
     "New API manufacturing plants in India and China reduce input costs for all producers.",
     (1.03, 1.08), (800_000, 2_400_000), "positive"),
    ("ADA Updates Treatment Guidelines to Recommend Connected Delivery",
     "Professional society endorsement creates tailwind for entire smart pen category.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Record Year for Biosimilar Insulin Adoption in US",
     "Biosimilar market share crosses 30% of total insulin market. Stigma fading.",
     (1.04, 1.10), (800_000, 2_400_000), "positive"),
    ("Federal Funding Allocated for Diabetes Technology Innovation",
     "NIH budget increase includes $200M for connected diabetes management research.",
     (1.04, 1.10), (600_000, 2_000_000), "positive"),
    ("Glycon Therapeutics Named Top Healthcare Startup by Forbes",
     "Media recognition drives investor confidence and talent acquisition pipeline.",
     (1.03, 1.08), (500_000, 1_800_000), "positive"),
    ("Employer Health Plans Increasingly Cover Smart Pens Without Prior Auth",
     "Trend toward frictionless access accelerates patient adoption.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Glycon Therapeutics J.D. Power Score Hits Category High",
     "Patient satisfaction drives referral rates and physician confidence.",
     (1.04, 1.09), (800_000, 2_400_000), "positive"),
    ("Telemedicine Integration Expands Smart Pen Prescribing Reach",
     "Virtual care platforms enable remote prescribing for connected insulin delivery.",
     (1.04, 1.10), (800_000, 2_400_000), "positive"),
    ("Glycon Therapeutics Production Record — 15K Patient Kits in Quarter",
     "Record manufacturing output demonstrates supply chain maturity.",
     (1.04, 1.10), (800_000, 2_400_000), "positive"),
    ("Insurance Industry Report Shows Smart Pens Reduce Total Healthcare Costs",
     "Actuarial data demonstrates 18% reduction in diabetes-related ER visits.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("State-Level Insulin Affordability Laws Pass in 8 Additional States",
     "Legislative momentum improves patient access and market certainty.",
     (1.04, 1.10), (800_000, 2_400_000), "positive"),
    ("Competitor Exits Insulin Market — Share Available",
     "Major pharmaceutical company de-prioritizes insulin to focus on GLP-1 drugs.",
     (1.06, 1.14), (1_200_000, 3_600_000), "positive"),
    ("Digital Health Reimbursement Codes Approved for Smart Pen Monitoring",
     "CPT code creation allows physician billing for connected pen data review.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Glycon Therapeutics Investor Day — Analysts Upgrade Outlook",
     "Strong pipeline presentation drives three analyst upgrades to Buy.",
     (1.04, 1.09), (600_000, 2_000_000), "positive"),
    ("Pharmacy Chains Expand Dedicated Smart Pen Displays",
     "Retail visibility for connected insulin delivery improves nationwide.",
     (1.03, 1.08), (500_000, 1_800_000), "positive"),
    ("Glycon Therapeutics OTA Update Adds Meal Logging Feature",
     "Software enhancement increases daily patient engagement by 30%.",
     (1.04, 1.09), (700_000, 2_200_000), "positive"),
    ("VA Health System Expands Smart Pen Program to All Facilities",
     "Veterans Affairs nationwide rollout creates significant volume pipeline.",
     (1.06, 1.14), (1_200_000, 3_600_000), "positive"),
    ("Major Academic Medical Center Publishes Favorable Real-World Evidence",
     "Johns Hopkins study validates smart pen outcomes in diverse patient population.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Insulin Pen Needle Innovation Reduces Injection Pain by 40%",
     "New needle technology improves patient experience across all pen platforms.",
     (1.03, 1.08), (500_000, 1_800_000), "positive"),
    ("Patient Advocacy Groups Launch National Smart Pen Awareness Campaign",
     "Grassroots awareness initiative drives patient demand for connected delivery.",
     (1.04, 1.10), (800_000, 2_400_000), "positive"),
    ("Health Insurance Premium Discounts Offered for Smart Pen Users",
     "Outcome-based insurance incentives drive enrollment.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Glycon Therapeutics Selected for National Quality Forum Pilot",
     "Quality improvement initiative validates smart pen as care improvement tool.",
     (1.04, 1.09), (600_000, 2_000_000), "positive"),
    ("Endocrinology Fellowship Programs Add Smart Pen Training",
     "Next-generation physicians trained on connected insulin delivery from residency.",
     (1.03, 1.08), (400_000, 1_500_000), "positive"),
    ("Glycon Therapeutics Zero-Cost Patient Assistance Enrolls 50K Patients",
     "Copay assistance program drives adoption among cost-sensitive patients.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Used Smart Pen Refurbishment Program Creates Sustainability Story",
     "Device recycling initiative generates positive media coverage.",
     (1.03, 1.07), (300_000, 1_200_000), "positive"),
    ("Diabetes Technology Conference Highlights Smart Pen Innovation",
     "ATTD conference presentations generate buzz among global diabetes community.",
     (1.04, 1.09), (600_000, 2_000_000), "positive"),
    ("Glycon Therapeutics App Store Rating Reaches 4.8 Stars",
     "Patient app satisfaction drives organic referrals.",
     (1.03, 1.08), (400_000, 1_500_000), "positive"),
    ("Federal Budget Includes $500M for Diabetes Prevention Programs",
     "Government spending creates downstream demand for diabetes management tools.",
     (1.04, 1.10), (800_000, 2_400_000), "positive"),
    ("New Study Shows Connected Pens Improve Medication Adherence by 25%",
     "Adherence data strengthens the value proposition for payers.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Glycon Therapeutics Selected as Innovation Partner by Major Health System",
     "Strategic partnership with large IDN drives protocol-based adoption.",
     (1.06, 1.13), (1_000_000, 3_000_000), "positive"),
    ("Retail Pharmacy Chains Report Growing Patient Demand for Smart Pens",
     "Pull-through demand validates DTC and physician marketing investment.",
     (1.04, 1.09), (700_000, 2_200_000), "positive"),
    ("Glycon Therapeutics Named to Fast Company Most Innovative List",
     "Business media recognition drives brand awareness beyond healthcare.",
     (1.03, 1.08), (400_000, 1_500_000), "positive"),
    ("Continuous Glucose Monitor Compatibility Expands to 3 Major Brands",
     "Broader CGM interoperability increases smart pen value proposition.",
     (1.05, 1.12), (1_000_000, 3_000_000), "positive"),
    ("Glycon Therapeutics Clinical Advisory Board Strengthens with 5 New KOLs",
     "Elite physician panel bolsters scientific credibility.",
     (1.03, 1.08), (400_000, 1_500_000), "positive"),
    ("National Diabetes Screening Initiative Identifies 2M Undiagnosed Patients",
     "Expanded diagnosis drives downstream demand for insulin therapy.",
     (1.04, 1.10), (800_000, 2_400_000), "positive"),
    ("Glycon Therapeutics Wins Sustainability Award for Eco-Friendly Packaging",
     "ESG recognition builds brand goodwill among environmentally conscious patients.",
     (1.03, 1.07), (300_000, 1_200_000), "positive"),

    # 40 NEGATIVE
    ("Congressional Hearing Targets Insulin Pricing — Industry Under Fire",
     "Bipartisan political pressure on insulin manufacturers creates pricing uncertainty.",
     (0.86, 0.93), (-3_600_000, -1_500_000), "negative"),
    ("GLP-1 Drug Popularity Reduces Insulin-Dependent Patient Population",
     "Ozempic/Wegovy success reduces the number of patients progressing to insulin therapy.",
     (0.85, 0.93), (-4_200_000, -1_800_000), "negative"),
    ("FDA Issues Industry-Wide Warning on Connected Device Cybersecurity",
     "Regulatory scrutiny of connected health devices creates compliance burden.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Major PBM Restructures Formulary — Smart Pens Moved to Higher Tier",
     "Payer cost-cutting shifts connected pens to less favorable reimbursement position.",
     (0.85, 0.93), (-4_000_000, -1_600_000), "negative"),
    ("Insulin API Supplier Faces FDA Import Ban — Industry Supply Disrupted",
     "Key active ingredient supplier blocked from US market. Prices spike.",
     (0.86, 0.93), (-3_600_000, -1_500_000), "negative"),
    ("Glycon Therapeutics Recalls 50K Pen Devices Over Mechanism Defect",
     "Voluntary recall disrupts patient trust and commercial momentum.",
     (0.84, 0.92), (-4_500_000, -2_000_000), "negative"),
    ("Major Health Insurer Removes Smart Pen Coverage Entirely",
     "UnitedHealthcare drops connected pen category. 20M lives affected.",
     (0.84, 0.92), (-4_500_000, -2_000_000), "negative"),
    ("Patent Cliff Approaching — Generic Smart Pen Competitors Emerge",
     "Key patents expiring within 18 months. Generic manufacturers file applications.",
     (0.86, 0.93), (-3_600_000, -1_500_000), "negative"),
    ("Negative 60 Minutes Investigation on Insulin Industry Pricing",
     "National TV segment creates public outrage and political pressure.",
     (0.85, 0.93), (-4_000_000, -1_800_000), "negative"),
    ("Competitor Launches Biosimilar at 70% Discount to {{company}}",
     "Aggressive pricing undercut threatens market share in price-sensitive segments.",
     (0.83, 0.91), (-5_000_000, -2_200_000), "negative"),
    ("Patient Data Breach at Connected Health Platform — Industry Fallout",
     "Healthcare data breach at another company dampens enthusiasm for connected devices.",
     (0.86, 0.93), (-3_500_000, -1_400_000), "negative"),
    ("Hurricane Season Disrupts Pharmaceutical Distribution Across Southeast",
     "Multiple storms create logistics challenges for temperature-sensitive products.",
     (0.87, 0.94), (-3_000_000, -1_200_000), "negative"),
    ("Medicare Reimbursement Rate Cut for Insulin Delivery Devices",
     "CMS rate reduction compresses margins in the largest payer channel.",
     (0.85, 0.93), (-4_000_000, -1_600_000), "negative"),
    ("Glycon Therapeutics CFO Departs Unexpectedly",
     "Executive departure triggers analyst concern and stock decline.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Insulin Pen Needle Shortage Affects Industry",
     "Global needle supply constraint limits new patient starts.",
     (0.87, 0.94), (-3_000_000, -1_200_000), "negative"),
    ("State Attorney General Coalition Investigates Insulin Pricing",
     "Multi-state investigation creates legal uncertainty.",
     (0.86, 0.93), (-3_500_000, -1_400_000), "negative"),
    ("Glycon Therapeutics Product Liability Settlement — $12M",
     "Dosing error lawsuit settled. Sets precedent for future claims.",
     (0.86, 0.93), (-3_800_000, -1_500_000), "negative"),
    ("Competitor Files Patent Challenge Against Smart Pen Technology",
     "Inter partes review threatens key device patents.",
     (0.86, 0.94), (-3_200_000, -1_400_000), "negative"),
    ("Pharmacy Consolidation Reduces Negotiating Leverage for Manufacturers",
     "Fewer pharmacy chains means less competitive bidding for shelf space.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Glycon Therapeutics Faces SEC Inquiry Over Revenue Recognition",
     "Regulatory inquiry creates uncertainty. No wrongdoing alleged.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Rising Interest Rates Increase {{company}} Borrowing Costs",
     "Higher cost of capital constrains growth investment.",
     (0.88, 0.95), (-2_200_000, -900_000), "negative"),
    ("Insulin Market Price War Erupts Among Biosimilar Manufacturers",
     "Multiple competitors slash prices. Industry margins compressed.",
     (0.85, 0.93), (-4_200_000, -1_800_000), "negative"),
    ("FDA Delays Smart Pen Feature Approval Pending Additional Review",
     "Regulatory timeline slip pushes key feature launch by 6 months.",
     (0.86, 0.93), (-3_500_000, -1_400_000), "negative"),
    ("Negative JAMA Editorial Questions Value of Connected Insulin Delivery",
     "Influential journal piece dampens physician enthusiasm.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Glycon Therapeutics IT Outage Disrupts Patient App for 72 Hours",
     "Cloud platform failure prevents data syncing. Patient frustration.",
     (0.87, 0.94), (-3_000_000, -1_200_000), "negative"),
    ("Counterfeit Insulin Cartridges Discovered in US Distribution",
     "Fake product creates patient safety concern and regulatory scrutiny.",
     (0.85, 0.93), (-4_000_000, -1_800_000), "negative"),
    ("Healthcare Worker Shortage Limits Diabetes Clinic Capacity",
     "Endocrinologist shortage constrains patient access to specialist care.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Glycon Therapeutics Warehouse Damage from Severe Weather",
     "Tornado damages Midwest distribution center. 4-week supply disruption.",
     (0.86, 0.93), (-3_500_000, -1_500_000), "negative"),
    ("Patient Advocacy Group Launches Campaign Against Smart Pen Pricing",
     "Grassroots pricing activism creates negative media cycle.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Health System Consolidation Reduces Number of Formulary Decision-Makers",
     "Fewer buying decisions means losing one account has larger impact.",
     (0.87, 0.94), (-3_000_000, -1_200_000), "negative"),
    ("Competitor Wins Exclusive VA Health System Contract",
     "Veterans Affairs locks in rival for 3 years. Major volume loss.",
     (0.84, 0.92), (-4_500_000, -2_000_000), "negative"),
    ("Insulin Storage Recall After Potency Degradation Discovered",
     "Temperature stability issue forces market withdrawal of affected lots.",
     (0.85, 0.93), (-4_000_000, -1_800_000), "negative"),
    ("FDA Tightens Post-Market Surveillance Requirements for Connected Devices",
     "Additional reporting burden increases compliance costs.",
     (0.88, 0.95), (-2_200_000, -900_000), "negative"),
    ("Glycon Therapeutics Loses Key Patent in Federal Court",
     "Patent invalidation opens competitive moat to generics.",
     (0.85, 0.93), (-4_200_000, -1_800_000), "negative"),
    ("National Pharmacist Association Questions Smart Pen Complexity",
     "Pharmacist concerns about patient training create prescribing friction.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Competitor Launches Aggressive Hospital Switching Campaign",
     "Rival offers free 6-month supply to health systems switching from {{company}}.",
     (0.84, 0.92), (-4_500_000, -2_000_000), "negative"),
    ("US Dollar Strengthens — Export Revenue Reduced",
     "Strong dollar reduces the value of international licensing income.",
     (0.88, 0.95), (-2_000_000, -800_000), "negative"),
    ("Glycon Therapeutics Credit Rating Downgraded",
     "Moody's cites cash burn and competitive pressure. Borrowing costs rise.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),
    ("Diabetes Awareness Fatigue — Public Interest Declining",
     "Media attention shifts to other health concerns. Awareness campaigns less effective.",
     (0.88, 0.95), (-2_000_000, -800_000), "negative"),
    ("Glycon Therapeutics Board Dispute Over Growth vs Profitability Strategy",
     "Internal strategic disagreement leaks to press. Investor uncertainty.",
     (0.87, 0.94), (-2_800_000, -1_200_000), "negative"),

    # 20 NEUTRAL
    ("US Insulin Market Grows 8% — But Competition Intensifies",
     "Market expansion offset by biosimilar proliferation and pricing pressure.",
     (0.96, 1.06), (-1_200_000, 1_800_000), "neutral"),
    ("FDA Proposes Updated Guidance for Connected Medical Devices",
     "New framework could clarify or complicate smart pen regulatory pathway.",
     (0.96, 1.03), (-1_500_000, 1_000_000), "neutral"),
    ("Diabetes Technology Conference — Mixed Reviews for Smart Pen Category",
     "Enthusiasm for connected delivery tempered by cost-effectiveness questions.",
     (0.96, 1.04), (-1_200_000, 1_200_000), "neutral"),
    ("Healthcare Reform Debate Continues — Insulin Provisions Uncertain",
     "Political uncertainty around drug pricing policy. Impact unclear.",
     (0.96, 1.03), (-1_500_000, 1_000_000), "neutral"),
    ("Glycon Therapeutics Annual Report — Performance Meets Expectations",
     "No material surprises. Analyst consensus unchanged.",
     (0.97, 1.03), (-600_000, 800_000), "neutral"),
    ("Industry Study Shows Slow Adoption of Connected Health Tools by Physicians",
     "Digital health enthusiasm growing but physician behavior change is gradual.",
     (0.96, 1.03), (-1_200_000, 800_000), "neutral"),
    ("Pharmacy Benefit Manager Merger Creates New Market Dynamics",
     "PBM consolidation changes negotiating landscape. Net impact uncertain.",
     (0.96, 1.04), (-1_200_000, 1_200_000), "neutral"),
    ("Diabetes Patient Demographics Shifting — Younger Onset Increasing",
     "Type 2 diabetes diagnosed earlier. Changes target patient profile.",
     (0.97, 1.04), (-600_000, 1_200_000), "neutral"),
    ("Glycon Therapeutics Patent Portfolio Review — Mixed Assessment",
     "Some patents strengthened, others face challenge. Net position stable.",
     (0.97, 1.03), (-800_000, 800_000), "neutral"),
    ("Health System EHR Integration Standards Evolving",
     "Electronic health record compatibility requirements changing. Adaptation needed.",
     (0.96, 1.03), (-1_000_000, 800_000), "neutral"),
    ("Competitor Announces Strategic Review of Insulin Business",
     "Potential divestiture could create opportunity or stronger focused rival.",
     (0.95, 1.05), (-1_500_000, 1_500_000), "neutral"),
    ("Annual Diabetes Prevalence Report — Steady Growth in Diagnosed Population",
     "Incremental market growth continues. No acceleration or deceleration.",
     (0.97, 1.04), (-600_000, 1_000_000), "neutral"),
    ("Smart Pen Interoperability Standards Under Discussion",
     "Industry working group debates common data formats. Outcome uncertain.",
     (0.97, 1.03), (-800_000, 800_000), "neutral"),
    ("Glycon Therapeutics Mid-Year Guidance — Unchanged",
     "Management reaffirms full-year outlook. No material updates.",
     (0.97, 1.03), (-500_000, 600_000), "neutral"),
    ("Healthcare Staffing Trends — Endocrinologist Supply Stable",
     "Specialty physician workforce neither growing nor declining meaningfully.",
     (0.97, 1.03), (-500_000, 600_000), "neutral"),
    ("Insulin Delivery Market Report — Category Growing at 10% CAGR",
     "Market growth steady. {{company}} positioned in line with category.",
     (0.97, 1.04), (-600_000, 1_000_000), "neutral"),
    ("Federal Budget Negotiations — Healthcare Spending Flat",
     "No major increases or cuts to diabetes-related programs expected.",
     (0.97, 1.03), (-600_000, 600_000), "neutral"),
    ("Glycon Therapeutics Supply Chain Audit — Adequate Performance",
     "No critical findings. Some improvement recommendations noted.",
     (0.97, 1.03), (-800_000, 600_000), "neutral"),
    ("Smart Pen Category Awareness Growing But Adoption Lags",
     "Patient awareness high but switching from traditional pens is gradual.",
     (0.97, 1.03), (-600_000, 800_000), "neutral"),
    ("Glycon Therapeutics Quarterly Results In Line with Consensus",
     "No surprises. Stock trades flat post-earnings.",
     (0.97, 1.03), (-500_000, 500_000), "neutral"),
]
